### ISSUE TITLE
Navigation drawer max width is incorrect

### ISSUE THREAD

**Issue by afrolkin** [laurencedawson/reddit-sync-development#1000]
It looks like the navigation drawer width is currently equal to screen width - action bar height, which is correct for minimum width but according to the material design specs (http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs) the max width is equal to "five times the standard increment (56dp on mobile and 64dp on tablet)". 

The drawer looks a bit wide on my Nexus 6 on 520 dpi (especially when comparing the width to the drawer in Google apps).

**Comment by laurencedawson** [comment]
This has since been corrected. Cheers!
