### ISSUE TITLE
[Enhancement] When pressing back while editing a post/comment, it should warn you that the changes will not be saved, not that it will be discarded

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#1002]
In the end, they both mean the same thing, but I thought "not saved" would be more elegant than "discarded" in the context of the post/comment not being created from scratch, but edited.

**Comment by machinator2** [comment]
The dialog is now "discard changes". Is that clear enough?

**Comment by laurencedawson** [comment]
I think it's now clear enough!
