### ISSUE TITLE
[Feature Request] Improve handeling of albums

### ISSUE THREAD

**Issue by stthicket** [laurencedawson/reddit-sync-development#1004]
Feature 1: Text box should be closed by tapping outside of the box. This is currently only able to be closed with the back button, which is located at the bottom of the screen, and is awkward to reach sometimes. Tapping outside of the box or having a close button on the box would make it faster to use, and give a better workflow.

Feature 2: When pictures are accidetally tapped, the album closes, and it always starts on the first picture when reopened. If Sync instead remembers the last viewed picture, and continue from where it left, that would make scrolling through large albums very easy, and accidents would make it less annoing. It is very rare that one want (or need) to start over again in an album, but if they do, then the thumbnail grid would make it easy (because it always starts with first image).

Sorry if the english suck; I'm not a native speaker.

**Comment by laurencedawson** [comment]
1. This has been changed in recent versions
2. I've added position remembering for the next release

Cheers
