### ISSUE TITLE
Scrollbar on threads don't scroll properly

### ISSUE THREAD

**Issue by twig** [laurencedawson/reddit-sync-development#1006]
http://www.reddit.com/r/gamedev/comments/3dr6zs/i_just_released_my_first_ever_game_staq_for_ios/

This thread has super long OP text and while scrolling through that, the scrollbar doesn't actually move to reflect the true position.

**Comment by laurencedawson** [comment]
This has been fixed for the next release.

**Comment by twig** [comment]
Cool thanks.

On the topic of scrollbars, the notch when scrolling on subreddit pages seems to be missing too
