### ISSUE TITLE
[Feature request] Save images to SD card

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1010]
Request thread: https://www.reddit.com/r/redditsync/comments/3bj5jh/will_there_be_an_option_to_save_images_on_sd_card/

Hopefully this is possible with new Android 5.0+ APIs.

**Comment by laurencedawson** [comment]
Allowing the user to configure the save directory would be a great addition.

**Comment by laurencedawson** [comment]
Add for the next release.
