### ISSUE TITLE
[Feature request] Tag or categorize saved posts

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1011]
The ability to categorize saved posts using a tag or folder system would be nice.

Request threads: https://www.reddit.com/r/redditsync/comments/2bcbl3/feature_request_organizing_saved_posts/
https://www.reddit.com/r/redditsync/comments/3btmzs/tags_for_saved_posts/

**Comment by brett1337** [comment]
This is added for those with reddit gold. Long press the save icon.
