### ISSUE TITLE
[Feature request] Download gifv as gif

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1012]
You said it was on the to-do list [here](https://www.reddit.com/r/redditsync/comments/2y2m0o/_/), but I couldn't find it on the issue tracker. Second request thread from four months later [here] (https://www.reddit.com/r/redditsync/comments/3c6eru/annoyances_with_imgur_and_gifv/).

**Comment by m-p-3** [comment]
Would be useful for those like me who want to reshare/rehosts the gif file over others apps like Hangouts.

**Comment by machinator2** [comment]
Closing as this has now been implemented.
