### ISSUE TITLE
[Feature request] Search for subreddits without knowing exact name

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1015]
As stated in title. Not to be confused with the "casual" subreddit lookup function that Sync already has (seee #904). This might not be possible, but I thought it would be worth a request, in light of the change to the search interface on the main reddit website.

Request thread [here](https://www.reddit.com/r/redditsync/comments/3dh01c/searching_for_subreddits/).

**Comment by laurencedawson** [comment]
This is also known as an "explore" feature.

**Comment by laurencedawson** [comment]
Added for the next release.
