### ISSUE TITLE
Pop up ad scam on np.Reddit.com link

### ISSUE THREAD

**Issue by bringobrongo** [laurencedawson/reddit-sync-development#1017]
I went to this link http://np.reddit.com/r/buildapc/comments/3e16h7/what_is_the_best_antivirus_to_go_on_a_new_computer/ctamthw and when I did it popped up with a grey bar at the top and a notice about me being chosen to be a beta tester for an iPhone 7. Obviously it is a scam, but what it causing this? It can't be the website because np.Reddit.com is a legit Reddit link.

**Comment by machinator2** [comment]
This was a bug with the beta "load post content" feature. I don't think this really applies to the app anymore.

**Comment by laurencedawson** [comment]
@machinator2 is right. This was when the website was loaded in the background.
