### ISSUE TITLE
[Feature Request] Integrate with Imgur for "Send to..." Image Uploading 

### ISSUE THREAD

**Issue by livejamie** [laurencedawson/reddit-sync-development#1018]
I love your reddit client! I'm a happily paid user.

One of the features that I miss from Baconreader is the ability to go to the "Send to..." menu of a photo on my Android phone and easily create a post from it.

Reddit is fun also has this capability.

Thanks!

**Comment by laurencedawson** [comment]
Added for the next release. Cheers.
