### ISSUE TITLE
[Feature request] Addressing accidental image download/saves

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1020]
Because some phone companies (read: Samsung) like to mess with the standard nav button layout, many users have problems with accidental image downloads because of the back button's proximity to the save button on these phones. I know a relatively recent update tried to address this by adding more padding to the image toolbar, but it is still a common complaint: [thread 1](https://www.reddit.com/r/redditsync/comments/34wwnu/accidentally_saving_images/), [thread 2](https://www.reddit.com/r/redditsync/comments/3csuza/is_there_a_way_to_have_image_downloads_confirmed/), [thread 3](https://www.reddit.com/r/redditsync/comments/36lerv/request_move_download_button_from_image_links/).

Proposed solutions include a confirmation dialog for saving/downloading images (as an option), switching the order of the buttons on the toolbar, moving the toolbar to a different spot in the image viewer, or requiring a long press to save the image. I think the first suggestion would provide the best UX.

**Comment by laurencedawson** [comment]
In the alpha I've added a new bottom sheet to avoid this.

Cheers.
