### ISSUE TITLE
i.stack.imgur.com links become i.imgur.com links, which results in incorrect images

### ISSUE THREAD

**Issue by Pokechu22** [laurencedawson/reddit-sync-development#1023]
*Note: I am not a reddit sync user.  I'm simply reporting this bug because other users have reported it, so that it can be fixed.  I can't give versions as such, sorry :/*

Images hosted on [`i.stack.imgur.com`](http://i.stack.imgur.com) are redirected to `i.imgur.com`, even though the images there are different.  (stack.imgur.com is used by [StackExchange](http://stackexchange.com/) as an image host).  

This can have bad effects, such as [here](https://www.reddit.com/r/ProgrammerHumor/comments/3ewnyz/fox_explains_github/), where the redirected image is NSFW.

**Comment by MorganLG** [comment]
Happens to me on version 10.7.17.

Thanks

**Comment by Pokechu22** [comment]
Apparently fixed on imgur's side a while ago.  (It was an oembed issue on their side).  Closing.

**Comment by laurencedawson** [comment]
Thanks for the update.
