### ISSUE TITLE
Unable to view submissions outside of subreddits

### ISSUE THREAD

**Issue by adduc** [laurencedawson/reddit-sync-development#1024]
Example Link: https://www.reddit.com/comments/3es06a/37_hours_of_lucha_underground_in_37_minutes/

On my phone (Xperia Z3 on CM12.1), clicking on the link crashed Reddit Sync initially, and on subsequent attempts resulted in an empty view, with "error loading comments" text.

**Comment by machinator2** [comment]
Are you still seeing this issue?

**Comment by adduc** [comment]
Yes, on reddit sync v11.5.10. It looks like the [mobile Reddit](https://m.reddit.com/comments/3es06a/37_hours_of_lucha_underground_in_37_minutes/) website experiences issues as well (title loads, but no comments load).

**Comment by laurencedawson** [comment]
I've never seen those sort of links before. Are you seeing these regularly?

**Comment by adduc** [comment]
No, if I recall correctly, I had found the link through the "other discussions" tab of a [separate post](https://www.reddit.com/r/SquaredCircle/duplicates/3et25y/37_weeks_of_lucha_underground_in_37_minutes/). In the separate post, the link appears to be from the /r/promos subreddit

**Comment by laurencedawson** [comment]
Added support for the next release.
