### ISSUE TITLE
Flipping images

### ISSUE THREAD

**Issue by flyingpies155** [laurencedawson/reddit-sync-development#1027]
It seems that I can flip images in the image viewer. I think it had something to do with the double-tap-and-drag zooming. Steps to reproduce:
1. Open an image.
2. Double tap and hold.
3. Quickly swipe up.

It seems to sometimes take a few tries, but it does happen, and it doesn't seem like an intended feature.

Edit: This only happens when deepzoom is disabled.

**Comment by laurencedawson** [comment]
This has been fixed for the alpha. Thanks for reporting this issue.
