### ISSUE TITLE
No option to opt-in to quarantined subreddits.

### ISSUE THREAD

**Issue by bdonvr** [laurencedawson/reddit-sync-development#1029]
Quarantined subreddits only shows "Error loading posts." currently.

**Comment by flyingpies155** [comment]
There is no way to opt in to quarantined subs through the API, so you have to do it in a browser. Relevant redditdev post: https://www.reddit.com/r/redditdev/comments/3fx3gt/quarantined_content_will_be_unavailable_through/

**Comment by bdonvr** [comment]
Perhaps it can be configured to open the in-app browser to opt-in when visiting quarantined subreddits.

**Comment by flyingpies155** [comment]
The in app browser doesn't keep you logged in, though, does it? It would be a pain to have to keep logging in. I think it would be better to use a normal browser.

**Comment by bdonvr** [comment]
Perhaps, but it at least needs something more informative than "error loading posts".

**Comment by flyingpies155** [comment]
Well yeah, but the app hasn't been updated since quarantines were introduced.
