### ISSUE TITLE
The Unicode RTL character in flairs affects the "x ago" and "x points" strings

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1030]
See https://www.reddit.com/r/redditsync/comments/3gf6ae/the_unicode_rtl_character_in_flairs_affects_the_x/

Image: https://i.imgur.com/tLr1hxl.jpg

**Comment by laurencedawson** [comment]
Can no longer produce this. Cheers.

**Comment by laurencedawson** [comment]
Happening again:

**Comment by laurencedawson** [comment]
Fixed for the next release.
