### ISSUE TITLE
Sync is blocked in landscape after opening post link from app in landscape 

### ISSUE THREAD

**Issue by axeleroy** [laurencedawson/reddit-sync-development#1033]
Steps to reproduce bug :
1. Open Xzing Barcode Scanner
2. Scan any QR Code containing a reddit URL
3. Open link in Sync
4. Sync is blocked in landscape 

Version tested : Sync Dev 10.7.22

**Comment by kheidler** [comment]
http://developer.android.com/guide/topics/manifest/activity-element.html#screen

might be related to ```android:screenOrientation``` being set to ```behind```, maybe set it to ```user```?

**Comment by machinator2** [comment]
Are you still seeing this issue?

**Comment by axeleroy** [comment]
Good thing you raised the issue, as I haven't checked if it was fixed.
I'm using Sync 11.5.10 dev and the issue is still there as seen in this video https://gfycat.com/RawNimbleAustralianfurseal

**Comment by laurencedawson** [comment]
Android is a little better at handling this now, unable to repeat.
