### ISSUE TITLE
Reddit Sync crashes when trying to open "Messaging" 

### ISSUE THREAD

**Issue by EliasH97** [laurencedawson/reddit-sync-development#1038]
Hello, pretty straight forward problem - everytime I go to "Settings -> Messaging" the app crashes. I get the error message "Unfortunately, Sync Pro has stopped." 
Running it on 5.0.1 Samsung Galaxy S4, stock version.

**Comment by laurencedawson** [comment]
Hmm I've been unable to repeat this and the crashlogs are no longer showing this error. Closing for now.
