### ISSUE TITLE
[Feature Request] Swipe right to access inbox/profile/go to specific sub, etc ; option for back button to return to front page instead of exiting app

### ISSUE THREAD

**Issue by RevolverSloth** [laurencedawson/reddit-sync-development#1039]
Basically, I'm asking for functionality mimicking that of Relay for Reddit, where you can swipe right to access the menus that allows you to go to your profile, check your inbox, go to a specific subreddit, etc. I realize that there's a button in the top left that allows you to do all these things, but I have rather small hands and it makes Sync pretty uncomfortable to use one-handed. 

Also, if there could be an option for the back button to send you back to the front page after viewing a specific subreddit instead of closing the app entirely, that'd be nice.

**Comment by laurencedawson** [comment]
This has been added for the next release.
