### ISSUE TITLE
Markdown when replying

### ISSUE THREAD

**Issue by flyingpies155** [laurencedawson/reddit-sync-development#1041]
I was replying to a comment with a link in it recently, and in the area where it shows the comment you're replying to, it did not parse the markdown. Instead of showing something like like [Text](http://www.example.com), it showed something like \[Text\]\(http://www.example.com).

**Comment by machinator2** [comment]
I believe this is intentional. Several users requested that the app behave this way.

**Comment by laurencedawson** [comment]
@machinator2 is correct. This is the intended behaviour.
