### ISSUE TITLE
[Feature request] Remember or set default order per subreddit

### ISSUE THREAD

**Issue by ghost** [laurencedawson/reddit-sync-development#1042]
I prefer having my frontpage set to new and r/all set to hot, switching between new and hot all the time gets very tedious. This would be solved by having the ability to set a default order per subreddit, or remembering the last used order per subreddit.

**Comment by exzacklyright** [comment]
Also if if you could have it remember search settings as well that'd be great. So basically you can set a default view with a search or empty search

**Comment by laurencedawson** [comment]
Added for the next release.
