### ISSUE TITLE
Captcha not visible (black)

### ISSUE THREAD

**Issue by Timvdlinde** [laurencedawson/reddit-sync-development#1044]
The captcha is black when I try to post on a subreddit.
Android m developer preview 3
Nexus 5

Screenshot

**Comment by Timvdlinde** [comment]
http://imgur.com/k58VMVl

**Comment by akabhirav** [comment]
It isn't just a problem for M developer preview, the problem seems to be happing with anyone using the material designed app

**Comment by sillyman1** [comment]
This is also happening to me, Galaxy S6 Edge, Android 5.1.1 - very frustrating! Tried disabling AMOLED and night views made no difference.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
