### ISSUE TITLE
Numbered list autonomously restarted the counter

### ISSUE THREAD

**Issue by NetBender** [laurencedawson/reddit-sync-development#1045]
Hi, i was reading [this](https://www.reddit.com/r/oneplus/comments/3izejg/so_youve_just_bricked_your_oneplus/) post and i noticed that the numbered list restarted the count after "12".
Then i tried via browser and all was fine.

Screenshots:
 [Android view](http://imgur.com/BvapDHB) 
 [PC view](http://imgur.com/Ekvln50)

**Comment by laurencedawson** [comment]
This has been fixed for the next release. Cheers.
