### ISSUE TITLE
Refresh Button stops working after menu gesture

### ISSUE THREAD

**Issue by raid** [laurencedawson/reddit-sync-development#1046]
I'm using Reddit Sync in tablet mode on a Nexus 9. The refresh button opens a menu with two options. If instead of tapping the button to open the menu I swipe my finger downwards after pressing on the button without lifting my finger up and then choose one of the options, the button will not work the next time it is tapped.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
