### ISSUE TITLE
The 11th comment (counting the very first comment) does not load.

### ISSUE THREAD

**Issue by bringobrongo** [laurencedawson/reddit-sync-development#1047]
The 11th comment in a thread (red, 10th reply to a comment) will not load, even when I click on, "Show more." It just tries to load and then removes the option to show more. This isn't a specific comment thread either, all threads are like this. (Thread meaning a comment to a post and its replies, not the post itself. Sorry if that was confusing.)

**Comment by 2fst4u** [comment]
Can confirm. All threads only load a certain number of comments and no more

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
