### ISSUE TITLE
[Feature Request] Option to force phone layout

### ISSUE THREAD

**Issue by vassie79** [laurencedawson/reddit-sync-development#1048]
Taken from the sub, but a feature I would also like to see

> Is there any way I can use the single column layout from my N6 on my N9? I don't like looking at the comments from a previous post or an empty column when scrolling through posts. I'd basically like a blown up phone layout on my tablet. Is there a setting I'm missing or is this not possible? If it's not... Can it be?

**Comment by laurencedawson** [comment]
This has since been added. Cheers.
