### ISSUE TITLE
Livememe support - a quick fix

### ISSUE THREAD

**Issue by hypah** [laurencedawson/reddit-sync-development#1049]
There was a time when Sync loaded quick image previews of livememe links correctly, but it seems to have lost that ability at some point, and some users have expressed their frustration. Here is a simple explanation of how to make it work.

This is the typical livememe submission URL format on reddit: http://[www.]livememe.com/X[.jpg]

where "X" is the alphanumeric image ID. (Note: The file extension will often be absent.)

Sync's quick image view can then directly access the CDN by replacing the "X" in the following URL with the previously detected alphanumeric ID:

http://i.lvme.me/X.jpg

--------

Here is an example pair:

http://www.livememe.com/86soydd

becomes

http://i.lvme.me/86soydd.jpg

**Comment by laurencedawson** [comment]
Added for the upcoming v11 release.

Cheers.
