### ISSUE TITLE
The sync feature doesn't save comments

### ISSUE THREAD

**Issue by roman-ku** [laurencedawson/reddit-sync-development#1050]
It would be nice if the sync feature did more than just save the submission title and text in self posts. After all reddit sync was born to have offline capabilities and it was one of the first big selling features. This is not a priority but a nice thing to have, and I myself would use the sync feature a lot more if it saved comments on threads.

**Comment by machinator2** [comment]
Comment caching in v11 allows you to sync comments offline for individual threads, provided you enter the threads when online first.
