### ISSUE TITLE
$ inside code block disappears

### ISSUE THREAD

**Issue by Kehet** [laurencedawson/reddit-sync-development#1053]
**what it does**
it shows comment without $ -signs inside code formatting

**what you expect it to do**
it should show those signs as on using native browser

**reproducing**
creating new comment or text post like this

```md
lorem ipsum

    $this is $code c$o$d$e$ is this

more text
```

post is showing correctly on pc, but on reddit sync it loses all $ signs. this only happens inside code formatting. 

**version I'm using**
* Android 5.0.2
* HTC One m7
* Reddit Sync "newest from Google store" (couldn't find version number anywhere inside app)

**edit:** also \ seems to be disappearing

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.
