### ISSUE TITLE
Clicking post link while in comments view ignores external browser setting

### ISSUE THREAD

**Issue by PaulLFC** [laurencedawson/reddit-sync-development#1056]
If a post link is clicked while in subreddit / cards view, it'll obey the external browser settings and  open in the correct app (Chrome, Twitter etc). 

However if you click a post to go to comments view, and then click the post link (to the site/tweet/etc) at the top, the external browser setting is ignored and all links and tweets are opened in the internal browser.

**Comment by laurencedawson** [comment]
This has all been overhauled for the v11 release. Cheers.
