### ISSUE TITLE
[Feature request] A slideshow browsing mode for image heavy subreddits

### ISSUE THREAD

**Issue by JessenFuely** [laurencedawson/reddit-sync-development#1058]
The last time I saw this being mentioned was a year ago in this [post](https://www.reddit.com/r/redditsync/comments/2cm9fa/slideshow_view_option/) by [/u/Lightsout565](https://www.reddit.com/user/Lightsout565). As [/u/Lightsout565](https://www.reddit.com/user/Lightsout565) mentioned it would be nice if there  was a slideshow button that easily allows browsing images like in this [image](https://i.imgur.com/x8o7s6d.jpg). This would make browsing image heavy subs a lot better. Its one of the features many of the other Reddit apps have except for sync so I think it would be a nice addition.

**Comment by szeichorn** [comment]
yes, please make this a possibility.

**Comment by machinator2** [comment]
Seems like this has been implemented with the addition of the Slide view.

**Comment by laurencedawson** [comment]
Agreed. Closing!
