### ISSUE TITLE
Collapsing long comments skips too far down the page.

### ISSUE THREAD

**Issue by SZE2** [laurencedawson/reddit-sync-development#1059]
When collapsing a long comment, Sync will close the comment without moving the view back up to where that comment started.

This leaves you far down the page in the sublevel comments with no context for how you got there.

Can this be changed, so that when collapsing a comment, you only move to the next comment, not skipping to wherever the view was originally?

thanks in advance, this app is awesome!

**Comment by machinator2** [comment]
Are you still seeing this?

**Comment by laurencedawson** [comment]
Going to close this issue as comment navigation was completely rewritten for v11.
