### ISSUE TITLE
Metric conversion bot links are opening in app browser

### ISSUE THREAD

**Issue by Rdstrmfblynch79** [laurencedawson/reddit-sync-development#1061]
http://www.reddit.com/r/mapporn/comments/3okllo/afroamerican_travel_map_1942__a_guide_for_negro_hotels_and_guest_houses_in_the_eastern_usa_40003987/cvy9s5f

They used to open right in the comment section in a pop up.

**Comment by laurencedawson** [comment]
From the source I think this is expected behaviour. It's using mouseover events but if they fail opening the browser which is happening correctly.

Cheers
