### ISSUE TITLE
Relative links in posts/comments do not work properly

### ISSUE THREAD

**Issue by nandhp** [laurencedawson/reddit-sync-development#1063]
Relative links to posts and comments do not work properly in Sync. Here is an example post: https://www.reddit.com/r/test/comments/3lb8n9/foo_bar_baz_box/cw4rx04

* The relative link to a subreddit `[link](/r/test)` works.
* The relative link to a post `[link](/r/test/comments/3lb8n9/foo_bar_baz_box/)` does not work. (The built-in browser opens to `about:blank`.)
* The relative link to reddit's postcards page `[link](/about/postcards/)` does not work (I just get a weird popup that says "/about/postcards/".)

All of these links should work like the equivalent absolute link.

**Comment by laurencedawson** [comment]
This has been fixed for the next release. Cheers.
