### ISSUE TITLE
[Feature Request] Force HTTPS on Links

### ISSUE THREAD

**Issue by kamegami13** [laurencedawson/reddit-sync-development#1065]
Essentially I'd like built in support for this:
https://www.reddit.com/r/YouShouldKnow/comments/2n0zbl/ysk_how_to_view_imgur_photos_from_a_blocked/

Basically for certain sites that are known to support it like imgur, optionally force the link to be https.

**Comment by laurencedawson** [comment]
Sync already forces https for imgur.
