### ISSUE TITLE
Unable to load some user profiles

### ISSUE THREAD

**Issue by m-p-3** [laurencedawson/reddit-sync-development#1068]
I've noticed my user profile (https://www.reddit.com/user/m-p-3) is unable to load when you try to view the comments, trophies, etc, in Reddit Sync.

Here's some tests I've done with some other user profiles

/u/kn0thing: loads
/u/blake: doesn't load
/u/John: doesn't load
/u/downvoter: doesn't load

At first I though it could have been a trophy, a snoovatar or something unusual that could cause problem parsing the data, but I couldn't find anything common between multiple accounts that doesn't load. I've tried running a logcat and see if I could see any kind of error message, but it didn't give any positive results.

**Comment by laurencedawson** [comment]
I'm now unable to reproduce this. Guessing the v11 rewrite fixed this.

If you encounter this again let me know. Cheers!
