### ISSUE TITLE
Imgur Links

### ISSUE THREAD

**Issue by flyingpies155** [laurencedawson/reddit-sync-development#1069]
It seems that any link that contains the word 'imgur' will try to open as an image, and it will say that the image was not found. I discovered this while trying to click a link to /r/IgnorantImgur that I found in one post's comments. When I clicked open in browser, the link was to i.imgur.com/Ignoran.jpg

**Comment by laurencedawson** [comment]
This has been fixed for the upcoming v11 release. Cheers.
