### ISSUE TITLE
[Feature Request] Add Dual window support for LG phones

### ISSUE THREAD

**Issue by KeatonKafei** [laurencedawson/reddit-sync-development#1071]
http://developer.lge.com/resource/mobile/RetrieveDOCList.dev?categoryId=CTANRS030302###

Looks like it requires just a single line of code in the AndroidManifest.xml:
`<meta-data android:name="com.lge.support.SPLIT_WINDOW" android:value="true"/>`

**Comment by machinator2** [comment]
See also this thread:

https://www.reddit.com/r/redditsync/comments/3r88zd/can_we_get_dual_windows_support/

**Comment by laurencedawson** [comment]
This has since been added. Cheers.
