### ISSUE TITLE
[Feature Request] swipe ability from all screens

### ISSUE THREAD

**Issue by deronsizemore** [laurencedawson/reddit-sync-development#1072]
I love the ability to swipe to go back to the sub from comments. I think adding this feature everywhere would also be fantastic. This would be similar to Alien Blue (long time iOS user here; been on Android for a week). For example when you open a link and are viewing with built in browser, swiping to go back won't work there. Would also be nice to be able to swipe to go forward if possible. Like if you browse to a sub and then swipe from the left to go back, swiping from the right would then take you back into the sub you just left (good for when maybe you swiped and went back accidentally and want to head back into the sub without manually typing it in again)

Thanks

**Comment by laurencedawson** [comment]
I've added swipe to most sections of the app now but don't intend to add swipe to go forward. 

Thanks for the suggestion.
