### ISSUE TITLE
Tie settings/filters to currently selected account/user. 

### ISSUE THREAD

**Issue by oenomel2015** [laurencedawson/reddit-sync-development#1075]
EX... 
Account 1 (u/xyz)  is a work account, needs to be SFW, when in that account,  filters are set to hide NSFW Posts and Previews. 
Account 2 (u/zyx69) is a personal account, and doesn't need to be SFW, NSFW previews and and posts are active for that account.

**Comment by okungnyo** [comment]
How would this be implemented in a non-confusing way?

I think it would be simpler for you to just use two Reddit apps.

Like, use the free version with your work account and the pro version with your personal account.

**Comment by laurencedawson** [comment]
This has since been added!
