### ISSUE TITLE
(Feature Request) Immersive mode

### ISSUE THREAD

**Issue by spillytalker** [laurencedawson/reddit-sync-development#1082]
I was wondering if it could be possible when using an app like GMD immersive that the app could stretch out to use all pixels. Current when viewing a page the soft keys are hidden but the app stays the same height.  Viewing an image link will use the fullscreen which is great. This is using a nexus 6pp.

Thanks

**Comment by spillytalker** [comment]
Geez sorry about double post and typos.

**Comment by laurencedawson** [comment]
Sorry for the late reply. 

I'm going to go half way on this. In the alpha build I've set the status bar as translucent for a more immersive experience. I'm not the biggest fan of making the navigation keys transparent.

**Comment by spillytalker** [comment]
Thanks for the reply!
