### ISSUE TITLE
[Feature Request] Sidebar-free navigation

### ISSUE THREAD

**Issue by karlhe** [laurencedawson/reddit-sync-development#1083]
Not necessarily remove the sidebar altogether (like Youtube did), but It's a better user experience to be able to perform basic navigation without having to open the hamburger menu.

The main problem with the current layout of sync is the inability to switch to a different subreddit or multireddit without popping open the menu, which is a really common operation, even moreso than some of the easily accessible operations such as a new post (FAB), sorting (top navigation bar), and viewing the sidebar (swipe from right).

A lot of the "new" material design apps Google puts out use a tab-like design, where you can swipe left and right (or click the tab) to go to different section.

Slide for Reddit has an implementation like this to switch between subreddits (see https://lh3.googleusercontent.com/8dICkEpUqPM0UAxmSjj2ISE6zTWUOx0_SL8wjkcg9biFk0XoRAbEiULWw0azDfvmzQ=h900-rw), which I think is really well done. Additionally, after visiting a multireddit, the tab bar becomes a switch between multireddits instead. While the subreddit bar is only somewhat useful (you can be subscribed to a lot), but for multireddits it's really helpful since you'll only have a few and each will be "significant".

This isn't necessarily the only way it could be done, but it does solve the problem of not being able to easily navigate between multireddits.

**Comment by laurencedawson** [comment]
I've added the ability to change subs from the Toolbar for the next release.
