### ISSUE TITLE
Corrupted display of post with a one-line code segment with $1 in it.

### ISSUE THREAD

**Issue by ALuckyGuy** [laurencedawson/reddit-sync-development#1084]
In the PowerShell subreddit, I [posted](https://www.reddit.com/r/PowerShell/comments/3t6xa5/getrandom_looking_for_8_numbers_with_no_repeating/cx43y1z) a one-line code snippet that includes a regular expression:

`('{0:0}' -f (get-random -max (1e+18 - 1) -min 1e+17) -replace '(\d)\1+','$1').substring(0,8)`

Strangely, when *displaying* the post RedditSync seems to evaluate the $1 within regular expression itself, substituting the whole code snippet.

![image](https://cloud.githubusercontent.com/assets/3267060/11246159/716be340-8de4-11e5-8186-55118351218a.png)

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.
