### ISSUE TITLE
Writing HTML code in a comment such as <I> italicizes the rest of the comment instead of displaying <I>

### ISSUE THREAD

**Issue by Ashanmaril** [laurencedawson/reddit-sync-development#1087]
Found this out by accident. An example of what a comment is supposed to look like:  
http://i.imgur.com/ijimukO.png  
And here's how Sync displays it:  
http://i.imgur.com/b2VlAvP.png

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.

**Comment by laurencedawson** [comment]
Doesn't quite seem to be fixed.

**Comment by iwebhub** [comment]
Does this only happen with the <i> tag or do other HTML tags work? If other tags work as well, this could lead to XSS attacks. 

Although I don't see why comments get parsed as HTML at all, there's an easy way to prevent comment bodies getting parsed as HTML while still letting them pass through the parser, therefore disabling XSS attacks by replacing these characters with their HTML entities:

& --> &amp;
 < --> &lt;
 > --> &gt;
 " --> &quot;
 ' --> &#x27;    
 / --> &#x2F;

If this doesn't do much use, sorry, I just tried to help but I have zero experience in Java and Android.

**Comment by laurencedawson** [comment]
This has since been fixed.
