### ISSUE TITLE
Opening spoilers when "single click to hide comment is enabled" also hides the comment

### ISSUE THREAD

**Issue by lcc15** [laurencedawson/reddit-sync-development#1097]
When opening spoilers, the comment should not be hidden as the user will then need to find the hidden comment and unhide to continue reading. 

Same when it is disabled. Instead it shows the comment action buttons, while not as annoying as hiding, tapping on a spoiler should do nothing but open spoilers.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
