### ISSUE TITLE
Loading icon does not work properly if frontpage is empty

### ISSUE THREAD

**Issue by fnkr** [laurencedawson/reddit-sync-development#1098]
I use Multireddits for everything, so I have no subscriptions and my frontpage is empty. The problem is that the loading icon does not work properly if the frontpage is empty: it just never disappears. [Screenshot](https://i.imgur.com/9hlZ1AJ.png)

There's a [thread on Reddit](https://www.reddit.com/r/redditsync/comments/3vgthh/bug_loading_icon_does_not_work_properly_if/) too.

**Comment by laurencedawson** [comment]
This has since been fixed.
