### ISSUE TITLE
[Feature Request] Better At Handling Subreddit List

### ISSUE THREAD

**Issue by phendrome** [laurencedawson/reddit-sync-development#1101]
Hi there,

Coming from Windows Phone, with awesome reddit apps like Readit and Baconit, I was really spoiled with the way of handling my subreddit list with all my subscriptions.

Adding a star next to a subreddit to put them on top of the list would be awesome, or holding down to make them a favorite, or some other way. Dragging through my whole list takes ages right now, and it's really not a nice experience.

**Comment by laurencedawson** [comment]
I've improved the list significantly for the v14 beta.
