### ISSUE TITLE
Sync Pro - error loading token / loading posts

### ISSUE THREAD

**Issue by esillett** [laurencedawson/reddit-sync-development#1102]
Issue first started upon load of Sync pro...unable to send request, please check your network connection. Tried restarting, clearing app cache, uninstalling/reinstalling, revoking access via prefs on reddit, and now i cannot add account to Sync Pro, I get "error loading token"

**Comment by sudharsannr** [comment]
Second this. Same happens for me too.

**Comment by howardad** [comment]
Same here for Pro version. Although I didn't go to as much trouble as @esillett.

**Comment by howardad** [comment]
Further investigation shows that ad-supported version is also borked. Trying to add account gives "Error grabbing token".

**Comment by dscottboggs** [comment]
Also having this issue on sync pro

**Comment by El-Servas** [comment]
Also having this problem. On Pro.

**Comment by laurencedawson** [comment]
Reddit was down. Should be working again now.
