### ISSUE TITLE
If you filter the subreddit /r/Gaming then subreddits with the word Gaming in them also get filtered.

### ISSUE THREAD

**Issue by Primeey** [laurencedawson/reddit-sync-development#1104]
Finally. I've found what was causing my problem I've had ever since filters were added. How to reproduce this:

1) Add gaming as a subreddit filter
2) Navigate to pcgaming or any subreddit with the word gaming in it (A few examples would be legogaming, 	truegaming, IndieGaming)

Posts won't load and if you're subscribed then posts from the subreddit you tried to visit won't appear on your front page. This probably also works for other words.

**Comment by TaylorSanchez** [comment]
I tried to see if regex or quotes around the filter entry might fix this. I ended up crashing reddit sync with my filters that weren't working. Now I have to clear my cache. 

So don't try that...

**Comment by TaylorSanchez** [comment]
Recreated the crashing with single quotes. So probably a separate issue should be open that putting single quotes on a filter crashes the app, forcing you to clear the app data. 

I didn't find any way to fix the filter issue on the current version.

**Comment by Primeey** [comment]
Fixed in v11.2.1 :)

**Comment by laurencedawson** [comment]
At long last!
