### ISSUE TITLE
GIFs not loading ocassionally, espcially gfycat ones. Example included.

### ISSUE THREAD

**Issue by TyCooper8** [laurencedawson/reddit-sync-development#1105]
https://www.reddit.com/r/GlobalOffensive/comments/3x9g0n/sad_slide/

**Comment by tjansson** [comment]
I'm unable to load gifs at all. All I get is the following message "Error: Could not load video". It's been like this for a week or so. Have tried to clear cache, reinstall several times, but nothing seems to help.

**Comment by laurencedawson** [comment]
Are you still getting this issue? Cheers

**Comment by TyCooper8** [comment]
Nope! However I did get a new phone. But it's all been smooth sailing for
me for the past few months. I'm using the beta, also.

Ty
