### ISSUE TITLE
Profile overview not working.

### ISSUE THREAD

**Issue by HBOXNW** [laurencedawson/reddit-sync-development#1107]
I'm using sync pro on a Sony Xperia z3. Android 5.1.1

A couple of weeks ago the overview and comments part of my profile completely stopped working. 

I've tried reinstalling the app twice, the second time I restarted my phone between uninstalling and reinstalling. I've cleared the apps cache numerous times. 

It isn't my connection as everything else works fine. My profile still works using Chrome and Firefox. It fails both on 4g and wifi.

Please help.

**Comment by laurencedawson** [comment]
This was for the pre v11 re-release.

If you're still having the issue let me know and I'll re-open this ticket. Thanks.
