### ISSUE TITLE
[Feature Request] Add full screen in app web browser. 

### ISSUE THREAD

**Issue by usmcssgt** [laurencedawson/reddit-sync-development#1108]
Can you add a full screen option for the in app web browser? With the device notification bar + app header + app browser header and footer, the page is extremely small.

**Comment by laurencedawson** [comment]
In the V11 release Sync now uses Chrome Custom Tabs that automatically hides the Toolbar.

**Comment by usmcssgt** [comment]
I took a screen shot and highlighted what I was talking about.

**Comment by laurencedawson** [comment]
I think you forgot to attach it.
