### ISSUE TITLE
Viewing YouTube in fullscreen mode erases posts

### ISSUE THREAD

**Issue by DanHenry4** [laurencedawson/reddit-sync-development#1109]
When clicking a YouTube link, you can watch the video and click the back button without issue UNLESS you watch the video in fullscreen. If you watch it in fullscreen mode and go back to the post, it says "No posts to display" in the thread.

**Comment by DanHenry4** [comment]
I shouldn't have said "erases", because they're still there. It just doesn't load/display them properly after going back.

**Comment by laurencedawson** [comment]
I think this has since been fixed with the v11 release.
