### ISSUE TITLE
External links not opening

### ISSUE THREAD

**Issue by toddhuish** [laurencedawson/reddit-sync-development#1110]
I am not sure what I have to do to recreate the issue...I know, that makes it awesome for you.

The app will be working fine and then I'l click an external link to read an article more fully and...nothing. The link appears to start to load but the progress bar gets to maybe 15% and then stops. Once this happens Sync stops loading external links until I reboot the phone. There may be a less drastic way of fixing it but simply closing and re-opening or swiping it out of memory doesn't seem to fix it. 

The app still loads reddit links and will let me continue browsing. I can read messages, I can read self posts np.* posts but if the link goes to any external site...nothing. I can not even go to settings...other...licenses though settings...other....help and support works.

I am using the newest version of the client on LG's version of Android 5.1

**Comment by toddhuish** [comment]
New info! If I swipe the client out of memory it DOES seem to solve the problem...until it happens again. When I tried this last night it worked for 3 more links then stopped and I couldn't even go back to a link I had already clicked and have that work.

**Comment by laurencedawson** [comment]
Unfortunately this is caused by a bug in the Google WebView. There is supposedly a fix coming in the next month or two though from Google.
