### ISSUE TITLE
[Feature Request] Customizes Post Actions (e.g., I never hide posts, but frequently "view subreddit"

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#1111]
Morning, 

On each post, there are four buttons (upvote, downvote,  save, and hide). Then, hidden in the overflow are lots of other actions (like view subreddit, view profile, share, etc.). 

It would be really cool if we could customize the last two options available on each post. These two:

http://imgur.com/2BxgEfh

That way, we can speed up browsing, everyone gets what they want, and we can prevent some accidental button presses.

**Comment by laurencedawson** [comment]
This has since been added.
