### ISSUE TITLE
[Feature Request] Allow "browsing" while an image loads

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#1113]
Some of us use the app on slow internet connections. So, when you open an image, it covers the screen with the black transparency with the white loading bar on top. 

But, then you can't browse. You have to wait for that one image to load before doing anything else in the app.

It would be neat if sync could somehow let us "queue" an image so that, while it loads, we can browse text posts or even just scroll down the page. 

How to do this? I've no idea. It could be how those link apps work, whereby (if you have this setting on), the image loads in a little button that floats up and then opens automatically when it's loaded.

**Comment by laurencedawson** [comment]
If you close the image it continues to load :)

**Comment by ikjadoon** [comment]
OMG, you're right. I had no idea. But, when you open it a second time, the "progress bar" disappears. Is there a way to make that "stay" between different instances of opening the images? It might make it more visible that it's still loading in the background. 

I'm so excited. I'll just open like twenty images and then go back slowly later. Wow. Life changed.
