### ISSUE TITLE
Invalid MIME type

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#1114]
Getting the error on this image uploaded onto Dropbox:

http://www.reddit.com/r/battlefield_4_cte/comments/3yw0yl/_/

**Comment by laurencedawson** [comment]
Thanks. Looks like it's an image within a page. I've added a rule to fix this for the upcoming V11 release.

**Comment by ikjadoon** [comment]
Dope....you're awesome, :D
