### ISSUE TITLE
[SOLVED] Subreddits loading very slow despite good connection

### ISSUE THREAD

**Issue by Matthylonit** [laurencedawson/reddit-sync-development#1116]
I've encountered a problem opening subreddits on Reddit Sync.
The Frontpage is loading quickly, but when I try to open a specific subreddit it loads very slowly/not at all; the loading circle is rotating, but nothing happens!

I tried it on my 8mbps WLAN connection and on 4G/LTE: equally slow/not loading at all!

I'm using a Samsung Galaxy S6 (Stock ROM) running Android Lollipop 5.1.1 with the latest version Sync for Reddit (10.7.33)

**Comment by laurencedawson** [comment]
Closing as this has been marked as solved.

Just out of interest what was the issue?
