### ISSUE TITLE
Markdown: Sync parses backslash in codeblocks

### ISSUE THREAD

**Issue by pille1842** [laurencedawson/reddit-sync-development#1118]
When creating a codeblock by indenting a line with four spaces like this:

    This is a test.\n

The expected behaviour would be that the Markdown parser doesn't treat the backslash in any way, like the website does:

![Screenshot from desktop](http://i.imgur.com/AViI455.png)

Instead, Sync's Markdown parser hides it, allegedly trying to parse it:

![Screenshot from Sync](http://i.imgur.com/RnPKSJl.jpg)

**Comment by laurencedawson** [comment]
This has been fixed for the next release. Cheers.
