### ISSUE TITLE
Gifs not opening, size too large supposedly.

### ISSUE THREAD

**Issue by 6weaver** [laurencedawson/reddit-sync-development#1119]
Hello, I had this issue for a good while and I can't seem to find what's causing it. I'm using a Meizu Mx5 (mediatek soc -idk if it matters) and the issue happens without fail each time after opening the app (after cleaning cache) and viewing few gifs (in the album one loaded,and after that none of them worked) 
I've uploaded an imgur album with the screenshots,hope that you guys can figure it out. 
http://imgur.com/a/EhEgy  
-the gifs are obviously under 50 MB so that's NOT the issue.

**Comment by laurencedawson** [comment]
I think this has since been fixed.

Have you seen this since?

**Comment by 6weaver** [comment]
It was me who posted the bug thread on the subreddit when it was fixed.
Forgot about this github post.
