### ISSUE TITLE
Allow comments to be distinguished, and to show the [M] flag on distinguished comments

### ISSUE THREAD

**Issue by zhimsel** [laurencedawson/reddit-sync-development#1126]
The app doesn't appear to notice the flag at all, and you can't set it.

https://www.reddit.com/r/redditsync/comments/40mqlu/option_to_distinguish_comments/

**Comment by ikjadoon** [comment]
This is the same as stickied comments, right?

**Comment by zhimsel** [comment]
No, 'distinguished' and 'stickied' are two related, but separate flags.

**Comment by ikjadoon** [comment]
Oh, I see. Thanks for the clarification. If we can have it apply to sticky
comments, too, I'd be grateful.

**Comment by zhimsel** [comment]
It should by default. All 'stickied' comments are by definition also 'distinguished'

**Comment by laurencedawson** [comment]
Added for the next release.
