### ISSUE TITLE
[Feature Request] Continue browsing comments while YouTube player is active

### ISSUE THREAD

**Issue by pseeth** [laurencedawson/reddit-sync-development#1128]
Is there anyway to have the player, instead of being an overlay that closes when you click out of it, instead tile above the comments (like horizontal split-screen). That way, you can continue browsing comments while the video plays. Small thing, but would be nice, I think.

Thanks!

**Comment by laurencedawson** [comment]
The in-app youtube player is so flakey I don't really want to commit any more dev time to it.

However, this could be easily achieved by not using the in-app player with the new Android N split screen.

Cheers!
