### ISSUE TITLE
[Feature Request] Remember Readability Mode settings (dark mode, font style and size)

### ISSUE THREAD

**Issue by krompus** [laurencedawson/reddit-sync-development#1129]
I like to read articles using Readability Mode, with the "Dark" setting, but every time I open a page with it, it resets to default settings, despite having the option to sign in to my account with the Readability bar on the bottom.

[Also, the UI is frustratingly 1/3 offscreen.](https://dl2.pushbulletusercontent.com/ihqkkHLW4mi1QUhHga0Oc8PQ4sUbEwOb/Screenshot_2016-02-01-16-58-24.png). It's impossible to select the third font choice (not really a problem, since I prefer the sans font anyways), and the dark mode buttom only has a tiny part that is clickable (still possible, but finicky).

After fiddling with the UI for a bit every time I open an article, [I can get it to how I want it.](https://dl2.pushbulletusercontent.com/rn6hqTy7RKM0uUmDjsMoWjyu1g8fACrT/Screenshot_2016-02-01-16-58-42.png) 

This is pretty much the only thing I miss about Relay for Reddit (besides remembering comment folds); [the in-app readability viewer remembers settings.](https://dl2.pushbulletusercontent.com/ndbB83ciLfsiIDJCAdt4vbk1MMqnCNaF/Screenshot_2016-02-01-17-03-30.png) Perhaps we could look into how they did it, and implement the feature for Sync?

**Comment by laurencedawson** [comment]
Closing as I've switched to using chrome custom tabs.
