### ISSUE TITLE
[Feature Request] Remember comment folds.

### ISSUE THREAD

**Issue by krompus** [laurencedawson/reddit-sync-development#1130]
Comment folds are not remembered when navigating around, for example:

1) Open comment thread, fold a few comments.

2) Go back to links page.

3) Open same comments page, comments are reset.

This is currently one of the few things I miss about Relay for Reddit (indeed, Sync has many more benefits, and I will continue using it).

**Comment by laurencedawson** [comment]
This has been added previously. Cheers.
