### ISSUE TITLE
Viewing a spoiler with a "%" symbol in it crashes the app.

### ISSUE THREAD

**Issue by bdonvr** [laurencedawson/reddit-sync-development#1132]
https://www.reddit.com/r/redditsync/comments/43x4qh/putting_inside_a_spoiler_tag_will_crash_sync/

**Comment by iansan5653** [comment]
Confirmed. Using a Moto X 2014 with Marshmallow. On the alpha, both fail to display the spoiler but neither crash the app.

**Comment by ikjadoon** [comment]
This still happens on 10.7.39, actually. :(

**Comment by laurencedawson** [comment]
This has been fixed for the upcoming v11.5.11 beta. Cheers.
