### ISSUE TITLE
GIF doesn't load if I come back to it after a share

### ISSUE THREAD

**Issue by nanny07** [laurencedawson/reddit-sync-development#1134]
It's a small bug, nothing big just a little annoyance

To reprocude:

1. Open a GIF taping on the image
2. Press the share button
3. Choose any app to share
4. Press the back button
5. The GIF isn't loaded

This happens only with GIFs but not with images

**Comment by ikjadoon** [comment]
Yup, can confirm on 7.39 and OPO on CM13. Currently, you have to hit refresh first.

**Comment by laurencedawson** [comment]
Fixed for the next release.
