### ISSUE TITLE
Highlight upvote arrow on comments

### ISSUE THREAD

**Issue by tylershatto** [laurencedawson/reddit-sync-development#1135]
When I upvote a post, the arrow becomes orange to indicate that I have upvoted it. Having the comments do the same thing would be awesome. Sometimes I'm reading a long comment and I go to upvote it, but I'm not sure if I actually tapped the upvote button, or if I just tapped the comment itself, especially since both actions cause the bottom bar to be hidden. So then I have to scroll back up to the top of the comment to make sure it was upvoted. Thanks, this app is awesome and so is the dev

**Comment by ikjadoon** [comment]
This would be killer.

**Comment by laurencedawson** [comment]
This has been added in the alpha. Cheers.

**Comment by ikjadoon** [comment]
THAT'S DOPE. I LOVE IT.
