### ISSUE TITLE
[Feature Request] Redirect full imgur links to direct links

### ISSUE THREAD

**Issue by ExperimentalDJ** [laurencedawson/reddit-sync-development#1138]
This post brought this up to my attention... https://www.reddit.com/r/funny/comments/46c2v5/90_of_my_mobile_reddit_experience/d042nxg

Can we get any full imgur links to automatically open up the direct link instead? This would make it much faster it seems.

**Comment by laurencedawson** [comment]
Sync has had this for about 4 years!

But thanks for the report.
