### ISSUE TITLE
[Deepzoom Bug]

### ISSUE THREAD

**Issue by DragonSlapz** [laurencedawson/reddit-sync-development#1139]
https://i.imgur.com/Nhopuvn.jpg

Thumbnail: has colour
Deepzoom disabled: has colour
Deepzoom enabled: grayscale

**Comment by DragonSlapz** [comment]
http://www.reddit.com/r/funny/comments/46vove/_/

Link to reddit thread of that picture

**Comment by laurencedawson** [comment]
This has since been resolved with recent releases of Sync.

Thanks for taking the time to report this issue.
