### ISSUE TITLE
Non-animated GIFs treated as GIFs, unable to be zoomed or downloaded

### ISSUE THREAD

**Issue by SafariMonkey** [laurencedawson/reddit-sync-development#1140]
Take this GIF for example: https://i.imgur.com/O5YuPHy.gif

Sync assumes it's a gifv, so you can't zoom it (like you can't with animated GIFs) and if you try to download it, it 404s because it's presumably trying to use the gifv link. Also, the link I got when I hit copy link was gifv too.

This isn't a common issue, though, as non-animated GIFs are unusual nowadays.

**Comment by laurencedawson** [comment]
This has since been fixed and all gifs can now be zoomed. Cheers.
