### ISSUE TITLE
[Feature request] Add subreddit to multireddit

### ISSUE THREAD

**Issue by rykugur** [laurencedawson/reddit-sync-development#1143]
I started a post on /r/redditsync, seems relatively popular, to have this feature added in.

https://www.reddit.com/r/redditsync/comments/49z7br/feature_request_add_subreddit_to_multireddit/

Simply, I think it'd be a helpful feature to be able to add a subreddit to a multireddit, while viewing that subreddit (or perhaps even while viewing your multireddit).

**Comment by laurencedawson** [comment]
Added for v12.1. Cheers!
