### ISSUE TITLE
Domain Filters cause loading errors with comments/posts in user profiles

### ISSUE THREAD

**Issue by OneGoodReason** [laurencedawson/reddit-sync-development#1145]
After enabling a domain filter in the settings, comments and posts won't load properly inside profiles. The user's profile seems to fail to load any content, resulting in an infinite loading animation, while other profiles only load posts (not comments). This appears to happen with any domain filter. The domain filters appear to work properly when viewing subreddits, though.

**To reproduce this**, enable any domain filter in the settings (test, imgur, androidpolice). Go to the user's profile via the "Profile" button in the Navigation Drawer. No comments or posts will load.  Go back and view any poster's profile (via 3-dot menu on post). Only their posts should load.

Observed on Sync Pro, version 10.7.35. Also reproducible on Sync Alpha 11.0.5. 
Found after another user [reported an issue](https://www.reddit.com/r/redditsync/comments/4a05vs/profile_not_loading/) loading profiles on /r/redditsync.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
