### ISSUE TITLE
Subreddits starting with "self" have an incorrect domain for every selfpost

### ISSUE THREAD

**Issue by alexwh** [laurencedawson/reddit-sync-development#1147]
Example behavior on r/selfhosted: 
![screenshot_20160313-013248](https://cloud.githubusercontent.com/assets/1723612/13766272/5f668a80-ea58-11e5-8f90-4c6f3dd2c694.png)

Might be related to #141?

**Comment by laurencedawson** [comment]
This was a neat little bug. Fixed for the next release.
