### ISSUE TITLE
[ALPHA] Action bar is not always colored according to subreddit theme

### ISSUE THREAD

**Issue by danrant** [laurencedawson/reddit-sync-development#1149]
App version: 11.0.10

Navigate to a subreddit with themed action bar for example /r/projectfi. Action bar becomes green according to the subreddit theme. Open any post. The action bar becomes blue (default Reddit Sync action bar color). Status bar remains green. While it's not a big deal it's not pleasing to eyes. I expect action bar to remain the same color.

**Comment by laurencedawson** [comment]
As with the other issue the comments is being rewritten. The new version will support changing the Toolbar color too.
