### ISSUE TITLE
[ALPHA] Chrome Custom Tabs not working when Chrome is not default browser

### ISSUE THREAD

**Issue by danrant** [laurencedawson/reddit-sync-development#1150]
Reddit Sync: 11.0.10
Chrome: 49.0.2623.91
Android: 6.0.1
Phone: Nexus 5x
**Default browser: Flynx**
Reddit Sync settings: (default after installation) internal browser for links & Chrome Custom Tabs

Links are always opened in Flynx. That was confusing since I got used to Reddit Sync opening links in the internal browser. If I set Chrome to be the default browser then it works as expected: links are opened in a Chrome Custom tab.

It would be great if it either worked regardless of the default browser or "Chrome Custom Tabs" is automatically disabled if Chrome is not default and internal browser used.

**Comment by laurencedawson** [comment]
This is the expected behaviour of Chrome Custom Tabs and not something I can change in Sync.

**Comment by danrant** [comment]
I see. My main problem was confusion. A couple of suggestions for improvements:

1. Check if Chrome is not default and don't enable Chrome Custom Tabs upon upgrade or installation of Reddit Sync.
2. If user tries to enable the option and Chrome is not default, display a message.

**Comment by laurencedawson** [comment]
I've since added this behaviour.

Thanks for taking the time to submit this issue.
