### ISSUE TITLE
App crashes when pressing "Retry" [logcat included]

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#1151]
Logcat: http://pastebin.com/cJWDxcZt

Happens when you run out of posts and you tap Retry. Sometimes it works, sometimes it crashes the app.

Tested on a OnePlus One, CM12.1 (5.1.1). App versions affected: 10.7.37 and at least two versions before. Logcat is from 2-22.

**Comment by ikjadoon** [comment]
Any update? More than a few users have had this bug for months now.

**Comment by ikjadoon** [comment]
My phone even got the Marshmallow update and it's still happening.

 I'm on 10.7.39, too, on a OnePlus One now on CM13.

**Comment by ns-n0wl** [comment]
I have had this issue since release of Marshmallow on my HTC One M8 (Verizon)

**Comment by ikjadoon** [comment]
Oh, I think Laurence hasn't updated GitHub yet. I sent him an email follow-up and two weeks ago, he said, "This looks like a crash to do with the ListView, but in the Alpha I've completely reworked this. Hoping to get it to beta ASAP."

So hopefully, we're getting close. These little bugs are starting to stack onto each other, but the app usually works great 90% of the time.

**Comment by laurencedawson** [comment]
Yup this has been completely fixed in the alpha. Closing as yeah it's fixed.

**Comment by ikjadoon** [comment]
Hooray!! :D
