### ISSUE TITLE
Option to help prevent accidentally closing the hamburger menu.

### ISSUE THREAD

**Issue by maxsundell** [laurencedawson/reddit-sync-development#1153]
Whenever i scroll through my subreddits i keep accidentally closing the hamburger menu by scrolling at a slight angle. It would be really great if you could add an option to prevent you from closing the hamburger menu unless you swipe from the far right of the screen.

**Comment by laurencedawson** [comment]
I use the standard drawer and this is something that comes with the Android design lib.
