### ISSUE TITLE
All links in comments and text posts do not open in app on the N Developer Preview 1.

### ISSUE THREAD

**Issue by pyrogoggles** [laurencedawson/reddit-sync-development#1154]
All links to images and websites that are left in the comments or in text posts do not open in app like previously, they only open in Chrome. Also, reddit link handling (/r/ links, any links to reddit posts) doesn't work. Holding down on links also gives no context or options anymore.

Steps to reproduce: Open up a text post or comment section, then attempt to open a link, image, or reddit link.

Device: Motorola Nexus 6

Android version: Android N Developer Preview 1 Build #NPC56P

App version: 10.7.38

**Comment by laurencedawson** [comment]
This has since been fixed with subsequent dev previews.
