### ISSUE TITLE
[FEATURE REQUEST] Add a "Backup Settings" feature that includes filters

### ISSUE THREAD

**Issue by Gangreless** [laurencedawson/reddit-sync-development#1155]
The most recent update logged me out of the app and reset it back to "factory settings", I lost all 150+ filters I had set up. Being able to backup and restore all of the settings, including filters, would be a great feature.

**Comment by danrant** [comment]
Sync Alpha showed up in the list of backed up apps in Google Drive. You need Android 6.0 for that to work though.

**Comment by kefkf** [comment]
@danrant I'm using v11.2.1 (beta) on MM and reddit sync is not present on the list of apps using drive backup.

**Comment by danrant** [comment]
@kefkf it works for me. Sync Dev 11.2.1 on Android N preview 3.

**Comment by laurencedawson** [comment]
I've since added an option to manually export all settings + filters in the app in the settings under "backup".

Thanks for the report!
