### ISSUE TITLE
[Feature Request] Add option to add subreddit to filter list in 3 dot context menu on each post

### ISSUE THREAD

**Issue by Gangreless** [laurencedawson/reddit-sync-development#1158]
Something like this maybe, perhaps with a confirmation box to prevent accidental filtering:

http://i.imgur.com/gi6Nsef.jpg

I know at least 2 other apps now have this and it's way more convenient than having to type out subreddit names, especially when you sometimes can't remember how some of them are spelled.

**Comment by kefkf** [comment]
I would like to see this as a feature as well.

**Comment by ikjadoon** [comment]
Likewise!

**Comment by machinator2** [comment]
This has been added.
