### ISSUE TITLE
When editing comments and a user hits back, it should say "Discard changes?", not "Discard comment?"

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#1159]
A comment I already submitted and tapped "Edit comment": http://imgur.com/05mW1Xd

It says "Discard" at the top left. It makes it sound like it will discard the comment, not the changes (like it actually does). I think it could be reworded as "Back" to make it more clear.

Then, the confirmation will ask "Discard comment?". But, again, it's not going to discard the comment. It's going to discard our **changes**. Thus, it could be better worded as "Discard changes?"

**Comment by laurencedawson** [comment]
This has since been corrected. Cheers.
