### ISSUE TITLE
Loading bar missing for gifs already opened once

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#1160]
So, sometimes users back out of gifs that are still loading. Unknown to users, they are still loading in the background. If you open the gif again while it's trying to load, there is no notification bar, making the user think it glitched out / image is broken.

http://i.imgur.com/qG6n2YD.png

The loading bar should re-appear for these gifs while they are still loading.

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers!
