### ISSUE TITLE
App loses scroll position when users exit with "back"

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#1161]
See this video: https://streamable.com/oxfd

Twitter keeps its scroll position, no matter if the user presses home or back. Sync only keeps the position if the user presses home. 

The best solution, in my opinion, would be if the app treated "back" as home, and did not destroy the app, [as seen here](http://stackoverflow.com/questions/2000102/override-back-button-to-act-like-home-button).

**Comment by laurencedawson** [comment]
I respectfully disagree. I really think when you exit the app fully with back it should start a new session the next time you enter the app.

But I'll keep this issue open and maybe add an option in future.
