### ISSUE TITLE
Redd.it links break if not using https

### ISSUE THREAD

**Issue by tboxlive** [laurencedawson/reddit-sync-development#1162]
Within Sync, when opening a redd.it link that does not use https it throws an error. If the link does use https, it works. Example:

Works: https://redd.it/4buhar
Breaks: http://redd.it/4buhar

https://redd.it links opened from outside the application still run into the same issue noted here:
https://github.com/laurencedawson/reddit-sync-development/issues/984

![redd it-error](https://cloud.githubusercontent.com/assets/18078702/14056830/3ab55a26-f2bf-11e5-9848-9350f1727358.png)

**Comment by laurencedawson** [comment]
This has since been fixed. Thanks for the report.
