### ISSUE TITLE
[Feature Request] Hide post on vote option 

### ISSUE THREAD

**Issue by Megaqwerty** [laurencedawson/reddit-sync-development#1163]
What it says on the tin. Option that will cause posts to be hidden if they are voted upon. 

Thank you!

**Comment by Gangreless** [comment]
This is already a feature of reddit itself. You need to enable it in your preferences in the desktop site. 

Here :http://i.imgur.com/HPLoCWh.jpg

**Comment by Megaqwerty** [comment]
I was not aware! I also don't use the desktop browser to access reddit. 

Thank you!

**Comment by Megaqwerty** [comment]
Alright, so I enabled this and it is definitely more convenient. However, it's not exactly the same as clicking Hide Post in Sync because that latter option will also make the post physically disappear from the current view, even without a refresh. 

Would it be possible to implement that? That is, if hide on vote is enabled on the website settings, voting inside Sync will also remove the post from the current view. 

Thank you!

**Comment by laurencedawson** [comment]
I think for most users this would be the expected behaviour. Cheers.
