### ISSUE TITLE
[Request] Add to Friends List - Friends list colored usernames

### ISSUE THREAD

**Issue by Darhole** [laurencedawson/reddit-sync-development#1164]
the r/friends is a very useful reddit feature.
Add a 'Add Friend/Remove Friend' option when viewing a user's profile.
Color friends usernames across the site.  In normal reddit usernames turn orange, this is an awesome feature to quickly notice people you have an interest in posting.

Thanks!

**Comment by laurencedawson** [comment]
Merging:

https://github.com/laurencedawson/reddit-sync-development/issues/1093
