### ISSUE TITLE
after filtering multiple subreddits from /new, certain other subreddits or pages wont load.

### ISSUE THREAD

**Issue by d00mraptor** [laurencedawson/reddit-sync-development#1165]
After filtering subreddits, other subreddits are being excluded from my frontpage and will not load if directly selected from subreddit drawer. also other elements like my "profile" page will not load. unfiltering all subreddits fixes this issue.

**Comment by d00mraptor** [comment]
this has happened across multiple devices for multiple versions.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
