### ISSUE TITLE
Moderator menu item doesn't exist

### ISSUE THREAD

**Issue by mdszy** [laurencedawson/reddit-sync-development#1168]
On one account I have added to Sync, I am a moderator of multiple subs and the Moderator menu item isn't showing up, and I am unable to perform any moderator actions on mobile. I know that the Moderator menu showed up before on another account that I had since deleted from Sync, but it isn't showing up on this one, or any of the other accounts I have that mod subs.

**Comment by laurencedawson** [comment]
Can you try removing and adding your account back?

Cheers

**Comment by mdszy** [comment]
Well wha'dya know, that fixed it. Thanks a bunch!
