### ISSUE TITLE
All image links return 404 error

### ISSUE THREAD

**Issue by ADynamicOat** [laurencedawson/reddit-sync-development#1171]
My device is an LG G3 (d855) running cm13.0-20160407-NIGHTLY-d855. Reinstalling doesn't fix the issue. Didn't happen before the recent update.

**Comment by laurencedawson** [comment]
Is this still happening? Cheers.

**Comment by ADynamicOat** [comment]
Yes, it's still happening.

**Comment by laurencedawson** [comment]
Can you go to Settings > Images and enable "show image debug options".

Then open an image and swipe up from the bottom. It should show a debug log.

Can you take a screenshot of the debug log? Thanks

**Comment by ADynamicOat** [comment]
![screenshot_20160723-224227](https://cloud.githubusercontent.com/assets/17783078/17077934/0b7becc2-5127-11e6-8c2d-6023b62da82c.png)

**Comment by laurencedawson** [comment]
Odd. That link is working fine.

Does it work in the browser for you?

**Comment by ADynamicOat** [comment]
Yeah, it's fine when I open it in Chrome.

**Comment by laurencedawson** [comment]
Closing as this hasn't been discussed in a few years.
