### ISSUE TITLE
[Feature Request] Settings to change DNS or use VPN

### ISSUE THREAD

**Issue by hhjeremy** [laurencedawson/reddit-sync-development#1175]
Hi there from the non-developed part of the world. Approximately 2 Billion people leave in countries where the government is blocking websites or restricts some way of free access. 
I live in a country where imgur is blocked. We all know there is a way to circumvent those blocks like using a VPN (sometimes even this is not a solution, but anyways...)
My feature request would be to have few network options for reddit-sync where users would freely change how the app connects to internet (change dns, connect via proxy, use a built in vpn everytime the app opens and so on) and how users can access to reddit content.

**Comment by laurencedawson** [comment]
I think this should be down to the OS. Per app routing can already be achieved using a variety of apps on Google Play etc.

Cheers
