### ISSUE TITLE
Saved comments don't show up in the Saved section of the user profile

### ISSUE THREAD

**Issue by skylineKid712** [laurencedawson/reddit-sync-development#1179]
[Alpha](https://i.imgur.com/CBC8ZEE.png)
[Dev](https://i.imgur.com/JXkrncs.png)

**Comment by laurencedawson** [comment]
Are you using filters? Is this still happening? Cheers

**Comment by skylineKid712** [comment]
It actually got fixed a while ago. Thanks though!

**Comment by laurencedawson** [comment]
Perfect!
