### ISSUE TITLE
Sync feature not working

### ISSUE THREAD

**Issue by m4DnZ** [laurencedawson/reddit-sync-development#1181]
It stays stuck at 10%

**Comment by graingert** [comment]
@laurencedawson I can't even find the sync menu option anymore

**Comment by machinator2** [comment]
It was removed in the rewrite of the app and is currently under development.

**Comment by graingert** [comment]
@machinator2 @laurencedawson can we rename the app "for Reddit"

**Comment by laurencedawson** [comment]
This will be back in for the next release.

**Comment by graingert** [comment]
Sweet

**Comment by laurencedawson** [comment]
Fixed.
