### ISSUE TITLE
[Bug Alfa] youtube in landscape

### ISSUE THREAD

**Issue by Eideen** [laurencedawson/reddit-sync-development#1182]
The menu is hiden behind the dark overlay on top.
![screenshot_2016-05-13-19-32-40](https://cloud.githubusercontent.com/assets/1884894/15256392/a4208e4c-1941-11e6-9c81-290579d58611.png)

For some reason the youtubeplayer auto stops in landscape.

testet on a sony z2 tablet.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
