### ISSUE TITLE
Used "remove ads" but don't have pro? 

### ISSUE THREAD

**Issue by pfluegs** [laurencedawson/reddit-sync-development#1185]
Are these two different things? Do I have to pay twice? If not, does pro have ads? Can I get refund for the ad removal and purchase pro instead?

**Comment by jkgao** [comment]
There's two main versions of the app (not counting the dev version). Sync for Reddit and Sync for Reddit (Pro). It seems like what you did was that you have the Sync for Reddit app and you removed the ads via an in app purchase (IAP). This essentially gives you the same functionalities as the pro version but it doesn't grant you to have the pro version in Play Store.

**Comment by laurencedawson** [comment]
@jkgao is spot on. Unfortunately I can't link the two versions with a single purchase, but the two are identical. 

Cheers.
