### ISSUE TITLE
Nightmode toggle 

### ISSUE THREAD

**Issue by m4DnZ** [laurencedawson/reddit-sync-development#1186]
I think it would be more handy with a toggle instead of another menu behind the 'night mode's option and the auto feature would be a checkbox in the settings.

**Comment by machinator2** [comment]
There is a night mode toggle in the three-dot menu in subreddit view. Is this what you were looking for?

**Comment by m4DnZ** [comment]
Notice the date this was posted

**Comment by muffinz** [comment]
Related: night mode toggle in navigation drawer like in the [Twitter app](https://gfycat.com/NearNiceHare)

**Comment by m4DnZ** [comment]
Holy shit yes!
