### ISSUE TITLE
Scrolling in text body when trying to compose lengthier text post is rather difficult 

### ISSUE THREAD

**Issue by Rdstrmfblynch79** [laurencedawson/reddit-sync-development#1190]
When I go to write up a decent length text post and then have to go back to review a part that requires scrolling up, I find that it's extremely difficult to get to an exact position within the text. The only way I can scroll is by using the text "cursor" and then dragging it up. The problem is it goes 0-60 way too fast. It appears comments do not have this problem. 

*Using LG G3 - latest beta version (.4), but this has been an issue since before the alpha.

**Comment by laurencedawson** [comment]
Expanded the box to show up to 10 lines at a time.

Cheers.
