### ISSUE TITLE
Cannot unhide posts

### ISSUE THREAD

**Issue by chanhhuynh** [laurencedawson/reddit-sync-development#1191]
Once a post is hidden, it cannot be 'unhidden'.

Steps to replicate:

1. Hide a post
2. Go to profile and the 'Hidden' posts page
3. Open the 3-dot menu on the post and select 'Unhide'

The 'Hidden' dialogue pops up and the post remains hidden outside of the 'Hidden' section of the profile page.

**Comment by machinator2** [comment]
This works now as of 11.5.10 (beta).
