### ISSUE TITLE
[BUG] Comment Spoilers End Early After Nested Right Parens

### ISSUE THREAD

**Issue by technizor** [laurencedawson/reddit-sync-development#1192]
Comment spoilers that have been tagged through the usage of markdown's hover text will end when a right paren is first encountered, leaving the remainder of the spoiler text completely visible.

`[Warning](#s "Spoiler Text (Here) This should be hidden but is instead visible.")`

[Test Comment](https://www.reddit.com/r/redditsync/comments/4kujk2/sync_for_reddit_v1123_beta_is_now_going_live_on/d3i9l9r) (Only the spoiler section is relevant, the rest of the issues raised appear to be fixed.)
![Screenshot from beta v11.2.8](https://cloud.githubusercontent.com/assets/7350359/15630496/e990ddda-250b-11e6-9bc8-8092b284588f.png)

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.
