### ISSUE TITLE
Option to save imgur webm or gifv as gifs

### ISSUE THREAD

**Issue by zack6849** [laurencedawson/reddit-sync-development#1194]
Hi there, I find often imgur shows moving images as webm or gifv, which is nice, however if the content is meant to loop (as it usually is), webm playback doesn't work so well, as it doesn't Loop them with most media players.

Could you possibly add an option to save imgur gifv or webms as plain gifs?

**Comment by laurencedawson** [comment]
This has since been added. Thanks for reporting this issue.
