### ISSUE TITLE
[Feature Request] Pull down to close

### ISSUE THREAD

**Issue by ds84182** [laurencedawson/reddit-sync-development#1197]
In the latest version there is a new animation that shows the Reddit post transitioning into the full screen version. The problem now is that swiping right to close now (personally) looks and feels really bad. The right swipe makes it seem like the post gets cloned and pushed aside.

I'm requesting a Google Inbox (or Plaid) like drag down to close gesture just for the sake of consistency. It would be great if the change was optional too (otherwise this would hit a lot of resistance).

**Comment by laurencedawson** [comment]
I'm not sure it would work as it would conflict with pull to refresh...
