### ISSUE TITLE
[Feature Request] On the fly account switching

### ISSUE THREAD

**Issue by BakedBroccoli** [laurencedawson/reddit-sync-development#1202]
I come from the land of Antenna (Formerly AMRC) on iOS. 

In that app, we are able to switch reddit user accounts **anywhere in the app without losing our place.** 

That means if I'm reading through a comment thread and I see a comment I want to reply to with a different account, I am able to switch accounts **on the fly** without losing my place in the thread.

Here are some screenshots to show you how Antenna (amrc) handles it.

![asset](https://cloud.githubusercontent.com/assets/8946997/15805792/2247c9a4-2b6f-11e6-92fa-b765d953e8ad.PNG)

You touch my username (anoxy) at the top, and this menu pops up from the bottom showing all of my other accounts. When I make the switch, I am back where I was so I can resume making my comment.

![asset 1](https://cloud.githubusercontent.com/assets/8946997/15805793/22492e8e-2b6f-11e6-9c28-31ab16b51434.PNG)

**Comment by laurencedawson** [comment]
Merging:

https://github.com/laurencedawson/reddit-sync-development/issues/795
