### ISSUE TITLE
[Feature Request] Handle compose message links

### ISSUE THREAD

**Issue by matthieugrieger** [laurencedawson/reddit-sync-development#1203]
Hi!

Currently message compose links open up in the in-app browser, meaning the user has to sign in again in order to send the pre-composed message. It would be really nice if it brought up the messaging screen in the app instead with all of the information filled in.

Here is a comment with a link that demonstrates this behavior: http://www.reddit.com/r/pcmasterrace/comments/4mmu3i/_/d3wvnu5

Clicking on the link to send a PM opens the link in the in-app browser instead of using the messaging portion of the app.

**Comment by laurencedawson** [comment]
Added for the next release.

**Comment by matthieugrieger** [comment]
Awesome, thanks! You're really going to town on these issues. :)
