### ISSUE TITLE
[BUG] Entire posts become blank at times

### ISSUE THREAD

**Issue by davidschaeffer2** [laurencedawson/reddit-sync-development#1204]
Not sure how I triggered it exactly, but I experience entire posts going blank on my Moto X, Android 5.1, Sync Pro version 11.3.8. 

Screenshot: http://i.imgur.com/AMC7duG.png

If I tap on the blank spot, it'll still open the link and/or comments. If I refreshed the screen by dragging down from the top, it would make the post above it blank out. They swapped blanking out back and forth on each refresh.

**Comment by laurencedawson** [comment]
Can you try upgrading and see if this still persists?

**Comment by davidschaeffer2** [comment]
It doesn't seem like an issue anymore. I haven't noticed it for the last 2 builds or so. I also don't have my moto anymore after deciding to take a dip with it in my pocket. You can probably close this now. (I honestly forgot I opened this! Sorry.)

**Comment by laurencedawson** [comment]
Cheers!
