### ISSUE TITLE
[BUG] Saves images hosted on {i.reddituploads.com} as text files and not as jpgs

### ISSUE THREAD

**Issue by joey022** [laurencedawson/reddit-sync-development#1206]
**Description**
When you download images that are hosted on i.reddituploads.com (NOT i.redd.it/ etc.) it saves it as plain text files.You then have to go to your file manager and chane the file extentions manually to .jpg.

**Scenario**
1.View a image that's hosted on i.reddituploads.com eg. on a subreddit such as r/awww.
2.Click download image
3.Go to File Manager 
4.Search for file that was saved

**Result(s)**
Sync would have saved the image as a .txt file instead of a .jpg file 

**Device Info**
Device Model - Galaxy S3
Android Version - Android M (6.0.1) (Cyanogenmod 13)
sync version - Sync Free v11.4

**Comment by laurencedawson** [comment]
Fixed in the latest beta. Cheers.
