### ISSUE TITLE
[BUG] Messaging settings being ignored

### ISSUE THREAD

**Issue by zoomy942** [laurencedawson/reddit-sync-development#1208]
It has been tested by various users in the subreddit.  The messaging settings are ignored.  If they are off, notifications will still happen outside the app.  If they are on, the interval is also ignored.

https://www.reddit.com/r/redditsync/comments/4ocxpa/testing_possible_messaging_bug/

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
