### ISSUE TITLE
[Feature Request] Option to mark scrolled past posts as read

### ISSUE THREAD

**Issue by YoYoost** [laurencedawson/reddit-sync-development#1211]
Hi,

I am subscribed to a few subs where I don't read all the posts. 'Slide' has a feature where a post can be marked as read when you scroll it out of the window.
I couldn't find another Feature Request for this so I figured I added it.
Thanks in advance!

**Comment by marcusti** [comment]
+1
Got used to this feature in Boost.

**Comment by laurencedawson** [comment]
Added for the next release.
