### ISSUE TITLE
[Feature Request] Better Mod Tools!

### ISSUE THREAD

**Issue by Hareuhal** [laurencedawson/reddit-sync-development#1213]
Please, please, please implement better mod tools. Reddit Sync / Sync for Reddit is my absolute favorite mobile Reddit application, but when I'm on my phone, I'm forced to either use Relay, Reddit is Fun, or my phone browser to do moderating on the go.

The mod tools on Reddit Sync are abysmal. Mod Mail that only shows the original message - **but no responses**, is horrible. I get notifications that I have unread ModMail, but don't even bother checking it., then Moderated / Unmoderated Queues.

No ability to remove posts, ban users, sticky posts/comments. 

Please implement better mod tools. I don't want to continue using other Reddit apps - none of them are as good as Reddit Sync, but Mod Tools are one area where there is a serious lack of love

<3

**Comment by machinator2** [comment]
Add viewing report reasons (for both comments and posts) to that.

**Comment by machinator2** [comment]
I'll add to this: ability to refresh moderated subreddits without having to log back in and back out: https://www.reddit.com/r/redditsync/comments/4y4hue/request_moderated_subreddits_refresh_button/

**Comment by muffinz** [comment]
#1401 duplicate

**Comment by laurencedawson** [comment]
>  Mod Mail that only shows the original message - but no responses, is horrible.

[Threaded messaging has been added today](https://github.com/laurencedawson/reddit-sync-development/issues/719)

> No ability to remove posts, ban users, sticky posts/comments.

You can already remove posts, I've added the ability to ban users and sticky comments today. You can already sticky posts.
