### ISSUE TITLE
[Feature Request] Add touch ripples to navigation drawer list items and cards

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1214]

**Comment by laurencedawson** [comment]
Also referenced on reddit:

 - /r/redditsync/comments/4hpgii/_/d2rr3mu
 - /r/redditsync/comments/4hvmwq/_/d2vefwg

**Comment by laurencedawson** [comment]
Merging:

https://github.com/laurencedawson/reddit-sync-development/issues/696
