### ISSUE TITLE
[Feature Request] Add animation feedback when upvoting

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1215]
Hi LJ,

There's this nifty, lightweight library that adds popping animation effects similar to Twitter's heart animation. It's called [SparkButton](https://github.com/varunest/SparkButton). There's also a demo video and demo app available on the Play Store.

Thanks!

**Comment by machinator2** [comment]
Is the current upvote/downvote animation insufficient?

**Comment by laurencedawson** [comment]
Where would this be used?

**Comment by DW1045** [comment]
The SparkButton animation could be used for when saving posts

**Comment by laurencedawson** [comment]
Sync already uses a circular reveal animation here.
