### ISSUE TITLE
Upvote, Downvote, and Favorite Buttons Hidden on Nexus 6P Dual-Card View (After Recent Update from 2 weeks ago)

### ISSUE THREAD

**Issue by random6969** [laurencedawson/reddit-sync-development#1217]
I've noticed a weird bug on my Nexus 6P since the app update from 2 weeks ago. The upvote/downvote and favorite buttons are hidden on my Frontpage when in landscape mode, with 2 columns of cards.

/u/ljdawson stated in a previous Reddit comment that "This is intentional due to the limited space."

However, there is plenty of whitespace to show the vote arrows and the favorite button.

http://i.imgur.com/xxYNKiH.png

Please consider adding these buttons back. In particular, the lack of voting arrows is a major annoyance, as I have to open each post manually to vote. And I can't tell at a glance which posts I've already voted on.

**Comment by laurencedawson** [comment]
This has been fixed in the latest beta. Cheers.

**Comment by laurencedawson** [comment]
Fixed for the next release.
