### ISSUE TITLE
Multireddits: Treat multireddits and subreddits the same in the subscription list. No more separate lists.

### ISSUE THREAD

**Issue by bentrop** [laurencedawson/reddit-sync-development#1220]
In the subscription list, treat multireddits like regular subreddits.
No separate list, let the user sort them the way they seem fit.
Mark them, but don't separate them.

See e.g. Relay for Reddit, Dash for Reddit

Upon initial import, don't append multireddits at the bottom of the list but either at the top (since they are mostly used for managing the subscribed subreddits by those who use them) or alphabetically within the regular subreddit list (most clients do this).

**Comment by laurencedawson** [comment]
This has since been introduced.
