### ISSUE TITLE
[Enhancement] Add animation when tapping on app bar to scroll to top

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1226]
edit, related: add animation when collapsing / expanding _Subreddits_ and _Multireddits_ in navigation drawer

**Comment by machinator2** [comment]
Do you have a specific animation from the material guidelines in mind?

**Comment by muffinz** [comment]
Any animation should be fine. It helps prevent the abrupt jump to the top of the view. Here's an article on [duration and easing](https://material.google.com/motion/duration-easing.html). The eased linear animation found under _Natural easing curves => Standard Curve_ may be helpful.

**Comment by laurencedawson** [comment]
Added for the next release. Cheers.
