### ISSUE TITLE
Content Filter (Images, Albums, GIFs, Videos, Links, Selftext, NSFW, Gilded)

### ISSUE THREAD

**Issue by bmcclure937** [laurencedawson/reddit-sync-development#1229]
Post List - Overflow - Content Filter (Images, Albums, GIFs, Videos, Links, Selftext, NSFW, Gilded)

This will provide the user quick access to filter the current view (FrontPage, All, Subreddit, Profile, etc.) from the overflow. This also allows for quickly toggling NSFW off/on).

**Comment by laurencedawson** [comment]
This has since been added!
