### ISSUE TITLE
Theme Engine Enhancements

### ISSUE THREAD

**Issue by bmcclure937** [laurencedawson/reddit-sync-development#1232]
1.  option for opacity of nav bar
2.  color chooser for app theme
3.  individual subreddit themes
4.  individual Font Settings
5.  drawer image (account chooser)
6.  post view options - show new comment count
7.  post view options - left hand mode

**Comment by machinator2** [comment]
Customize fonts for messages as well: https://www.reddit.com/r/redditsync/comments/519n6p/feature_request_add_font_customization_to/

**Comment by laurencedawson** [comment]
Most of these have since been added.
