### ISSUE TITLE
[Cosmetic] Sidebar list dividers have incorrect opacity and height

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1239]
[**Dividers**](https://material.google.com/components/dividers.html)

In Reddit Sync, sidebar list dividers only have a thickness of 1px and not 1dp. They are also darker than 12% black on the light theme.

**Specs**
- Thickness: 1dp
- Opacity: 12% black or 12% white

edit: list dividers in the settings are also darker than 12% black

**Comment by muffinz** [comment]
subjective: I think the sidebar list items might look better if it looked like the navigation drawer

**Single-line list specs** for trending sidebar on /all and /frontpage
- Font: Roboto Regular 16sp
- Height: 48dp
- Left and right padding from screen edge: 16dp
- Top padding: 8dp

**Single-line list with icon specs** for subreddit sidebar
- Font: Roboto Regular 16sp
- Height: 48dp
- Icon padding, left: 16dp
- Text padding, left: 72dp
- Top padding: 8dp

**Comment by laurencedawson** [comment]
These have since been removed.
