### ISSUE TITLE
[Request] Add support for CSS flairs

### ISSUE THREAD

**Issue by DW1045** [laurencedawson/reddit-sync-development#1240]
Sync has introduced a flair picker recently and due to most subs using CSS flairs as the default, a lot of flairs on most subreddits come up as blank.

The flairs does have texts accompanying them. 

E.g., selecting a flair in Slide for Reddit: http://i.imgur.com/csblcHz.png
vs selecting a flair in Sync for Reddit: http://i.imgur.com/I5tuesi.png

Both are displaying flairs from the same subreddit, /r/leagueoflegends, however slide has the text accompanying the flairs shown.

This support for the CSS flairs to be shown in the flair picker and in the comments would solve the issue of the blank flairs! 👍

**Comment by laurencedawson** [comment]
Added for the next release.

**Comment by DW1045** [comment]
Thank you!!
