### ISSUE TITLE
Move 'mark as read' button to post action bar for easier access

### ISSUE THREAD

**Issue by elmkzgirxp** [laurencedawson/reddit-sync-development#1244]
[done icon](https://design.google.com/icons/#ic_done) or [visibility icon](https://design.google.com/icons/#ic_visibility)
[visibility off icon](https://design.google.com/icons/#ic_visibility_off) when marked as read to mark as unread

**Comment by laurencedawson** [comment]
I've since added an option to customize the FAB.
