### ISSUE TITLE
Use 'view comfy' icon for album overview instead of 'grid on' icon

### ISSUE THREAD

**Issue by elmkzgirxp** [laurencedawson/reddit-sync-development#1254]
[view comfy icon](https://design.google.com/icons/#ic_view_comfy)
[grid on icon](https://design.google.com/icons/#ic_grid_on)

**Comment by muffinz** [comment]
I think the grid on icon may be more appropriate because the actual grid is 3 columns wide.

**Comment by elmkzgirxp** [comment]
How about [this](https://design.google.com/icons/#ic_view_module)?

**Comment by laurencedawson** [comment]
Updated to the "view module" icon.
