### ISSUE TITLE
Streamable logo inconsistency

### ISSUE THREAD

**Issue by f-d** [laurencedawson/reddit-sync-development#1258]
When viewed in list/compact, could links to Streamable show the same logo (that little infinity symbol) that they do in full height/fixed height cards? Currently they show the image logo that you'd get on an Imgur link or similar.

I know that the site is listed, but the logo discrepancy makes a bit too easy to open a link with sound when you're expecting a silent one.

**Comment by laurencedawson** [comment]
I've since added the option to auto mute links which I think solves this issue. Cheers!
