### ISSUE TITLE
[Request] Alphabet on the subreddit list

### ISSUE THREAD

**Issue by cutterrojo** [laurencedawson/reddit-sync-development#1259]
This would add the alphabet along the right side of the pull out subreddit list which would allow the user to quickly jump to the desired letter location in their subreddit list. For an example/inspiration, the app sidebar in Action Launcher 3 or most contact apps.

This is a quality of life feature

**Comment by laurencedawson** [comment]
I've since added a text input box to the top of the sub list for fast browsing.
