### ISSUE TITLE
Selftext spoilers in card view mode

### ISSUE THREAD

**Issue by brianatlive** [laurencedawson/reddit-sync-development#1260]
Some subreddits often either tag/title a post as a spoiler or NSFW instead of spoiler tagging the text itself and this means spoilers are visible in the card view preview. Could you please make it so that selftext spoilers like the ones below are blocked while using cards. Thanks!

[Titled as a spoiler](https://www.reddit.com/r/asoiaf/comments/4v6rq1/spoilers_everything_dany_has_a_vision_in_the/)

[Flaired as a spoiler](https://www.reddit.com/r/books/comments/4v0nw6/convinced_my_45_year_old_wife_to_read_where_the/)

[Titled a spoiler and flaired NSFW](https://www.reddit.com/r/SquaredCircle/comments/4v3ftd/main_event_spoilers_mojo_rawley_is_over_as_hell/)

**Comment by laurencedawson** [comment]
I've since added support for the official spoiler tag.
