### ISSUE TITLE
Remove 2dp rounded corners in settings

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1265]
[**Screenshot**](http://i.imgur.com/oyhCukU.png)
[**@ 3x zoom**](http://i.imgur.com/ZUo7qfk.png)

reference: stock Android settings app and Nova Launcher settings do not have rounded corners on the full width card containers

**Comment by muffinz** [comment]
related: list items in settings do not line up to the 72dp list keyline

[Screenshot](http://i.imgur.com/1qfPvix.png)
[Keylines](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B6Okdz75tqQsNVlYYkdnMktUVmc/layout_metrics_keyline_mobile8.png)

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.
