### ISSUE TITLE
"Couldn't load any more posts" clips upvote/downvote buttons

### ISSUE THREAD

**Issue by jharder** [laurencedawson/reddit-sync-development#1267]
In the sub view, profile view, or basically anything where "Couldn't load any more posts/comments" notification can appear, it won't go away and blocks access to the bottom bar of "X points/Y comments, upvote/downvote, star, menu".

I should note that I've configured mine to put post titles above the post content, though this happens in the default mode as well.

Device: Nexus 6P
OS: Android 6.0.1
Sync version: 11.6.1

Repro: Visit r/zoo and scroll all the way to the bottom (only like 4 pages, so not that far). Any reddit with at least slightly more than 1 scroll of posts should repro though.

**Comment by laurencedawson** [comment]
This bar can now be swiped away.
