### ISSUE TITLE
[Theme engine enhancement] Customize subreddit font in subreddit view

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1270]
- Colors
- Bolding/Italics
- Font type

https://www.reddit.com/r/redditsync/comments/4vbf55/make_subreddit_names_standout_on_posts/

**Comment by jagruk** [comment]
Would love this feature

**Comment by laurencedawson** [comment]
~~- Bolding/Italics~~

**Comment by laurencedawson** [comment]
This has since been added.
