### ISSUE TITLE
Consolidate info in user profile view

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1271]
https://www.reddit.com/r/redditsync/comments/4vb2rz/suggestion_combine_profile_info_cards_into_one/

[Current view](http://i.imgur.com/klYCf6G.png)

[Mockup](http://i.imgur.com/51VMMcJ.png)

**Comment by laurencedawson** [comment]
Going to close this as I actually prefer how it is now!
