### ISSUE TITLE
[Bug] Post cannot be scrolled vertically when a table is horizontally scrolled

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1272]
See [this thread](https://www.reddit.com/r/redditsync/comments/4vcuil/feature_maybe_bug_allow_vertical_scroll_when_a/) for more information.

**Comment by mikestephens** [comment]
Hi I am the OP! Would be more than happy to give additional info if needed.

**Comment by laurencedawson** [comment]
Fixed for the next release.
