### ISSUE TITLE
[Bug] Right alignment of certain post titles

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1273]
See [thread](https://www.reddit.com/r/redditsync/comments/4v9xts/bug_text_alignment_of_the_title_is_to_the_right/).

Here's an example link to the actual post: https://www.reddit.com/r/formula1/comments/4v643w/mbrundlef1_lots_of_talk_about_track_limits_being/

By the looks of it, the handling of the @ sign is off.

**Comment by laurencedawson** [comment]
This has since been fixed.
