### ISSUE TITLE
[Feature request] Save draft of text post submit form

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1275]
[Request thread](https://www.reddit.com/r/redditsync/comments/4ve8r2/feature_request_confirmation_when_exiting_text/).

Perhaps a dialog box like the one that appears when you exit an unfinished comment?

**Comment by laurencedawson** [comment]
Merging:

https://github.com/laurencedawson/reddit-sync-development/issues/804
