### ISSUE TITLE
[Enhancement] Provide toggle to disable "copy to clipboard" behavior when discarding comment

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1285]
See [thread](https://www.reddit.com/r/redditsync/comments/4vitvi/bug_when_i_discard_a_comment_i_was_going_to_write/).

**Comment by twig** [comment]
Alternative:

- when the user cancels, create a notification with the text they entered
- provide two actions for the notification: copy text and discard

This way there is no magic erasure of a the global clipboard without user interaction/permission.

**Comment by laurencedawson** [comment]
This has since been replaced with a drafts manager.
