### ISSUE TITLE
[Bug] Code tags not parsed correctly

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1288]
See [thread](https://www.reddit.com/r/redditsync/comments/4vebf1/code_tags_not_being_parsed_correctly/).

**Comment by machinator2** [comment]
[Another thread](https://www.reddit.com/r/redditsync/comments/4vms2z/codetags_dont_work/).

**Comment by laurencedawson** [comment]
Fixed for v12.
