### ISSUE TITLE
[Feature request] Option to not mark posts (or subset of posts) as read

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1291]
See [thread](https://www.reddit.com/r/redditsync/comments/4vlsw6/request_option_to_not_save_nsfw_post_history/). Users could limit posts not marked read to those that are NSFW, in certain subreddits, etc.

This may be related to #786, in which case I expect you won't implement this, but worth clarifying.

**Comment by laurencedawson** [comment]
I've since added an option to not mark posts as viewed.
