### ISSUE TITLE
[Feature request] Ability to see "other discussions" for link posts

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1294]
[See request thread](https://www.reddit.com/r/redditsync/comments/4vl7j7/feature_request_profile_sharing_and_other/). On web Reddit, any link that has been posted multiple times (e.g., crossposted to other subreddits) will produce an "other discussions" tab that aggregates all posts on reddit where that link is shared.

Here is an example of such a link: https://www.reddit.com/r/Android/duplicates/4vixn8/manual_exposure_control_is_coming_back_to_googles/

**Comment by laurencedawson** [comment]
This has since been added. Cheers.
