### ISSUE TITLE
[Bug] Links to reddit posts with sorting in the URLs open in Custom Tabs

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1295]
[Thread](https://www.reddit.com/r/redditsync/comments/4vk71j/links_to_reddit_posts_with_sorting_in_the_links/).

Example links: 
[Normal, no sorting specified](https://www.reddit.com/r/AskReddit/comments/t0ynr/throwaway_time_whats_your_secret_that_could/)
[Sorting by top](https://www.reddit.com/r/AskReddit/comments/t0ynr/throwaway_time_whats_your_secret_that_could/?sort=top)
[Sorting by new](https://www.reddit.com/r/AskReddit/comments/t0ynr/throwaway_time_whats_your_secret_that_could/?sort=new)

Would be cool if Sync could read the sort type in the URL and automatically apply that sort to the destination thread.

**Comment by machinator2** [comment]
[Similar issue with search queries](https://www.reddit.com/r/redditsync/comments/4x0ol4/why_this_links_opens_up_in_custom_tabs/).

**Comment by laurencedawson** [comment]
This has since been fixed.
