### ISSUE TITLE
[Bug] Sync doesn't detect when user is added to a sub's mod team

### ISSUE THREAD

**Issue by Avinch** [laurencedawson/reddit-sync-development#1296]
I was recently added as a moderator to a subreddit but Sync did not detect that I was added as one, therefore not allowing me to use mod tools for that sub. The only way that I could force Sync to detect it was by logging out and logging back in. It would be great for Sync to detect when a user has been added to a mod team w/o forcing them to relog.

Device/App details if needed:
Dev version v11.6.2
Moto X Pure (2015) running stock 6.0 Marshmallow

**Comment by laurencedawson** [comment]
I've since added an option to manually refresh your moderated subs.
