### ISSUE TITLE
Drop down arrow in nav drawer is invisible

### ISSUE THREAD

**Issue by stevefye** [laurencedawson/reddit-sync-development#1302]
If i tap on the location where the arrow should be, the menu expands as expected.  Tried uninstalling, clearing cache, etc.  

Here's what it looks like for me:. http://i.imgur.com/RMhQ3pW.png

I'm using the following:
Note 3 SM-N900A AT&T w/root 4.4.2, 3.4.0-722276

**Comment by laurencedawson** [comment]
This has since been fixed.
