### ISSUE TITLE
[Bug] Some letters with diacritics not displayed properly in post titles

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1305]
[See thread](https://www.reddit.com/r/redditsync/comments/4vusii/bug_weird_extra_characters_in_titles/).

Direct link to offending post: https://www.reddit.com/r/formula1/comments/4vrp4n/_/

**Comment by laurencedawson** [comment]
Looks like sync is handling these correctly. There's some random unicode in the actual title.
