### ISSUE TITLE
[Bug] Sync can't open links from external applications

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1310]
[See thread](https://www.reddit.com/r/redditsync/comments/4vz7rz/bug_sync_cant_open_reddit_links_from_external/).

[Logcat](https://gist.github.com/anonymous/7981d990474e139c798b7b63681ace14)

[Video showing steps to reproduce](https://www.youtube.com/watch?v=EoghmjILh5s)

**Comment by laurencedawson** [comment]
I think this has since been fixed. Cheers.
