### ISSUE TITLE
[Feature request] Option to share link with reddit post title

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1311]
[See thread](https://www.reddit.com/r/redditsync/comments/4w0j4j/request_share_with_post_title/)

**Comment by heylouiz** [comment]
I was not sure if I should post on sync subreddit or create another issue here, I think updating this one is best to keep the repository clean.

This was working before for me and now it doesn't. I could share links with title and the app always prompted if I wanna send the title.
Now it doesn't ask me anymore and the title is never sent, even on gmail as mentioned in other threads.

I think this is a problem with my phone (Galaxy S7 Edge with stock samsung rom), my friends that use sync with Motorola G5 Plus and Nexus 5X are not having this problem.

Device Info
    Device Model - S7 Edge SM-G935F
    Android Version - 7.0 (Samsung stock)
    sync version - Sync for reddit Free v16 (beta 2) (using pro via reddit user)

Thanks for the app!

**Comment by laurencedawson** [comment]
This has since been added.
