### ISSUE TITLE
[Enhancement] Access subscribed-to subreddit without losing position in current activity

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1312]
[See request thread](https://www.reddit.com/r/redditsync/comments/4w1607/request_add_an_option_to_open_a_subreddit_from/).

The idea, I think, is to be able to "casual browse" a subreddit you are subscribed to without having to use the current "go to subreddit" option in the hamburger menu. For example, if you are browsing the front page but temporarily want to view /r/android (which you are subscribed to), you could press and hold "Android" in the subreddits part of the hamburger menu and open a new activity containing /r/Android without losing your place on the front page.

**Comment by laurencedawson** [comment]
This has since been added!
