### ISSUE TITLE
[Bug] Another invalid MIME type image

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1319]
https://www.reddit.com/r/gifs/comments/4wg41g/hotel_shower_in_rio/d66vqw9

**Comment by machinator2** [comment]
One more: https://www.reddit.com/r/globaloffensive/comments/4wu0y3/_/

**Comment by machinator2** [comment]
Another one, but this one's a streamable video: https://streamable.com/bh37

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers again for collating these!
