### ISSUE TITLE
[Feature request] Add subreddits dynamically to suggestions in "view subreddit" feature

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1327]
[Thread](https://www.reddit.com/r/redditsync/comments/4wk7kb/request_add_subreddits_to_suggestions_dynamically/).

Essentially, the request is that any subreddit that is viewed via casual subreddit browsing is added to the dropdown of suggestions that appear in future searches.

**Comment by laurencedawson** [comment]
This has since been added.
