### ISSUE TITLE
[Bug] Gray auto toolbar color + night mode = hard to see links

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1329]
[Thread](https://www.reddit.com/r/redditsync/comments/4wnpcn/links_become_very_hard_to_read_in_night_mode_when/)

Steps to reproduce:
1. Set theme to dark (night) and turn on auto toolbar color (night).
2. Go to https://www.reddit.com/r/KIC8462852

Links in sidebar are hard to read.

**Comment by laurencedawson** [comment]
This has since been fixed.
