### ISSUE TITLE
[Bug] Random NSFW button not working

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1331]
[See thread](https://www.reddit.com/r/redditsync/comments/4woi1h/bug_random_nsfw_broken_desktop_link_used_instead/)

[In another thread](https://www.reddit.com/r/redditsync/comments/4woi1h/bug_random_nsfw_broken_desktop_link_used_instead/), someone suggested that the desktop link hijacking random NSFW is the one asking users to confirm they are 18+ years of age.

**Comment by laurencedawson** [comment]
This has since been fixed.
