### ISSUE TITLE
[Enhancement] "Could not load more posts" snackbar impedes visibility

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1332]
Affects profiles, subreddits, and single-comment threads.

[Request thread 1](https://www.reddit.com/r/redditsync/comments/4wopkr/is_it_possible_to_autorefresh_once_you_get_to_the/)

[Request thread 2](https://www.reddit.com/r/redditsync/comments/4wp7jw/request_timeout_on_or_ability_to_dismiss_could/)

**Comment by muffinz** [comment]
Just found out you can swipe the snackbar to hide it.

**Comment by laurencedawson** [comment]
I've since added the ability to swipe and dismiss this in any Activity.
