### ISSUE TITLE
[Feature Request] Temporarily NSFW thumbnails when viewing random NSFW subreddit

### ISSUE THREAD

**Issue by Kargii** [laurencedawson/reddit-sync-development#1336]
It would be great if we could temporarily allow NSFW thumbnails when clicking for random NSFW subreddit.

**Comment by machinator2** [comment]
Similar request: allow all NSFW subreddits to show thumbnails while disallowing NSFW thumbnails in non-NSFW subreddits.

Request thread: https://www.reddit.com/r/redditsync/comments/537k4n/can_we_have_the_option_to_show_thumbnails_in/

Supported in Reddit is fun and Relay for reddit, I believe.

**Comment by laurencedawson** [comment]
In the next beta I've added an option to only hide NSFW previews on frontpage and all
