### ISSUE TITLE
Add "search within thread"  option

### ISSUE THREAD

**Issue by clhs1** [laurencedawson/reddit-sync-development#1339]
similar to CTRL+F

**Comment by machinator2** [comment]
Already available. Enable "navigation bar" in comment settings.

**Comment by clhs1** [comment]
Thanks.  I couldn't find it.  Thought it had been removed.

**Comment by machinator2** [comment]
No problem. Do you think you can close this issue, then?

**Comment by clhs1** [comment]
Sure
