### ISSUE TITLE
[Enhancement] When loading an image that's unable to decode bitmap, automatically try refreshing once

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1340]
Some images open with the error `could not decode bitmap (try refreshing)` for the first time (the preview usually loads, though). Refreshing always clears the error. Automatically refreshing itself once may reduce the need to close and reopen the image.

**Comment by laurencedawson** [comment]
I actually did some work on the last release. If an image preview now fails to decode, the deepzoom ignores the preview and continues to load the image!
