### ISSUE TITLE
[Feature request] In-app support for my.mixtape.moe videos

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1347]
Request threads: [1](https://www.reddit.com/r/redditsync/comments/4xochb/support_for_mymixtapemoe_mp4_videos_like_these/), [2](https://www.reddit.com/r/redditsync/comments/4xp6wx/can_mymixtapemoe_be_supported_in_the_inbuilt/)

Seems to be the successor to Streamable, which is popular on sports subs such as /r/soccer.

Example link: https://my.mixtape.moe/dhkvbr.mp4 ([link to /r/soccer thread](https://www.reddit.com/r/soccer/comments/4xorml/mane_scores_vs_arsenal_to_make_it_41/))

Not sure if this helps, but link to API: https://spit.mixtape.moe/api

Main page: https://mixtape.moe/

**Comment by laurencedawson** [comment]
Added support in V12. Cheers.
