### ISSUE TITLE
[Feaure Request] Make the left drawer less fiddly to drag open. Enable swipes across the whole screen to open this drawer.

### ISSUE THREAD

**Issue by robdavis95** [laurencedawson/reddit-sync-development#1351]
In the default Twitter app for example, any swipe across the screen brings up the left drawer. You don't need to swipe from the very left pixels to open this, wheras in Reddit Sync currently you do.

This makes this drawer very fiddly to open for those with bumper phone cases for example and would be a huge quality-of-life improvement. According to /u/GinDaHood [he] believe's this is an artifact of the standard Android navigation drawer library used in 5.0+ apps.

**Comment by muffinz** [comment]
iirc the material design support library doesn't support this. for ex. the Play Store and Inbox have the exact same fiddly gesture

**Comment by robdavis95** [comment]
I believe it's probably because the other apps have different functions for the background content. Eg, archiving/dismissing emails in inbox and scrolling through content in the play store. 

Sucks it's not officially supported though. Thanks for the info.

**Comment by laurencedawson** [comment]
I think I'm going to close this for now as it's not officially supported and the hacks I've tried mess up with the RecyclerView swipe gestures.

**Comment by robdavis95** [comment]
No worries, thanks for the hard work Lawrence! :)
