### ISSUE TITLE
[Bug] When using splitscreen on the latest Android N Developer preview, the previous page is visible behind the current page

### ISSUE THREAD

**Issue by robdavis95** [laurencedawson/reddit-sync-development#1352]
Image attached showing issue. Apologies if android N is not currently supported. 

**How to replicate**
- Visited /r/android via the subreddit search box whilst having YouTube open. 
- Front page posts visible behind the posts in /r/android
- When scrolling up and down the front page remains stationary, and the current subreddit scrolls.

Nexus 6P
Latest Android N Developer Preview
Sync for Reddit pro v11.6.3

![image](https://cloud.githubusercontent.com/assets/15858131/17680623/048283ee-6339-11e6-8379-48fcef168dcb.png)

**Comment by laurencedawson** [comment]
Does this happen every time?

**Comment by robdavis95** [comment]
I've found it happens intermittently and can't work out what's causing it.

Someone over at Reddit found it happened too and stopped when restarting the app. 

Will update if I work it out.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
