### ISSUE TITLE
Repeating "null" notifications

### ISSUE THREAD

**Issue by karanrajpal14** [laurencedawson/reddit-sync-development#1363]
I have a couple of unread messages that I haven't replied to yet. Whenever my hourly sync takes place, Sync throws me a random notification with a "null" and the content from one of my old unread messages. This particular message was sent to me about 2 months ago and I have quite a few newer ones. I have no idea how to reproduce it and it doesn't happen as often as I'd expect it to. 

I'm currently running CM13, Android 6.0.1 on my Moto X 2014. I'd be happy to provide any other information if necessary.

![screenshot_20160817-220248](https://cloud.githubusercontent.com/assets/3253145/17829400/f1c279b8-66ca-11e6-8b6f-e7ee213c7573.png)

**Comment by laurencedawson** [comment]
This has been fixed for the next release.
