### ISSUE TITLE
[Request] Highlight the phrase/letters that are being searched within thread

### ISSUE THREAD

**Issue by DW1045** [laurencedawson/reddit-sync-development#1364]
Right now Sync directs users to the comment, but doesn't actually highlight what the user searched for.

Maybe highlight the text using the accent colour?

It's convenient when searching for words in long comments if the searched phrase/word/letter is highlighted!

**Comment by Ayesuku** [comment]
Hoping for the implementation of this improvement as well!

**Comment by laurencedawson** [comment]
This has since been added.
