### ISSUE TITLE
[Feature request] View OP text when posting top-level comment

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1373]
When writing a comment that is a top-level response to a self post, it would be nice if one could see the original self post while in the text editor. This would preferably be included as a toggleable option within the editor (defaulted to off) so that long self posts don't overwhelm the user / comment editor.

Request thread: https://www.reddit.com/r/redditsync/comments/4y7v36/request_view_op_text_when_posting_top_level/

**Comment by laurencedawson** [comment]
This has since been added.
