### ISSUE TITLE
[Enhancement] Dim background when selecting FAB options

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1379]
Also close FAB when tapping anywhere else?

Request thread: https://www.reddit.com/r/redditsync/comments/4ynhaj/the_fab_behaviour_feels_very_wrong_it_should_sim/

**Comment by muffinz** [comment]
It doesn't necessarily have to dim the background like shown in **[speed dial](https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions)**

**Comment by laurencedawson** [comment]
I'm going to close this as it's not supported out of the box in the design library or required in the guidelines.
