### ISSUE TITLE
[Bug] Direct sharing of deviantart images does not work (invalid MIME)

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1382]
Link to image: http://pockyoo.deviantart.com/art/Hanzo-Shoots-Logs-629460896

Link to post: https://www.reddit.com/r/redditsync/comments/4yrecn/cant_share_this_picture_directly_theres_an/

Steps to reproduce:
1) Select post context menu
2) Hit "Share"
3) Select "image" and "invalid video MIME" pops up.

**Comment by laurencedawson** [comment]
Added for the next release.
