### ISSUE TITLE
[Bug] Ampersand's not showing up properly since 11.6.6

### ISSUE THREAD

**Issue by RobinFlikkema** [laurencedawson/reddit-sync-development#1383]
Since version 11.6.6 (which made changes to title parsing) ampersand's (and other special characters?) aren't showing up correctly in post titles

**Threads**:
- http://www.reddit.com/r/redditsync/comments/4yvboh/_/
- http://www.reddit.com/r/redditsync/comments/4yq8sr/_/
- http://www.reddit.com/r/redditsync/comments/4z4i0u/_/

**Examples**:
- "<" and ">": [Here](http://www.reddit.com/r/gamedev/comments/4ywgsa/_/) and [here](http://www.reddit.com/r/pebble/comments/4ypt8u/_/) and [here](http://www.reddit.com/r/ftlgame/comments/4ypxc6/_/)
- "&": [Here](http://www.reddit.com/r/atlasreactor/comments/4v8ffh/_/) and [here](http://www.reddit.com/r/streetwear/comments/4yvms9/_/)

**Helpful comments**
[/u/MR-reddit-user](http://www.reddit.com/r/redditsync/comments/4yvboh/_/d6r8vjo):
> The Reddit API returns those unless you set raw_json=1 in the request. That might be the issue

**Comment by 13steinj** [comment]
Reddit escapes those chars (and others I believe) for legacy clients. I'm curious to know "what" changed in how reddit serves titles, because if reddit started serving differently without notice that's cause for concern and probably a bug in and of itself.

**Comment by muffinz** [comment]
Fixed in v12b1
