### ISSUE TITLE
[Feature Request] Option to display viewed user / subreddit autocomplete

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1384]
[Request thread](https://www.reddit.com/r/redditsync/comments/4yy3ho/request_remember_entered_subreddits/)

ex. open navigation drawer, tap on `User`, search for `ljdawson`. The next time you tap on `User`, autocomplete will now suggest `ljdawson`.

**Comment by laurencedawson** [comment]
Recent users viewed are now suggested.
