### ISSUE TITLE
[BUG] Trailing space before a dash is removed, screws up links.

### ISSUE THREAD

**Issue by Coffee-Viking** [laurencedawson/reddit-sync-development#1389]
Using a dash like in between words, such as "www.google.com - look yourself" displays as "www.google.com-", with the dash becoming part of the url and as such not possible to open.

In regular sentences it's just a cosmetic issue, but still annoying.

**Comment by machinator2** [comment]
Can you provide a link to a comment where this occurs?

**Comment by Coffee-Viking** [comment]
Sure thing, here you go:
http://www.reddit.com/r/redditsync/comments/4ymrjy/_/d6tpbm3

Screenshots:
http://m.imgur.com/a/ZfMng

**Comment by laurencedawson** [comment]
Fixed for the next release.
