### ISSUE TITLE
Vimeo video player

### ISSUE THREAD

**Issue by skylineKid712** [laurencedawson/reddit-sync-development#1403]
Would it be possible to have a Vimeo video player like the YouTube one? I've done a little bit of looking around and it seems like it may be possible but I'm not 100% sure. Here's one of the links I found talking about it http://stackoverflow.com/questions/35520783/vimeo-video-play-in-android-native

**Comment by laurencedawson** [comment]
Sorry but this is not currently supported. 

All Vimeo support is opening the link in their app...
