### ISSUE TITLE
Comment options open really slowly after opening links in the comment section

### ISSUE THREAD

**Issue by skylineKid712** [laurencedawson/reddit-sync-development#1404]
When I open a link within the comment section and then go back to the comments the animation when I tap on a comment (where it shows upvote/downvote arrows etc.) is really slow. The only way I can fix it is by going back to the list of posts. I'm running Sync dev v12b1 on a Nexus 6 running the August security update of Android 6.0.1

**Comment by machinator2** [comment]
Can't reproduce this on my Nexus 6P running Nougat. (same version of Sync).

**Comment by laurencedawson** [comment]
I think this has since been fixed.
