### ISSUE TITLE
[Enhancement] Option for character limit for self-post previews in subreddit view

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1406]
Reddit request thread: https://www.reddit.com/r/redditsync/comments/4zy7dx/can_we_get_a_character_limit_in_post_previews/

This would apply to the Full Height and Fixed Height card views.

Previously requested in #605 but that was merged into the material design issue and never implemented.

**Comment by muffinz** [comment]
maybe cut off text after the first 3 lines?

**Comment by laurencedawson** [comment]
Added for the next release.
