### ISSUE TITLE
[Bug] /r/stevenuniverse Snoo avatar not showing up in subreddit header

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1408]
Reddit thread: https://www.reddit.com/r/redditsync/comments/4zxodb/bug_rstevenuniverse_reddit_avatar_is_not_showing/

**Comment by laurencedawson** [comment]
The sub in question doesn't have an icon so it isn't shown!

**Comment by machinator2** [comment]
I'm seeing one when using the official reddit app: https://imgur.com/l5CMjsv
