### ISSUE TITLE
[Bug] gyazo gif does not play properly

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1409]
Initial link: https://i.gyazo.com/32505e96c129f2d7c8e89736e02e1b8c.gif

Link redirects to this: https://embed.gyazo.com/32505e96c129f2d7c8e89736e02e1b8c.gif

Reddit thread: https://www.reddit.com/r/redditsync/comments/4zwqr3/gif_doesnt_play_and_looks_weird/

**Comment by laurencedawson** [comment]
Fixed the GIF not auto playing but the GIF is missing the background and that's why it looks funky.
