### ISSUE TITLE
[Bug] In advanced view customization, selecting full width cards does not affect preview

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1412]
**Description**
In advanced view customization, selecting full width cards does not change how the preview looks.

**Scenario (steps to reproduce)**
1. Open settings
2. Tap on advanced view customization
3. Turn on full width cards

**Result(s)**
Card preview is not full width.

**Device Info**
HTC One M9
Android 6.0.1, CM13
v12 beta 3 dev

**Comment by laurencedawson** [comment]
Fixed for the next beta.
