### ISSUE TITLE
[Feature Request] Ability to "Hide Read" from Settings.  I don't want to have to click it every single time.

### ISSUE THREAD

**Issue by jobs127** [laurencedawson/reddit-sync-development#1420]

**Comment by laurencedawson** [comment]
From the settings?

**Comment by jobs127** [comment]
Correct.  Most of the time, I am not interested in seeing "read" posts again.  The only way to avoid this is to click the ... menu, and click "Hide read".  Of course this has to be done every time - which means constantly whenever I enter a new sub, boot the app, or refresh.  

Instead, implement this.

From the Setting / Posts menu, implement an option that says something like, "Hide read posts by default".  When selected, already read posts would be hidden by default.  Additionally, when selected, change the ... menu to say, "Show read".  

This inverts the default behavior in a very logical way that would be useful to many users.  

As the app is now, there is essentially no "archive feature" like Gmail has.  This creates that kind of behavior - where a user only views archived material if interested; as opposed to needing to archive all reddit material constantly (as they must now).

**Comment by laurencedawson** [comment]
If you go to your reddit settings in the browser and enable:

[] don't show me submissions after I've upvoted them (except my own)
[] don't show me submissions after I've downvoted them (except my own)

This will automatically hide the post if you've voted on it.

By default reddit doesn't provide a way to only request unread posts and as a result I cannot support this.

**Comment by jobs127** [comment]
Why can't you just automatically run the "hide read" algorithm when populating the post lists?

**Comment by DW1045** [comment]
On a related note, my issue #1365 

If the votes immediate marks the posts as read, then it would be easier to just go to the overflow menu and hide it right away!

Instead of having to refresh (reloads everything, so this consumes data), voting would mark a post as read/grey it out so that we're able to "hide read" in Sync without having to refresh the post list!
