### ISSUE TITLE
[Bug] GIF does not loop

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1427]
Link to offending post: https://www.reddit.com/r/globaloffensive/comments/507vox/_/

Link to redditsync thread: https://www.reddit.com/r/redditsync/comments/50apa7/the_gif_doesnt_loop_it_just_stops_when_it_gets_to/

**Comment by laurencedawson** [comment]
Seems like images from that host just don't loop no matter what...
