### ISSUE TITLE
[Bug] Clicking on a YouTube channel when using in-app player causes an error

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1429]
Not sure anything can be done on your end, but at the very least this will document the bug for public viewing.

Request thread: https://www.reddit.com/r/redditsync/comments/50einy/bug_clicking_on_a_youtube_channel_causes_an_error/

Example link: http://www.youtube.com/c/cutinhalf

**Comment by laurencedawson** [comment]
Added as a rule for the next release. Cheers.
