### ISSUE TITLE
Any text disappears when it's between </> arrows (reopen of #1174)

### ISSUE THREAD

**Issue by 13steinj** [laurencedawson/reddit-sync-development#1433]
This is a reopen of #1174, as it was falsely closed as fixed.

Original text:

> Any and all text between a < and a > doesn't display. Sony Xperia Z, android 4.3. It's been a bit of an annoyance since day one however I kept forgetting to report it.
> 
> My apologies if there's already an open issue on this, github's search found nothing for me and I didn't want to flip through 13 pages on mobile.

However after closing, it was still not functional. Text displayed, but only the first word. This was demonstrated in [this comment](https://github.com/laurencedawson/reddit-sync-development/issues/1174#issuecomment-241472284).

Now, version 12, the bug is back at it's original state. Unfortunately, github doesn't allow reopening of issues closed by repo members, so I'm reopening this way.

**Comment by machinator2** [comment]
Can confirm on my Nexus 6P (7.0) running the latest beta (12.1). Here's another comment where I only see the first word within the angle brackets on Sync:

https://www.reddit.com/r/nfl/comments/50z1nv/_/d78298m?context=1000

**Comment by drislands** [comment]
I'm seeing a variation on this at this comment:

https://www.reddit.com/r/programmerhumor/comments/6iq65m/_/dj8rs1l

I haven't seen the text on a PC so I don't know what the exact original text is supposed to be, but there's quite a difference between what's shown while scrolling through comments versus what I see when I go to reply.

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by 13steinj** [comment]
@laurencedawson this has *not* been resolved in the most recent release. Still, only a single word is shown. In case I don't get a response to this comment, I will wait one more release in case you meant that one, before reopening yet again.
