### ISSUE TITLE
Disable Inbox Replies

### ISSUE THREAD

**Issue by bmcclure937** [laurencedawson/reddit-sync-development#1435]
When submitting a post to reddit using sync, there is the option to enable or disable inbox replies. If I submit a post with inbox replies enabled and it becomes popular the replies become overwhelming... there is currently no way to disable inbox replies.

Please add the functionality to visit your post and **disable inbox replies** for that post.

Thank You

**Comment by laurencedawson** [comment]
Added for the next release!
