### ISSUE TITLE
[Bug] Reddit URLs with trailing question marks are not handled in app

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1443]
Link to redditsync thread: https://www.reddit.com/r/redditsync/comments/50z7by/bug_the_link_in_this_post_opens_in_the_browser/

Direct link to URL in question: https://np.reddit.com/r/The_Donald/comments/50wesj/announcement_due_to_the_overwhelming_excitement/?

**Comment by laurencedawson** [comment]
Fixed for the next release.
