### ISSUE TITLE
[Feature request] Subreddit folders

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1444]
Ability to put subreddits into distinct categories to make for shorter subreddit list in navigation menu as well as better subreddit organization. Note that this is not the same as multireddits because the user's goal is to still find just one subreddit to browse, as opposed to a combination of subreddits.

**Comment by laurencedawson** [comment]
With v14 I've merged subs + multis which I think is the right way to go intead of folders.
