### ISSUE TITLE
[Enhancement] Rename "Sent" to "Private messages" in messaging menu

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1445]
The dropdown menu in the messaging center gives you the option to see only private messages, both sent and received, under "Sent". However, this is misleading to the user, as it gives the appearance of only showing sent PMs and not those received as well. Requesting that this filter be renamed to something that more accurately describes its contents, such as "Private messages".

Example of confused user: https://www.reddit.com/r/redditsync/comments/5122ue/can_we_get_an_inbox_filter_of_just_messages/

**Comment by laurencedawson** [comment]
Closing as I've since added a Messages section.
