### ISSUE TITLE
[Cosmetic] Update blockquote styling

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1454]

**Comment by laurencedawson** [comment]
Any info on this?

**Comment by muffinz** [comment]
[Here's an example comment](https://www.reddit.com/r/redditsync/comments/5293a9/this_gif_makes_the_slider_jump_around_weirdly/d7ij2l0)

it looks okay in the light theme but it's really hard to see when you're in night mode

Try making the bar 1dp or 2dp thick with a little bit of padding on the right side, as well as a different kind of blue. Maybe blue 500 #2196F3?

**Comment by laurencedawson** [comment]
This has since been implemented.
