### ISSUE TITLE
[Feature Request] Kill connection if you leave the loading screen

### ISSUE THREAD

**Issue by ytsni** [laurencedawson/reddit-sync-development#1456]
There has been quite a fair few times where I will open up an image, whether it be a jpg, gif, gfy and I've noticed that the size is too large and try to backout to the subreddit. 

However even if you backout the image will still continue to download in the background (confirmed with a connection speed monitor).

Unfortunately I've got a pretty small data cap so I try to avoid these sort of images if I can.
So ultimately my suggestion would be to change the behavior so that it kills the connection immediately or the possibility to add the size to the link so that you have an idea before you open it.

https://www.reddit.com/r/redditsync/comments/51i7ga/suggestion_kill_connection_if_you_leave_the/

**Comment by laurencedawson** [comment]
I've added a manual "cancel" button to the image viewer for the next release. Cheers.
