### ISSUE TITLE
The *Theme* option in the overflow is not shown for subs you're not subscribed to

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1462]
If you browse a "casual" subreddit, or get to a sub you are not subscribed to via /r/all or some search, the overflow menu doesn't show the _Theme_ option.

[Discussion on /r/redditsync](https://www.reddit.com/r/redditsync/comments/52kuwt/for_some_reason_i_cant_change_the_theme_when_im/)

**Comment by laurencedawson** [comment]
This was intentional, cheers.

**Comment by muffinz** [comment]
@laurencedawson he means light mode / dark mode, unless that is also intentional?

**Comment by laurencedawson** [comment]
Yup, also intentional!
