### ISSUE TITLE
[Bug] Non-stickied mod-distinguished comments do not display green highlighting

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1471]
Example distinguished comment that is not stickied: https://www.reddit.com/r/nfl/comments/52wg1m/im_doug_farrar_bleacher_reports_nfl_lead_scout_ama/d7o149j

Compare to this distinguished comment that is stickied: https://www.reddit.com/r/nfl/comments/50z1nv/minnesota_vikings_are_trading_for_eagles_qb_sam/d7800ou

The OP's (mod's) name should be highlighted in green in the first comment as it is in the second comment, but this is currently not the case.

**Comment by laurencedawson** [comment]
Fixed for the next release.
