### ISSUE TITLE
[Bug] Individual posts appear in wrong column on tablet view

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1473]
Steps to reproduce can be found here: https://www.reddit.com/r/redditsync/comments/51svhk/bug_individual_posts_appear_in_wrong_column_on/

Similar issue for smaller cards in landscape mode when using dual pane mode: https://www.reddit.com/r/redditsync/comments/52ueao/bug_smaller_cards_view_links_to_comments_end_up/

**Comment by chaghi** [comment]
The main issue is not that the posts appear in wrong column, but that they are squashed in the middle 1/3rd of the left pane, making them almost impossible to read.

Secreenshot (random post from /r/bestof): https://imgur.com/uhuVVrA

In my case, this happens only in my Nexus 7; I can't reproduce it on my Moto X. So maybe is DPI-dependent?
