### ISSUE TITLE
[Bug] Certain permalink reddit URLs are not handled in-app

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1485]
Link in question: https://www.reddit.com/r/dayz/comments/52lrz3/status_report_13_sept_2016/d7lbn78#d7lbn78

Reddit request thread: https://www.reddit.com/r/redditsync/comments/52oya7/comment_link_on_bottom_of_the_post_opens_in_web/

**Comment by laurencedawson** [comment]
Fixed for the next release.
