### ISSUE TITLE
[Bug] Admin comments incorrectly distinguished as moderator comments

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1486]
Example comment: https://www.reddit.com/r/the_donald/comments/528p0l/_/d7io7dq

Imgur album showing bug in app: http://imgur.com/a/PmYSH

Request thread: https://www.reddit.com/r/redditsync/comments/52ptid/reddit_admin_shows_up_with_m_tag_in_app_but_a_tag/

**Comment by laurencedawson** [comment]
Fixed for the next release.
