### ISSUE TITLE
[Bug] Thumbnail preload settings not respecting data options settings

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1489]
Steps to reproduce:

1) Set the following options under Data Options to "Never": Preload full images, Preload preview images, Preload thumbnails, Preload GIFs
2) Go to subreddit that has not been previously viewed or cached recently, such as /r/catsstandingup (https://www.reddit.com/r/catsstandingup) or /r/foxes (https://www.reddit.com/r/foxes)
3) Thumbnails are still preloading in subreddit view, regardless of whether on wifi or data.

**Comment by salimnanji** [comment]
Can reproduce this issue.

**Comment by laurencedawson** [comment]
This isn't an issue actually. 

So when you scroll down in Sync it now loads the next few thumbnails that are offscreen, so if you slowly scroll down they should be loaded by the time you scroll down.

If you disable preload thumbnails, go to an unvisited sub and then quickly scroll down you'll be able to see the thumbnails were not preloaded.

**Comment by salimnanji** [comment]
I see what you mean now. I thought that meant loading thumbnails period.

Just for clarification then, what do the other settings mean?
Preload full images - Will automatically download full resolution images in subreddit?
Preload preview images - Whats the difference between thumnails and preview images?

**Comment by salimnanji** [comment]
I see what you mean now. I thought that meant loading thumbnails period.

Just for clarification then, I have a few other questions:
1. Preload full images - Will automatically download full resolution images in subreddit?
2. Preload preview images - Whats the difference between thumnails and preview images?
3. Just for my curiousty, how much data is a thumbnail?

**Comment by laurencedawson** [comment]
1. Yup
2. Preview images are what shown in a card
3. It's all relative but reddit thumbnails are usually 100x100 so not too big
