### ISSUE TITLE
[Feature request] Move multireddits above subreddits in left sidebar (hamburger menu)

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1492]
Request thread: https://www.reddit.com/r/redditsync/comments/532pmu/when_will_we_be_able_to_show_multireddits_before/

This was marked as resolved in #359 but I can't figure out how to do this on Sync on 12.2 beta 1. I also don't see this in any changelogs.

**Comment by kiwiapple87** [comment]
I can't find this as well.

**Comment by chaghi** [comment]
This request keeps popping-up in the sub. For example in the last month or so:

* https://www.reddit.com/r/redditsync/comments/5oj7u5/multireddit_fast_access/
* https://www.reddit.com/r/redditsync/comments/5my485/is_there_a_way_to_put_multireddits_on_top_of/
* https://www.reddit.com/r/redditsync/comments/5o2ixl/request_an_option_to_put_the_multireddits_list/
* https://www.reddit.com/r/redditsync/comments/5o516y/request_10_important_features_sync_doesnt_have/ (point 5)
* https://www.reddit.com/r/redditsync/comments/5m3wc3/how_to_put_multireddits_at_top_of_list/
* https://www.reddit.com/r/redditsync/comments/5lq05v/how_come_multireddits_are_sorted_at_the_end_of/
* https://www.reddit.com/r/redditsync/comments/5kd470/option_to_move_multireddits_to_the_top/
* https://www.reddit.com/r/redditsync/comments/5jt4dz/request_ability_to_mix_subreddits_and_multireddits/
* https://www.reddit.com/r/redditsync/comments/5jq50n/requedt_add_option_to_change_left_barmenu_be/

**Comment by laurencedawson** [comment]
Subreddits and multireddits have been merged with a new look in the drawer for the next release.
