### ISSUE TITLE
[Bug] Comments scrollbar not appearing for certain devices

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1494]
Steps to reproduce:

1) Enable scrollbar in comment settings
2) Go to any comment section, and there's no comment scrollbar.

Device: Nexus 6P, 7.0.
App versions: Sync Pro Beta 12.2 beta 1, Sync Dev 12.2 beta 1, Sync (free with ads) 12.1 stable

Things I've tried: enabling and disabling comment navigation bar, enabling and disabling scrollbar in post settings, using both light and dark themes. The comment scrollbar does not appear in any of these situations.

See this thread: https://www.reddit.com/r/redditsync/comments/532qde/no_scrollbar_in_comments/

Someone with a Moto G 2014 running 6.0 is also experiencing the same thing.

**Comment by laurencedawson** [comment]
This has since been fixed.
