### ISSUE TITLE
[Bug] Sharing link with Dropbox does not work

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1496]
See thread with steps to reproduce: https://www.reddit.com/r/redditsync/comments/530qsz/bug_share_link_with_dropbox/

Note that the body of the post says the app version is 11.2.5 but OP later clarified their version was 12.1.

**Comment by laurencedawson** [comment]
> EDIT: This issue has resolved itself due to android upgrade. Everything is working now as normal. Weird.

Closing.
