### ISSUE TITLE
[Bug] Internal browser takes ages to load anything

### ISSUE THREAD

**Issue by noifen** [laurencedawson/reddit-sync-development#1497]
Both my Nexus 5X and Pixel C take ages to load anything when using the internal browser. Chrome tabs are fine but don't offer incognito mode.

Android version: 7.0
Sync version: 12.1

**Comment by laurencedawson** [comment]
This was most likely due to the webview. In future check in Google play if theres any updates available for the webview and if that fails try rebooting your device.
