### ISSUE TITLE
[Bug] Loading more comments does not work for users not logged in

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1498]
**Scenario (steps to reproduce)**
1. Log out
2. Open a post
3. Find a comment where you can tap on _View more_ and tap on it

**Result(s)**
_Error loading more comments_ appears, and _View more_ becomes stuck at _Loading_

**Device Info**
HTC One M9
Android 6.0.1, CM13
v12.2 (beta 2) dev

_referenced on [r/redditsync](https://www.reddit.com/r/redditsync/comments/536oe6/bug_hitting_load_more_comments_while_logged_out/)_

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.
