### ISSUE TITLE
Stickied moderator comments have an [S] tag after their username/flair.

### ISSUE THREAD

**Issue by Rolcol** [laurencedawson/reddit-sync-development#1500]
Perhaps the [**S**,M] means "stickied" in this context, in which case this bug report is invalid.

On Reddit's desktop site, the [S] tag is used to identify the submitter/original poster of a thread.  When mod comments are stickied in the comment thread, they're also identified with the [S] tag, even though they're not necessarily the submitter.  

Example of AutoModerator's comment to another user's bug report:
![screenshot_2016-09-19-18-10-47](https://cloud.githubusercontent.com/assets/22308514/18653541/d2e4a734-7e97-11e6-8577-01984c75ebbe.png)

**Comment by brett1337** [comment]
Could use google's pin there maybe?:

<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:width="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path android:fillColor="#000" android:pathData="M16,12V4H17V2H7V4H8V12L6,14V16H11.2V22H12.8V16H18V14L16,12Z" />
</vector>

**Comment by laurencedawson** [comment]
This has been fixed for the next release.
