### ISSUE TITLE
[Feature Request]  "Copy Link" button similar to the "Share" button

### ISSUE THREAD

**Issue by salimnanji** [laurencedawson/reddit-sync-development#1505]
A "Copy Link" button similar to the "Share" button that allows you to copy the link or comments to clipboard. Right now in order to do the same thing, I have to click "Share" -> "Link" -> Find "Copy to Clipboard" in list -> Click it.

Screen:
![screenshot_2016_09_20_14_33_46](https://cloud.githubusercontent.com/assets/12036621/18683696/49b6c6ec-7f3f-11e6-8333-1ddf4a5c0214.png)

Share:
Screen:
![screenshot_2016_09_20_14_33_46](https://cloud.githubusercontent.com/assets/12036621/18683696/49b6c6ec-7f3f-11e6-8333-1ddf4a5c0214.png)

**Comment by Chronogenesis** [comment]
This would be absolutely wonderful.

**Comment by laurencedawson** [comment]
This has since been added.
