### ISSUE TITLE
[Bug] Tumblr GIF starts glitchy, does not loop

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1506]
Link to GIF: https://67.media.tumblr.com/794a67029d9dad9c0912a81675d6c029/tumblr_nxvnn70KtM1tpl11ho1_500.gif

Link to post: https://www.reddit.com/r/unexpected/comments/538ey4/_/

Link to redditsync request thread: https://www.reddit.com/r/redditsync/comments/53ajgj/bug_gif_starts_glitchy_plays_fine_once_but_doesnt/

**Comment by laurencedawson** [comment]
Fixed for the next release.
