### ISSUE TITLE
[Request/Cosmetic] Extend the black line across but leave spaces on both left and ride sides so it looks cleaner! 

### ISSUE THREAD

**Issue by DW1045** [laurencedawson/reddit-sync-development#1515]

**Comment by DW1045** [comment]
How the text divider looks like right now: http://i.imgur.com/82t0ENd.png

My suggestion is to extend it to the right so the divider is not heavily favouring the left side of the app. 

Also it would looks less messy and easier to distinguish that it is a divider because it would actually divide the text instead of only looking like a short placeholder on the left!

**Comment by muffinz** [comment]
Also lighten the divider to 12% opacity

**Comment by laurencedawson** [comment]
This has since been added.
