### ISSUE TITLE
Text on self post taking too much space on card view. 

### ISSUE THREAD

**Issue by CristianJaviM** [laurencedawson/reddit-sync-development#1520]
Sometimes the poster doesn't format its text post quite correct and you end up seeing a wall of text. Other times, people put a spoiler tag on the title, but the spoilers end up being at the first few lines of the post. 

Is there a way to hide this self text previews?

**Comment by muffinz** [comment]
Check out #1406 and #1357

**Comment by CristianJaviM** [comment]
DEV told me on reddit to leave an issue here, never thought there was going to be another one. Sorry.

**Comment by muffinz** [comment]
don't say sorry! helps show that it's frequently requested

**Comment by laurencedawson** [comment]
This has been added to the most recent betas. Cheers!
