### ISSUE TITLE
[Cosmetic] Use single progress indicator instead of two while loading an image

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1532]
[**Progress indicators**](https://material.google.com/components/progress-activity.html#progress-activity-types-of-indicators)

Keep the circular progress bar but turn it into a determinate progress bar.

**Comment by muffinz** [comment]
kinda fixed

**Comment by laurencedawson** [comment]
Kinda?

**Comment by laurencedawson** [comment]
Kinda, I'd say fully!
