### ISSUE TITLE
[Cosmetic] Improve navigation drawer collapsible list styling

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1534]
_[referenced in r/redditsync](https://www.reddit.com/r/redditsync/comments/54q9c4/this_dark_menu_with_the_light_theme_is_it_a_bug/)_

Change from [this](https://i.redditmedia.com/fNjSCnL2EtAb8zjslZdqNMu_NmfTuZGJRE0gJ8rg5ng.png?w=432&s=1872b4d1239233ddd93883f0aba8d4bc) to [this](http://imgur.com/a/eZ5qP) (use dividers and indent)

**Comment by laurencedawson** [comment]
Added for the next release.
