### ISSUE TITLE
Switch to dark text in the app bar when a bright theme is used.

### ISSUE THREAD

**Issue by Seift** [laurencedawson/reddit-sync-development#1539]
The text is barely legible on bright colors as of now.

**Comment by muffinz** [comment]
**[Color references](https://material.google.com/style/color.html#color-color-palette)**

**Red**
50 => 300 = dark text
400 => 900 = light text

**Pink, Purple, Deep Purple, and Indigo**
50 => 200 = dark text
300 => 900 = light text

**Blue**
50 => 400 = dark text
500 => 900 = light text

**Light Blue**
50 => 500 = dark text
600 => 900 = light text

**Cyan**
50 => 600 = dark text
700 => 900 = light text

**Teal**
50 => 400 = dark text
500 => 900 = light text

**Green**
50 => 500 = dark text
600 => 900 = light text

**Light Green**
50 => 600 = dark text
700 => 900 = light text

**Teal**
50 => 400 = dark text
500 => 900 = light text

**Lime**
50 => 800 = dark text
900 = light text

**Yellow and Amber**
50 => 900 = dark text

**Orange**
50 => 700 = dark text
800 => 900 = light text

**Deep Orange**
50 => 400 = dark text
500 => 900 = light text

**Brown**
50 => 200 = dark text
500 => 900 = light text

**Grey**
50 => 500 = dark text
600 => 900 = light text

**Blue Grey**
50 => 300 = dark text
400 => 900 = light text

**Comment by laurencedawson** [comment]
This has been added for the next release.
