### ISSUE TITLE
[Cosmetic] Remove default content assets in cards

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1544]
[**reddit-sync-development** / assets](https://github.com/laurencedawson/reddit-sync-development/tree/master/assets)

Does not serve any purpose in my opinion and takes up space where the url would normally be

**Comment by laurencedawson** [comment]
These are only ever shown when the reddit API returns them.

You can change your prefs here:

https://www.reddit.com/prefs/
