### ISSUE TITLE
Opening a post re-expands the subreddit list

### ISSUE THREAD

**Issue by c00ller** [laurencedawson/reddit-sync-development#1546]
**Description**
I posted this [on reddit](https://www.reddit.com/r/redditsync/comments/55env0/bug_opening_any_post_reexpands_the_subreddit_list/) but figured it would be more properly documented here.
If I collapse the subreddits list in the hamburger menu sidebar, then tap on any post, the subreddits list will be re-expanded. Since there is still no option to show multireddits above subreddits, this adds to the already frustrating experience when trying to browse by multireddits. 

**Scenario (steps to reproduce)**
1. Collapse the list of subreddits in the hamburger bar by tapping on "Subreddits"
2. Tap on any post
3. Slide out the hamburger bar

**Result(s)**
The subreddits list will appear re-expanded and the scroll state will be back to the top.

**Device Info**
- Device Model - Nexus 5X
- Android Version - Android N (7.0)
- sync version - Sync Pro v12.3

**Screenshot**
[Gfycat](https://gfycat.com/SpryDeepHawaiianmonkseal)

**Comment by laurencedawson** [comment]
In the next version subreddits and multis have been merged.
