### ISSUE TITLE
[Cosmetic] Custom Colors for subreddits

### ISSUE THREAD

**Issue by curlyhairedprince** [laurencedawson/reddit-sync-development#1547]
I love the customization of the app and I've got it set up in this wonderful minimalist style. I've noticed that some (popular) subreddits have color themes, which really helps differentiate the different subreddits and give them each their flavor and style. The option to add colors to none popular subreddits and have the option to change some subreddits color to something different would be awesome! 

P.S You guys are doing an amazing job with this app. Keep up the amazing work.

**Comment by laurencedawson** [comment]
This has since been added to the betas. Cheers.
