### ISSUE TITLE
[Request] Banners for different post modes (locked, archived, competition, sports, live)

### ISSUE THREAD

**Issue by DW1045** [laurencedawson/reddit-sync-development#1548]
In light of the new no participation links banner, can there be a similar indication for archived, locked, sports (when it's implemented), live (when it's implemented), and competition mode posts too?

For reference, the banners would be:

- For **archived** posts: "This is an archived post. You will not be able to vote or comment."
- For **competition** posts: "This post is in competition mode, you will not be able to sort the comments" *(I personally think this is better as it informs the user what they can't or cannot do)* or "This post is in competition mode, the comments will be sorted in random".
- For **locked** post: "This is a locked post. You can vote but cannot comment/comments will be deleted".
- For **sports/live** mode (when it's implemented): "This post is in live mode. The post will refresh with every update."

Or if Sync plans to add a refresh interval then it could be something along the lines of:
"This post is in live mode. The post is set to refresh every __ seconds/minutes."

**Comment by laurencedawson** [comment]
Added for the next beta. Cheers.
