### ISSUE TITLE
Possible fix for delayed IAP

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1549]
[**In-app Billing API**](https://developer.android.com/google/play/billing/api.html)

**Purchasing Items**

> When your application starts or user logs in, it's good practice to check with Google Play to determine what items are owned by the user. To query the user's in-app purchases, send a **_`getPurchases`_** request. If the request is successful, Google Play returns a Bundle containing a list of product IDs of the purchased items, a list of the individual purchase details, and a list of the signatures for the purchases.

**Comment by laurencedawson** [comment]
Unfortunately the issue still isn't resolved:

https://github.com/googlesamples/android-play-billing/issues/2#issuecomment-238316085
