### ISSUE TITLE
Sync displays all colored text as spoilers

### ISSUE THREAD

**Issue by SenorPilkington** [laurencedawson/reddit-sync-development#1566]
Posts that use tags to add color to text all show up as spoilers on Sync.

[Browser](http://i.imgur.com/rW1UpNd.png)

[Sync](http://i.imgur.com/GiXLu03.png)

[Post example images were taken from](https://reddit.com/r/bravefrontier/comments/55q84r/bectas_exp_and_sp_farming_guide/)

Currently on Android 7.0, Sync v12.3.1

**Comment by laurencedawson** [comment]
Sadly the links are colored using spoiler tags and custom CSS.

All Sync sees is a new spoiler...
