### ISSUE TITLE
[Feature Request] A simple filtering input field on top of the subscription list in the sidenav to allow us to filter the subs

### ISSUE THREAD

**Issue by edinchez** [laurencedawson/reddit-sync-development#1569]
Having to scroll up and down to find a particular subreddit in a long list of 300+ subs is very annoying. I think a simple filtering input at the top would be perfect and easy to implement.

I did a quick mockup of how this could look:

![sidenav suggestion mockup](https://i.imgur.com/OHkaSu4.png)

**Comment by laurencedawson** [comment]
Closedb

**Comment by laurencedawson** [comment]
*closed...
