### ISSUE TITLE
[BUG] Comment Navigation Bar doesn't respect the subreddit theme when in dual panes mode

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1577]
**Description**

When Sync is configured to use subreddit themes, and you enter a comment thread in dual panes mode, the Comment Navigation Bar in the comments (right) pane uses the accent color of the base theme, and not that of the subreddit's. The FAB in the posts (left) panel uses the correct color though.

**Scenario** (steps to reproduce)

1. Enable *Use subreddit theme* (Settings > Theme customization)
1. Configure the *Smaller cards* view to use *Dual panes (landscape)* (Settings > Advanced view customization)
1. Enable *Display navigation bar* (Settings > Comments)
1. Switch to *Smaller cards view*
1. Held the device in landscape mode. Dual panes is activated.
1. Browse a subreddit with a custom theme (for example, /r/redditsync)
1. Select a post

**Result**

The comment navigation bar in the right pane uses the accent color of the base theme, and not the one of the subreddit theme.

Following the example (browsing /r/redditsync), the comment navigation bar should be blue (like the FAB in the left pane) and not green (as configured in the base theme).

**Device Info**

* Device: Motorola Moto X 2013
* Android Version: 5.1
* Sync Pro 12.5 (beta 2)

**Screenshot** 

http://imgur.com/aKtUqEI

![Screenshot](http://i.imgur.com/aKtUqEI.png)

**Comment by laurencedawson** [comment]
Aha so I figured this one out.

In your base configured theme I bet you've got it set so that the accent color is static. This will stop it from updating the comments navigation bar color too.
