### ISSUE TITLE
[Bug] User flair selection does not work

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1579]
Steps to reproduce:

1. Go to a sub like /r/NBA, /r/NFL, /r/tmobile, or /r/television.
2. Hit "select" flair in right sidebar.
3. Select any of the flair options. In /r/tmobile, try "[flair-mag] Truly Unlimited" for example.
4. If you go back to the select flair screen, you will see that the flair selection did not work, as the radio button for the flair you chose is still not filled in. This can be verified on desktop reddit.

This occurs regardless of whether you have "show CSS flair" toggled on or off. Same with "show user flair in comments" toggled on or off.

Nexus 6P, Nougat 7.0 stable, Sync for reddit Pro 12.5 beta 2, though this has been an issue ever since the option to select flair in-app was introduced.

**Comment by laurencedawson** [comment]
Got it!

Fixed for the next release.
