### ISSUE TITLE
[Feature Request] Being able to copy link and link to comments from the 3-dot menu.

### ISSUE THREAD

**Issue by zaneyk** [laurencedawson/reddit-sync-development#1584]
Being able to copy link and link to comments from the 3-dot menu, would be very handy, maybe merge it with the 'copy title' option here is an example of what it could look like
![sync copy](https://cloud.githubusercontent.com/assets/23311127/20119518/1f937c02-a609-11e6-8509-04b136b2398a.png)

**Comment by laurencedawson** [comment]
This has since been added.
