### ISSUE TITLE
[Bug] Comments are cached even with the option turned off

### ISSUE THREAD

**Issue by tenkuu** [laurencedawson/reddit-sync-development#1589]
The new feature in 12.4 which saves your position in the thread conflicts with the "Cache comments" option as threads are now saved regardless of the option.

Is there any chance you can tie the position-saving feature to the "Cache comments" option? Thank you.

**Comment by laurencedawson** [comment]
Saving position saves the entire state and thus has to load previously cached content.

I don't really understand what you're asking for, if you don't want to save state you can disable that option.

**Comment by tenkuu** [comment]
Oops, I didn't see that option. Sorry for taking up your time.

-------- Original message --------

**Comment by laurencedawson** [comment]
No worries, cheers!
