### ISSUE TITLE
[Feature Request] 12 hour clock support in night mode config

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1590]

**Comment by laurencedawson** [comment]
https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif

**Comment by muffinz** [comment]
I'm almost completely sure there is a way to detect 12 or 24 hour system time

Why not

**Comment by laurencedawson** [comment]
I think it's clearer being a 24 hour clock.
