### ISSUE TITLE
[Feature Request] Inline image albums in the Swipe View

### ISSUE THREAD

**Issue by LittleGhostyBooBoo** [laurencedawson/reddit-sync-development#1592]
When browsing in swipe mode, a user should be able to swipe side to side to switch between posts, and up and down to view different pictures in the current post if that post is an album.

Currently: While in swipe mode and when a user encounters a post which is an image album, the user must tap through to a different image viewer to switch between the different pictures in the album.  This can be a negative experience for the user when the album is a single image album.

**Comment by laurencedawson** [comment]
Unfortunately there's no easy way to tell if the image is part of a gallery without request the album.

I think for now I'm going to close this issue as I don't think albums should play inline.
