### ISSUE TITLE
[Feature Request] Cache controls in settings

### ISSUE THREAD

**Issue by muffinz** [laurencedawson/reddit-sync-development#1593]
- ability to clear cache in app
- ability to also set maximum cache size

**Comment by laurencedawson** [comment]
>ability to clear cache in app

Agreed.

>ability to also set maximum cache size

This kinda goes against the "sync" in sync for reddit.

**Comment by muffinz** [comment]
good point but I think it will sorta compliment the image cache duration setting

**Comment by laurencedawson** [comment]
Added a option under images. Cheers.
