### ISSUE TITLE
[Feature request] Keep in sync Advanced view customization (in settings) and the selected View mode

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1599]
This is something that confuses users quite frequently: they are in some view mode (for instance, Fixed height cards), go to *Advanced view customization* in settings, customize another view (for instance, Small cards), and then complain that the changes they made "won't stick", because they expect to be switched automatically to the view mode they've just customized.

I think the mode selected in *Advanced view customization* (in Settings) and the current view mode should be kept in sync:
* If I use *Advanced view customization* to customize another view, when I leave settings the view mode should automatically change to the one I've just customized;
* Likewise, if I'm using view mode X, when I enter *Advanced view customization* mode X should be automatically selected in the top bar spinner;

**Comment by laurencedawson** [comment]
>Likewise, if I'm using view mode X, when I enter Advanced view customization mode X should be automatically selected in the top bar spinner;

Already the case.
