### ISSUE TITLE
[Request] Make the background color of swipe mode match the theme in all cases

### ISSUE THREAD

**Issue by eric7763** [laurencedawson/reddit-sync-development#1604]
e.g. If I open swipe mode by choosing overflow > open > sub in swipe mode while I was using the light theme then the background color of swipe would be white. Currently swipe mode only has a white background when I open swipe mode by choosing change view in the overflow and I'm using the light theme.

**Comment by laurencedawson** [comment]
The dedicated swipe mode was designed to have a dark background so I'll close this issue without it being resolved.
