### ISSUE TITLE
[Request] Don't show approved posts in unmoderated

### ISSUE THREAD

**Issue by sebj** [laurencedawson/reddit-sync-development#1605]
Currently, if you a remove a post in the unmoderated section it disappears. However, if you approve a post, it remains in the list.

"unmoderated" should only contain posts that have not been approved or removed, so this does not make much sense.

**Comment by laurencedawson** [comment]
I think this is more of a reddit issue. I just display what the JSON is returning.

**Comment by sebj** [comment]
Correct me if I'm wrong, but aren't you fetching JSON to get a list of unmoderated posts, then manually removing a list item/list row when the user taps Remove? Would it not be possible to do the same if the user taps Approve? Sorry if I'm overly naive.
