### ISSUE TITLE
Remove "Mark as Read" for Posts Already Marked as Read

### ISSUE THREAD

**Issue by tenkuu** [laurencedawson/reddit-sync-development#1606]
When a post has been marked as read, I think the "mark as read" option in the overflow menu should switch to "mark as unread" or disappear.

**Comment by machinator2** [comment]
Duplicate of #1291

**Comment by tenkuu** [comment]
Not really. My issue is that the "mark as read" option is still there (and does nothing) for posts that are already marked as read.

**Comment by laurencedawson** [comment]
There's no API endpoint to mark as unread.

**Comment by laurencedawson** [comment]
Added for the next release.
