### ISSUE TITLE
[Request] Automatic image resizing

### ISSUE THREAD

**Issue by mariojuniorjp** [laurencedawson/reddit-sync-development#1609]
I made a suggestion a few weeks ago, but I forgot to report it here.

Link for video: https://drive.google.com/file/d/0B8Ue522-UyvlbERac2NMR2FPTHc/view

Sync does not automatically resize the image. You need a manual zoom, but this not work very well for large images and still decentralized.

If you look on relay, a image is automatically resized for the screen. Just wants double tapping to essentially go from viewing the whole image to fitting horizontally or vertically. It's just a minor annoyance when someone posts a really tall comic strip that seems like a simple fix.

**Comment by laurencedawson** [comment]
Added for the next release.

**Comment by mariojuniorjp** [comment]
1000x Thank You, Laurence! 👍
