### ISSUE TITLE
[Annoyance] Align sub menu items with the parent in the slide out nav menu

### ISSUE THREAD

**Issue by roman-ku** [laurencedawson/reddit-sync-development#1618]
So instead of what sync is doing now:

<img src="https://cloud.githubusercontent.com/assets/10580420/21511197/399b2676-cc52-11e6-866a-e98fcfd8ee8c.png" width="400">

Do something like the dash for reddit app:

<img src="https://cloud.githubusercontent.com/assets/10580420/21511198/42145732-cc52-11e6-823e-d46f90e95051.png" width="400">

Reason: This will make the nav bar menu more elegant and easier on the eyes, as well as make it easier to scan the menu and find what you're looking for.

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by roman-ku** [comment]
This is awesome. Thanks man.
