### ISSUE TITLE
[Feature Request] Maintain consistent user interface for saving items

### ISSUE THREAD

**Issue by gumaste** [laurencedawson/reddit-sync-development#1619]
In the card view, the bottom menu options are [ up  down  save  menu]; however the bottom menu options for a comment in a thread is [up   down  user   reply  parent  menu]. This requires the the user to take an extra navigation into the menu to save a comment and is not as usable as if the action options were consistent between the two interfaces.  Perhaps switching the user profile action with the save action could remedy this?

**Comment by laurencedawson** [comment]
I would have to disagree on this one.

Posts and comments are different so I think a different interface is fine. Also saving comments is far less common than posts.
