### ISSUE TITLE
[Request] Add support for background syncing

### ISSUE THREAD

**Issue by rbclark** [laurencedawson/reddit-sync-development#1621]
The new sync manager option to sync comments is great, the only issue I have with it is as of right now it takes a pretty long time and stops the rest of the app from being used while it is doing it. Would it be possible to get this feature moved to a progress bar in the navigation shade instead?

![Example](https://qph.ec.quoracdn.net/main-qimg-8fb67efeae7d8520198e9024c751002b-c?convert_to_webp=true)

**Comment by laurencedawson** [comment]
If you have Tasker you can schedule background syncs from this. Cheers.
