### ISSUE TITLE
The "No more posts were loaded" message covers the action buttons in Small Cards view 

### ISSUE THREAD

**Issue by ianwitherow** [laurencedawson/reddit-sync-development#1623]
When using the Small Cards view, if the "No more posts were loaded" message is shown, you can't access the buttons (up/down vote, save, etc) for that last post. 

Not a huge deal, but it's come up a couple times so I thought I'd submit an issue. 

Screenshot: http://i.imgur.com/mPmpTuy.png

**Comment by machinator2** [comment]
You can swipe that snackbar away.

**Comment by ianwitherow** [comment]
That changes things. Thanks!
