### ISSUE TITLE
Copy-pasting/selecting individual words to work with google translate. 

### ISSUE THREAD

**Issue by Sinaaaa** [laurencedawson/reddit-sync-development#1624]
Hi!

Would it be possible to develop copy pasting/selection of words within comments? Some of the big words in /science are giving me a hard time & I have to type them manually because only entire comments can be copied as of now. Within android any word that can be selected can be translated/defined immediately.
Like so: http://imgur.com/a/jbELb

(I love the app, this is pretty much my only issue with it)

**Comment by machinator2** [comment]
This is already possible. Select the comment of interest, hit the inline three-dot menu that appears, and hit "select text". You can then select text as you would on any other Android app.

**Comment by laurencedawson** [comment]
Due to having links in the text the approach outlined by machinator2 is the only approach possible.
