### ISSUE TITLE
Uploading a high quality photo fails every time

### ISSUE THREAD

**Issue by tuhoojabotti** [laurencedawson/reddit-sync-development#1632]
I was trying to upload a 20 megapixel photo, but it keeps failing every time. It is not too big because I was able to upload it directly via imgur mobile site, it's around 10 megabytes. I can attach it here as an example. 

Using Google Nexus 6P,  Stock Android 7.1.1, Sync 12.9.2

**Comment by tuhoojabotti** [comment]
Here is the file that I tried to upload (but it's not the first file that fails): https://drive.google.com/file/d/0B8qoPAyTKprwc1o4bnJ5Y2pIZk0/view?usp=drivesdk

**Comment by tuhoojabotti** [comment]
![screenshot_20170108-115131](https://cloud.githubusercontent.com/assets/633524/21749157/de093dac-d598-11e6-9f1e-e9acdedbb954.png)

**Comment by laurencedawson** [comment]
This has been fixed for the next beta.

**Comment by tuhoojabotti** [comment]
@laurencedawson Cheers! Do you mind explaining the issue? As a software developer myself I find these kind of things interesting. :smile:
