### ISSUE TITLE
[ISSUE\REQUEST] Ability to customize the colour of certain texts throughout the app.

### ISSUE THREAD

**Issue by PoonSlayer1000** [laurencedawson/reddit-sync-development#1635]
Preferably most text colour should be changable. There are too many places with text that is all the same colour. It not only makes it harder than necessary to browse but it is just unpleasant.
Just the implementation of colour customization for subreddit, author and usernames throughout, would drastically improve the appeal and usability of this app.

**Comment by laurencedawson** [comment]
This has since been added.
