### ISSUE TITLE
[Request] Make some changes to the theme engine!

### ISSUE THREAD

**Issue by JokeyChan** [laurencedawson/reddit-sync-development#1642]
For Example:

Changing the primary color changes the color of the toolbar and not of links, FABs etc.

Changing the Accent Color changes the color of flairs, FABs, links etc. And Not of a toolbar.

When I am using the night theme and choose the primary color of my choice, some colors just do not pop up as much as I want them to because of the darker background, of course. 
For example: darker shades of blue gray, green etc.

I want color of the toolbar and flairs, links etc to look different sometimes.

If we get this option we would have more control over theme customizations IMO.

**Comment by laurencedawson** [comment]
I've since heavily revised the theme engine.
