### ISSUE TITLE
Snackbar blocks bottom post controls

### ISSUE THREAD

**Issue by flipflop97** [laurencedawson/reddit-sync-development#1645]
As can be seen in the screenshot, the snackbar that appears at the bottom of a page blocks the comment and vote controls. If there really are no more posts then pressing the retry button does nothing and you can't access the controls of the bottom post at all from this view. By adding a little padding at the bottom this can probably be fixed easily.

![screenshot_20170114-160611](https://cloud.githubusercontent.com/assets/13943260/21955854/a0a78376-da73-11e6-93a9-97a74ffb473e.png)

**Comment by machinator2** [comment]
The snackbar can be swiped away (swipe from right to left).
