### ISSUE TITLE
Make "continue thread" load more than one comment

### ISSUE THREAD

**Issue by touzainanboku** [laurencedawson/reddit-sync-development#1646]
If you go to [this](https://www.reddit.com/r/counting/comments/5el4be/1523k_counting_thread_d/) thread and tap "continue this thread" below 1,523,009, on desktop it shows comments until 1,523,018. 

However, Sync only shows 1,523,010. So you have to keep tapping "continue thread" to see more comments. I've seen other apps behave like the desktop site, so I don't think there are any limitations for this in the API. It'd be great if it loaded more comments just like on desktop. 

And sorry if this was a duplicate, I did search to see if there's already an issue for this, but didn't find any.

**Comment by machinator2** [comment]
Boost for reddit is an example of an app that handles it better.
