### ISSUE TITLE
[Feature request] [Enhancement] Make it so the title in the Post shortcut opens the link directly

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1651]
When tapping the title of the post on the *Post shortcut* minicard in the right sidebar, and the post is not a selftext post, Sync should open the link.

Currently it reopens the thread, going to the top. If I want to check the link **without losing my place in the comments**, I need to tap the overflow of the preview, then *Open in browser*. It would be better if Sync handled that when tapping the title.

Better yet, it should honor the *Link handling* configuration, and open the link using the image viewer or Chrome Custom Tab or whatever, depending on the target.

And it would be *totally awesome* if it opened the link in a new activity, so I could go switch back and forth between the link and the comments with the app switcher...

[Discussion in the sub](https://www.reddit.com/r/redditsync/comments/5ovvxo/sync_for_reddit_v1210_is_now_going_live_on_google/dcn4b32/)

**Comment by laurencedawson** [comment]
Not entirely sure why I disabled the thumbnail for this now...

Anyways I've re-enabled the thumbnail so you can now click on the link and open the content from the sidebar!
