### ISSUE TITLE
[Feature request] [Enhancement] More options for flair visualization

### ISSUE THREAD

**Issue by leopard-tights** [laurencedawson/reddit-sync-development#1652]
As of right now CSS flairs show the image and when tapped, the hover/alt/etc. text.

Tech subs that use the text to display info about the user, like which phones they have, would be hidden. And subs that use the hover text for jokes along the image will never be seen, because hovering is easy and it even happens by random chance when using a mouse, but you'll never tap a flair image on your phone just of out of curiosity.

Ideally:

1. Show images and text at the same time, without tapping.
2. Like it is now.
3. Only the text like it was before.
4. No flairs.

Right now we have options 2 and 4. Subs without support for the css/images behave like option 3.

Edit: an example for the first case could be /r/pcmr, and for the second one /r/heroesofthestorm. Another suggestion is to have them be per sub basis; perhaps a global setting and a list of exceptions. /r/pcmr is again the example here, global "mode 1", would be better for a frequent visitor, but it would look very messy for a more casual reader, and the current "mode 2" would be better.

**Comment by laurencedawson** [comment]
Added for the next release.
