### ISSUE TITLE
[BUG] Blue bars covering text

### ISSUE THREAD

**Issue by ninjra** [laurencedawson/reddit-sync-development#1669]
When viewing posts, some text is covered over with blue bars, see screenshot at: http://i.imgur.com/C5JgoYB.png

The bar can be clicked to display the text, but no setting I can find disables the blue highlighting.
This issue does not exist when viewing it through either the mobile browser, nor a desktop browser.
I do not believe this is a problem with subreddit formatting, nor are these texts intended to be spoilers.

Scenario:
View posts like: https://www.reddit.com/r/ffbraveexvius/comments/5rack4/_/

Results:
http://i.imgur.com/C5JgoYB.png

Device Info:

Models: ZTE Axon 7, Nexus 6P
Android Version: 
       Axon: Marshmallow(6.0.1), Nougat:LineageOS 14.1
       6P: Nougat 7.0.1 stock
Sync version: Various, issue has been around through numerous versions. Currently on Free:12.10

Screenshot: http://i.imgur.com/C5JgoYB.png

**Comment by laurencedawson** [comment]
>nor are these texts intended to be spoilers.

But they use standard spoiler formatting...

**Comment by ninjra** [comment]
If that is the case it is not intended and also does not show up that way
on the web version.
