### ISSUE TITLE
[Feature Request] Watch Button 

### ISSUE THREAD

**Issue by UnknownDeemo** [laurencedawson/reddit-sync-development#1677]
If possible, could you make it so it would a watch button at the top right corner of a post when you enter it. Thank You

**Comment by UnknownDeemo** [comment]
It would show*

**Comment by UnknownDeemo** [comment]
To clarify it would show in post view

**Comment by laurencedawson** [comment]
I think going to post overflow and then watch is sufficient. It's not used enough to warrant being in the toolbar.
