### ISSUE TITLE
[Bug] Texts posts without text body shown as link posts

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1680]
Text posts that don't have a text body, and are just a title, are being shown as link posts (with the "chain" post type icon).

Example: https://www.reddit.com/r/androidthemes/comments/5sxhw1/_/

Sync Pro v12.11.1 beta.

[Relevant thread](https://www.reddit.com/r/redditsync/comments/5t1adu/some_text_posts_marked_as_link_posts/).

**Comment by laurencedawson** [comment]
Fixed for the next release.
