### ISSUE TITLE
Header is shown only if the subreddit name is correctly typed (is case sensitive!)

### ISSUE THREAD

**Issue by denysvitali** [laurencedawson/reddit-sync-development#1682]
Steps to reproduce:  
1. Visit [this link](https://www.reddit.com/r/redditsync/comments/5tkjc0/can_we_get_the_option_to_change_the_image_of_this/ddoxl8c/)  via the Reddit Sync app (this makes everything easier)
2. Click "/r/multicopter" (lowercase)  
3. Click "/r/Multicopter" ("m" is uppercase)

What happens:  
1. When the "m" is lowercase the header is missing
![multicopter](http://i.imgur.com/xY5FYNl.png)  
2. When the "M" is uppercase the header is available  
![Multicopter](http://i.imgur.com/wI2qrQu.png)  
  
The same happens when a subreddit is requested via "Menu" => "View subreddit" and the subreddit name is typed in lowercase / different case than the original's subreddit name  
  
Edit: Apparently it's a Reddit Sync problem, both endpoints [/r/Multicopter/about.json](https://www.reddit.com/r/Multicopter/about.json) and [/r/multicopter/about.json](https://www.reddit.com/r/multicopter/about.json) give the same result (and a `banner_img` as you would expect)

**Comment by laurencedawson** [comment]
Fixed for the next release. This was actually down to sync treating that sub like a multireddit and skipping the header check!

**Comment by denysvitali** [comment]
Thank you fro fixing :)
