### ISSUE TITLE
Long press feedback/improved animation in edit subs lage

### ISSUE THREAD

**Issue by justinwzig** [laurencedawson/reddit-sync-development#1691]
With the most recent update I've been spending a lot more time in the edit subs page and the long press feedback is kinda weird and jarring. There's no vibration and the menu doesn't open until you release your finger, unlike some similar actions. Maybe it's just me, but this doesn't seem entirely natural or user friendly.

**Comment by laurencedawson** [comment]
There isn't a long press action in manage, it will just trigger the on click action.
