### ISSUE TITLE
[Feature request] Swipe up/down to dismiss image/album

### ISSUE THREAD

**Issue by supahgreg** [laurencedawson/reddit-sync-development#1695]
Something I've gotten used to with Talon (for Twitter) is swiping up/down to dismiss an image/album I have open.  Having used that app for a while the action feels pretty natural, so I wanted to ask that it be considered for this app.  Thanks!

**Comment by touzainanboku** [comment]
Settings -> Images -> Swipe to close

**Comment by supahgreg** [comment]
Well that's embarrassing :)  Thanks for pointing it out!
