### ISSUE TITLE
[Bug] Default subreddit view mode set to swipe mode opens only in left column when in tablet landscape mode

### ISSUE THREAD

**Issue by brett1337** [laurencedawson/reddit-sync-development#1697]
Bug: set a multi or sub reddit to custom view swipe mode. Be in landscape tablet mode in list view on a regular sub like r/redditsync. Go to the multi. The swipe mode loads in the left column instead of the full screen. 

Sync v14 beta3.

Duplicated on 2 separate devices (phone _ Note 2, tablet _ amazon fire 8)

**Comment by laurencedawson** [comment]
This has since been resolved.
