### ISSUE TITLE
i.redd.it gifs are saved with the incorrect extension

### ISSUE THREAD

**Issue by touzainanboku** [laurencedawson/reddit-sync-development#1704]
**Description**

i.redd.it gifs are saved as gif files, even though the saved file is actually supposed to be an mp4. 

**Scenario** (steps to reproduce)

1. Have thumbnails enabled in your [reddit preferences](https://www.reddit.com/prefs/)
2. Open an i.redd.it gif like [this one](https://www.reddit.com/r/gifs/comments/5zbzxt/criminal_situation/)
3. Download the gif

**Result(s)**

The saved file will have a .gif extension, even thought it's supposed to be an mp4 file. Gallery apps won't be able to open the .gif file, but you can open it in a video player if you rename it to .mp4. 

**Device Info**

* Device Model: Sony Xperia Z2
* Android Version: 6.0.1
* sync version: Free v14beta4

**Screenshot** 

[Album](https://imgur.com/a/46be6)

**Comment by laurencedawson** [comment]
This has been fixed for the next beta. Cheers!
