### ISSUE TITLE
Feature request - /r/all departure confirmation. 

### ISSUE THREAD

**Issue by ns-n0wl** [laurencedawson/reddit-sync-development#1705]
Often times while browsing reddit, I will sometimes decide to browse /r/all

When browsing after lots of scrolling, an accidentally back click will return me to my Frontpage. 

That can be really frustrating if you've been scrolling down for several minutes, only to be returned to the top on accident. 

Additionally, there's very little indication that you've gone back from your front page.

**Comment by laurencedawson** [comment]
If you go to Settings > Posts and uncheck "return to your first sub before exiting" I think this should resolve the issue for you.
