### ISSUE TITLE
[Request] Can we have an optional confirmation prompt before opening YouTube links?

### ISSUE THREAD

**Issue by fruitymcdoo** [laurencedawson/reddit-sync-development#1710]
I'll often click links without looking at the source and be taken out of the app and have to wait for YouTube to load.

A simple toggleable warning like "This is a YouTube link, would you like to proceed?" Would be really cool.

Even better would be if you could add domains to this warning list and it'd prompt you for confirmation​ before opening links to any of the listed sites.

Thanks!

**Comment by laurencedawson** [comment]
I think an easier solution is to enable the video content filter if you're in a scenario where you don't wish to open YouTube links.
