### ISSUE TITLE
[REQUEST] Add a search button to the toolbar and increase the area available to jump to the top of the page

### ISSUE THREAD

**Issue by PoonSlayer1000** [laurencedawson/reddit-sync-development#1720]
The ability to search at the press of a button would be great. I use the search function frequently and having to access it from the overflow menu or now with v14, above subscriptions is tedious. A search button just right of the current sub on the toolbar would be perfect. Also a dedicated spot on the toolbar that is easy to press to jump to the top of the page, I know it is present currently but it is very hard to get it right.

**Comment by SuperiorNexus** [comment]
Actually, I think it'd be a better idea to also implement the search function into the Fab instead of "Submit" and "Hide Read"... I would use that a lot!

**Comment by laurencedawson** [comment]
Added to the bottom toolbar in the redesign.
