### ISSUE TITLE
[REQUEST] Option to autoplay GIFS when scrolling past them

### ISSUE THREAD

**Issue by PoonSlayer1000** [laurencedawson/reddit-sync-development#1725]
Also even adding an option to swap out slide to hide with slide to play, similar to most decent porn sites would be cool; As hiding a post seemes entirely unnecessary and adding this would allow people trying to save data, to still quickly play gifs without auto playing all.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/reddit-sync-development/issues/1666
