### ISSUE TITLE
[REQUEST] Option to change the colour of self text seperate to the title of a post

### ISSUE THREAD

**Issue by PoonSlayer1000** [laurencedawson/reddit-sync-development#1740]

**Comment by laurencedawson** [comment]
I'm going to close this issue as I think right now the level of customization is adequate.

**Comment by PoonSlayer1000** [comment]
Hi Laurence, just a bit of feedback;
I believe one of the most important parts of choosing a Reddit client for anyone is the look and feel, something the official client, both on pc and on smart phones, gets terribly wrong. The pc version is horrible to look at and the smartphone version is bland. If you invest your time in polishing the look and feel of this app you will pick up on this. Looking at the majority of posts in Redditsync regarding topics sorrounding the look and feel of the app it's easy to see how important this is to your consumer (including me). I love sync and would easily prefer it over any other client, however a few small additions and changes wouldn't go stray. So far functionality is good, yes maybe it could be made a little more user friendly (As even I, being fairly tech savvy, had a bit of a learning curve when I first started using sync) but for the most part, at this point, functionality is adequate. However, a few small tweaks and additions to the look and feel of this app, I believe, would be time well spent. I'd be happy to make some suggestions in regards to this, as I love what you're doing and appreciate the one man triumph.
Keep up the good work mate

________________________________
