### ISSUE TITLE
[BUG] Random user highlighted as if "Friend" or "OP"

### ISSUE THREAD

**Issue by SuperiorNexus** [laurencedawson/reddit-sync-development#1743]
https://www.reddit.com/r/android/comments/62sq6z

That is the link to the thread where I encountered the bug.

Basically, a random user (u/gadgetroid) would be highlighted as if he was OP (he isn't.)and then in the same thread, he wouldn't be.

This picture is showing actual OP:
https://imgur.com/59rhdut

This picture showing bug in question:
https://imgur.com/ueWTk5T

**Comment by brett1337** [comment]
He is a moderator. His comment below isn't highlighted because mods can choose to distinguish their comments with or without the mod flair. Not a bug.
