### ISSUE TITLE
[Feature Request] Add intent filter for AMP links

### ISSUE THREAD

**Issue by Kyle-Dornblaser** [laurencedawson/reddit-sync-development#1771]
Currently Google AMP links open in the browser instead of Sync. Could this be added so links automatically open in the app?

Example link: https://www.google.com/amp/s/amp.reddit.com/r/redditsync/comments/6c2u4j/sync_for_reddit_v142_is_now_going_live_on_google/

**Comment by laurencedawson** [comment]
Added for the next release.
