### ISSUE TITLE
[Request] Make Random Dice Remember Sort Type

### ISSUE THREAD

**Issue by lo4952** [laurencedawson/reddit-sync-development#1772]
If possible, could you make it so that the dice that randomly pulls a new subreddit on /r/random and /r/randnsfw remember how the previous subreddit was sorted? So for example if I sorted a subreddit by Top > All and then hit Random, the new sub would also be in Top > All.

**Comment by laurencedawson** [comment]
Random respects the default sort type which is the same behaviour elsewhere in-app.
