### ISSUE TITLE
Per-subreddit NSFW filter

### ISSUE THREAD

**Issue by TheGurpa** [laurencedawson/reddit-sync-development#1773]
I have NSFW content always hidden, but I also subscribe to a few subreddits where the NSFW tag is a way to hide spoiler posts. It would be nice to be able to enable NSFW content on specific subreddits, while having it disabled everywhere else.

**Comment by laurencedawson** [comment]
I don't see this being added anytime soon.

The alternative is to make two accounts as they have different setting profiles or to use the content filters which can be easily toggled.
