### ISSUE TITLE
[Bug] Can't upload images in self text

### ISSUE THREAD

**Issue by brett1337** [laurencedawson/reddit-sync-development#1783]
Can't upload images in self text as opposed to in comments working fine.

https://www.reddit.com/r/redditsync/comments/6h9ay9

**Comment by laurencedawson** [comment]
I literally just stopped this and fixed it before seeing your issue.

**Comment by brett1337** [comment]
Haha nice

**Comment by brett1337** [comment]
Fixed in beta 3
