### ISSUE TITLE
[Feature Request] offer to save drafts when closing submit form for self posts

### ISSUE THREAD

**Issue by DouweKoopmans** [laurencedawson/reddit-sync-development#1793]
when closing the submit form for a comment you get asked if you want to save the comment as a draft which is very useful if you are need to save your work before posting it, however when you exit out of the submit form for a self post you do not get this option. this means you are unable to create drafts when writing self posts. Could this option please be added?

it would also be very useful to have a dedicated button to save the current text (and possible title) as a draft.

**Comment by laurencedawson** [comment]
This has since been added.
