### ISSUE TITLE
[Feature request] New designs/themes for cards

### ISSUE THREAD

**Issue by Vakke** [laurencedawson/reddit-sync-development#1794]
Hello! 

Have you thought to create new designs for card view? I'd love to see even more material designin on them and more rounded corners like in the Boost for Reddit. If you're working on it my wondering on buying the app is over immediatly.

**Comment by laurencedawson** [comment]
The cards already have rounded corners. Can you be more specific?

**Comment by Vakke** [comment]
I'm trying to describe the design of the single card layout that for example Boost for Reddit has. In the bottom the upvote, downvote buttons have been rounded and the icons are much fuller in design. Also the gallery view Boost has is super useful and I'd love to have one on Sync.

But for short I'd love to have more design and more customation on the cards view especially. I'm not a native English speaker so I hope I can make myself clear enough :)

**Comment by laurencedawson** [comment]
The corners have since been made more round.
