### ISSUE TITLE
Ability to sort multireddits to the top

### ISSUE THREAD

**Issue by TylerShaw** [laurencedawson/reddit-sync-development#1798]
On the main screen, the drop-down that normal starts with "front page", I'd like the ability to sort multireddits first, in alphabetical order.

**Comment by laurencedawson** [comment]
This already exists. When you're in the edit screen and clicking sort, select multis first.

**Comment by TylerShaw** [comment]
I only have "Sort A-Z", "Sort Z-A", and "Sort by most viewed"

**Comment by TylerShaw** [comment]
https://www.dropbox.com/s/wmxcuziv0eciu9i/Screenshot_20170804-054914.png?dl=0

**Comment by laurencedawson** [comment]
Click any of those and you'll see additional options.

**Comment by TylerShaw** [comment]
...thanks, I swear I clicked on those before. Thanks for the quick response too! Really appreciate the app!
