### ISSUE TITLE
[Feature Request] Default accounts when opening app.

### ISSUE THREAD

**Issue by NotChristianGarcia** [laurencedawson/reddit-sync-development#1800]
It would be useful if you could set an account as default, so that whenever you open the app, that account is the one that opens first. Creating privacy for alt accounts and streamlining use of the app.

**Comment by thecakeisalie25** [comment]
Be honest, you have an nsfw alt and opened it in public didn't you? Haha it's okay I'm just playing, I did the same thing too. This would be good to add though, for this purpose.
