### ISSUE TITLE
Split screen forces single-column layout on tablet (Pixel C)

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1809]
(this keeps popping up in the sub. As I couldn't find it here, I'm copying this very nice [bug report](https://www.reddit.com/r/redditsync/comments/741zw1/bug_split_screen_forces_singlecolumn_layout_on/?ref=share&ref_source=link) by `/u/Nyriarty`)

**Description**

Split screen is forcing a single column layout, whereas at some time in the past it would use two or three columns depending on the available width. I use full-height cards, which works beautifully when multiple columns are shown, but not so much with a single excessively wide column.

Furthermore, when exiting split screen by holding the multitasking button the one column layout sticks until the app is restarted. This doesn't happen when dragging the separator between the two windows.

See the following screenshots:

https://imgur.com/a/MGvGM

**Scenario**

- Open reddit sync
- Hold multitasking button to start split screen
- Observe single column layout is shown (and full-height cards are _huge_)
- Close multitasking by sliding the window seperator all the way to the right.
- Observe multiple columns are shown
- Re-enter multitasking mode
- Hold the multitasking button to exit multitasking
- Observe a single column layout is shown until app is restarted

**Device info**

- Pixel C
- Android 8.0.0
- Sync version 14.4 (final final beta)

Link to original thread: https://www.reddit.com/r/redditsync/comments/741zw1/bug_split_screen_forces_singlecolumn_layout_on/?ref=share&ref_source=link

**Comment by arthurlt** [comment]
Similar issue with my Chromebook

**Comment by laurencedawson** [comment]
Fixed for the next release.
