### ISSUE TITLE
Double notification sound/vibration on Oreo

### ISSUE THREAD

**Issue by carlylemiii** [laurencedawson/reddit-sync-development#1811]
Pixel XL, Android 8.0

Any time a notification comes through, it sounds the alarm twice for a single alert.

https://www.reddit.com/r/redditsync/comments/6wmyox/double_notification_sound/

Much worse for multiple messages.

**Comment by carlylemiii** [comment]
Additionally, since Notification Channels have been implemented, the Notification Sound option found in-app should be removed/hidden for 8.0+ users. It's confusing at best, and I haven't actually tested how they interact, but I shouldn't be able to "set" conflicting values in different ways (i.e., at the notification level and also inside the app).

Same thing with notification LED. There should just be a "Manage notifications" option like there is in Gmail, which takes you to the Android System notification controls.

**Comment by carlylemiii** [comment]
@laurencedawson any chance we can _please_ get this fixed soon? Android P launches in 18 days, and we still have this O bug. :(

**Comment by laurencedawson** [comment]
Fixed and added for the next release.
