### ISSUE TITLE
Sync still connects to Crashlytics even if setting disabled

### ISSUE THREAD

**Issue by carlylemiii** [laurencedawson/reddit-sync-development#1813]
https://www.reddit.com/r/redditsync/comments/6x4t2j/bug_sync_still_tries_to_connect_to_crashlytics/

**Comment by laurencedawson** [comment]
Unable to reproduce this.

Try removing Sync from your recents and open again.

**Comment by carlylemiii** [comment]
Sorry, meant to close this. We discussed it on Reddit and it doesn't do it any longer with your newer builds. Cheers!

**Comment by carlylemiii** [comment]
@laurencedawson this should be reopened.

https://imgur.com/GpfwTLo

**Device information**

    Sync version: 16.1    
    Sync flavor: pro    
    
    View type: Fixed height cards    
    Player type: ExoPlayer    
    Push enabled: true    
    
    Device: taimen    
    Model: Google Pixel 2 XL    
    Android: 8.1.0
