### ISSUE TITLE
[BUG] Crash when trying to open a link with capitalized letters

### ISSUE THREAD

**Issue by metzgore** [laurencedawson/reddit-sync-development#1815]
**Description**

Trying to open the following link results in a crash: Https://Youtu.Be/MGek8sCMfuo?T=9m9s
Found here: https://www.reddit.com/r/rocketbeans/comments/75r4bs

**Scenario (steps to reproduce)**

Tap on link, YouTube video is supposed to start playing

**Result(s)**

Crash

**Device Info**

Pixel C, Android 8.0.0 October patch, 14.4 final final beta (free)

Feedback has been sent to Google play developer console

Bug report: https://www.reddit.com/r/redditsync/comments/75z5f3

**Comment by brett1337** [comment]
Is there a report on r/redditsync? Need to link it here so the bug can be reproduced.

**Comment by metzgore** [comment]
Added a report: https://www.reddit.com/r/redditsync/comments/75z5f3

**Comment by laurencedawson** [comment]
Fixed for the next release.
