### ISSUE TITLE
[Bug] Repeated crashing every 5-10 minutes of use. App unusable. 

### ISSUE THREAD

**Issue by tigerspecial** [laurencedawson/reddit-sync-development#1818]
**Description**
The app crashes within several minutes of use, repeatedly. No apparent pattern to the crashes (not connected to any specific type of content being opened etc).

**Scenario (steps to reproduce)**
Using the app for 5-10 minutes on my phone. Not sure what's causing it. Logs available.

**Result(s)**

**Device Info**
Sync version: 14.3.2    
Sync flavor: free    
Removed ads: false    

Device: bullhead    
Model: LGE Nexus 5X    
Android: 8.0.0

**Screenshot (recommended)**

**Logcat**
I have full logs from two sessions, but they may contain private info so I don't want to link them publicly. Please PM on reddit (I [posted there](https://www.reddit.com/r/redditsync/comments/7952a5/bug_repeated_crashing_every_510_minutes_of_use/) as well) and I will share txt files.

**Comment by laurencedawson** [comment]
This has been fixed in v15.
