### ISSUE TITLE
[Feature request] Either URL rewriting menu links or some form of external undelete support

### ISSUE THREAD

**Issue by OvermindDL1** [laurencedawson/reddit-sync-development#1820]
Specifically I'm curious in any of:

* Included unsure support pulling from ceddit or whatever
* Being able to add new links in the menu below Open thread in browser to let us open the thread after regex-rewriting the URL to ceddit or whatever.

Just would be a lot easier instead of opening the thread link in a browser, editing it, then opening it in another browser that floats but had no editable URL bar.

Optimally it would be awesome to choose a deleted thread, comment, or comment tree and have it be populated from various undelete/ceddit-like sites when they have such information, but saving me multiple steps otherwise would be wonderfully helpful.

**Comment by laurencedawson** [comment]
This is against the reddit TOS and not something I can add. Sorry.

**Comment by OvermindDL1** [comment]
> This is against the reddit TOS and not something I can add. Sorry.

I understand linking to the other sites, but what about a regex replacement of the URL that the user specifies that can then be opened?
