### ISSUE TITLE
Can we have upvote/downvote buttons disabled when a post is archived?

### ISSUE THREAD

**Issue by sjoshua270** [laurencedawson/reddit-sync-development#1823]
This is something that bugs me when I try to upvote something and just end up with a "This post is archived and cannot be voted on" message

**Comment by laurencedawson** [comment]
Added for the next beta.

**Comment by carlylemiii** [comment]
What about disabling the Reply button? Currently you're "able" to reply, and you even get a toast saying "Submitting", but of course it doesn't work, in the end.
