### ISSUE TITLE
Unable to change image download location

### ISSUE THREAD

**Issue by varystargaryen** [laurencedawson/reddit-sync-development#1826]
**Description**
Attempting to alter the image download folder gives an "This folder cannot be used (cannot write)" message.
On Internal Storage FYI
**Scenario**
Go to Settings/Images
Change the download folder
**Results**
This folder cannot be used (cannot write)
**Device Info**
OnePlus 3 Android 7.1.2 - LineageOS 14.1 - Unofficial SultanXDA version
Sync for Reddit Version 14.4 Dev (final final beta)

**Comment by M2ThaL** [comment]
Me too. On Sync Beta 15.1 on Moto G5 Plus.

**Comment by laurencedawson** [comment]
Fixed in todays beta (15.1 beta 4).

**Comment by trasheusclay** [comment]
Hi, love Sync! 

Sorry to resurrect this thread, but I'm on 16.1 and have attempted to move image dl'd folder to sd card. It's giving the same "This folder cannot be used (cannot write)" result. 

Is there a setting that I'm not seeing, to allow this move, or has this bug reappeared? Thanks for any help!
