### ISSUE TITLE
[Feature request] Sync should register itself as a handler for v.reddit direct links

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1828]
Direct v.reddit links [like this one](https://v.redd.it/l6o6r35airzz/DASHPlaylist.mpd) are handled ok in-app, but if someone receives the link in another app (text, email, some IM, etc) Sync doesn't handle it, so it's picked up directly by the default browser.

These should be handled the same as Imgur or Gfycat or any other of those; Sync should register itself as a handler so it could become an option to open those links with the app from outside.

Relevant thread on the sub: https://www.reddit.com/r/redditsync/comments/7f4u7o/v_reddit_links_dont_work/

**Comment by laurencedawson** [comment]
Added for the next release.
