### ISSUE TITLE
Change icon for v.reddit videos

### ISSUE THREAD

**Issue by thecakeisalie25** [laurencedawson/reddit-sync-development#1830]
The videos seem to play more like gifs in the sense of how inline they are. Rather than take me out of the app, they play easily. This makes it hard to determine which content I can watch and which I should skip.

**Comment by OvermindDL1** [comment]
Yeah it would be nice to see which animations will take me out of the app and which will keep me in before I click them.

**Comment by laurencedawson** [comment]
This has been added for the latest beta.
