### ISSUE TITLE
[Feature request] Allow sharing a reddit link from an external app to browse it in-app

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1847]
It would be nice if when sharing a reddit link from another app, Sync offered a "browse" or "open" option. Currently we can share a link with Sync from outside but only for submitting it.

This would be similar to how Twitter for example offers options to "Tweet" and "DM" when you share a link from another app.

Relevant thread on `/r/redditsync`: https://www.reddit.com/r/redditsync/comments/7nogpv/chrome_reddit_page_open_in_sync_app/

**Comment by laurencedawson** [comment]
Added for the next release.
