### ISSUE TITLE
[Feature Request] When navigating back in settings, go back to search results

### ISSUE THREAD

**Issue by carlylemiii** [laurencedawson/reddit-sync-development#1849]
I think it would be nice if when you do a search for results, click one, and then navigate back just once, it brings you back to the list of results. This would be in line with how Gmail works for email searching.

Use cases would be if you maybe didn't click the proper result the first time or if there are multiple related settings you want to change that are under the same search terms, e.g., "font".

https://www.reddit.com/r/redditsync/comments/7olxo2/feature_request_when_navigating_back_in_settings/

**Comment by carlylemiii** [comment]
In a similar fashion, when you're viewing a post and do a search for a keyword, select a matching post and then go back, I'd expect to see my list of results; that was the last thing I was on. Instead, I have to re-type my query.

Any chance of fixing these in an upcoming beta, @ljdawson? :)

**Comment by laurencedawson** [comment]
Added for the next alpha. Cheers!
