### ISSUE TITLE
[Bug] Can't create new categories for saved posts in-app unless at least one already exists

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1855]
[BUG] Can't create new categories for saved posts in-app unless at least one already exists
---

**Description**

If the user doesn't have any categories on their account, the app won't allow to save a post to a new category. Long pressing the save ("star") button will give them a message telling they don't have any categories.

To create a new category from the app the user needs to access the pop-up dialog with the available categories, which currently won't show up if there's no categories to use.

**Scenario** (steps to reproduce)

1. Swith to an account with Reddit Gold, and **no saving categories**.
1. Long-press the save ("star") button.

**Result(s)**

The app says there's no categories to choose from, and won't offer any dialog to create one.

Currently the user is forced to create at least one category using the web (or another app), which is really annoying.

**Device Info**

    Sync version: 16 (beta 2)
    Sync flavor: pro

    View type: Fixed height cards
    Player type: ExoPlayer
    Push enabled: true

    Device: potter_n
    Model: motorola Moto G (5) Plus
    Android: 7.0

**Comment by laurencedawson** [comment]
Fixed for the next release. Racing through these!
