### ISSUE TITLE
[Request] Viewing Wikimedia images 

### ISSUE THREAD

**Issue by wertyy102** [laurencedawson/reddit-sync-development#1860]
Was wondering if it is possible to add ability to view Wikimedia images like Tumblr and Imgur and other services.  Not often are they linked on Reddit, but it's enough that it's a bit jarring when I load my browser to open an image rathe than the extremely rapid, extremely clean image loader for imgur and other services.

**Comment by laurencedawson** [comment]
Wiki links can end an extension such as jpg but actually be a webpage. For this reason all wiki links are excluded from the image viewer.
