### ISSUE TITLE
[feature request] backup/preserve order of subscriptions

### ISSUE THREAD

**Issue by dimm0k** [laurencedawson/reddit-sync-development#1861]
is it possible to have the order of subscriptions saved during the creation of a backup or have some way to export it for safe keeping to be able to import it at a later time or to another device? upon creation of a reddit account there are a bunch of default subscriptions that are added, but since then I've been adding my own subscriptions for easy access and browsing. it's nice that Sync can allow one to re-order these, however more often than not something wreaks havoc on this list and the whole order is lost. There's no doubt in the last few weeks my "preferred" order was lost with no change on my part and now it doesn't even look to be in any specific order.

**Comment by bet** [comment]
Please, I want back the order I'd carefully created. Forcing all my subscribed subreddits into a mechanically sorted order is a loss for me; then splitting up multireddits into the individual subs and shuffling them in is rubbing salt in the wound.

**Comment by laurencedawson** [comment]
This has been discussed in the beta thread and will be fixed for the next release.

**Comment by dimm0k** [comment]
this may be fixed for the next release, but I'd still be more comfortable with an option to back up one's own list, which is sort of why I opened this request...
