### ISSUE TITLE
[BUG] Clearing viewed subreddits doesn't clear them from app shortcuts

### ISSUE THREAD

**Issue by jheiselman** [laurencedawson/reddit-sync-development#1862]
### Description

Using the "Clear viewed subreddits" option in Settings > History doesn't remove subreddits from the app shortcuts list.

### Scenario (steps to reproduce)

1. Visit a subreddit enough to have it show up on the app shortcut menu
2. Launch Sync and go to Settings > History
3. Tap "Clear viewed subreddits"
4. Tap Home
5. View the app shortcuts and notice that the subreddit is still listed

### Result(s)

The subreddit is still listed in the menu.

### Device Info

Device Model: Google Pixel 2
Android Version: 8.1.0
sync version (Version Number + Free/Pro/Dev): 15.1.1, free, ads removed

**Comment by laurencedawson** [comment]
This has been fixed for the next release. Cheers.
