### ISSUE TITLE
[Request] Option to always enable left tray when "Swipe to return" is disabled

### ISSUE THREAD

**Issue by el3gy** [laurencedawson/reddit-sync-development#1865]
The left tray (not sure what else to call it; the one with settings, profile, etc) can be accessed when viewing a subreddit from the subreddit list dropdown on the launch screen (frontpage), but never when navigating further in; if "Swipe to return" is disabled, then swiping from left after navigating from the homepage simply does nothing.

**Comment by chaghi** [comment]
This is more or less a duplicate of #1556.

**Comment by el3gy** [comment]
closed due to duplication then
