### ISSUE TITLE
no difference between fixed height and full height cards

### ISSUE THREAD

**Issue by anonymous-user** [laurencedawson/reddit-sync-development#1869]
I have Reddit Sync version 16 beta 4 and I recently noticed that there seems to be no difference between the fixed height card view and full height card view. In both views the cards all seem to be the same height. I want a view where I can see the full height of the image. This should be the full height cards right?

**Comment by chaghi** [comment]
This has been discussed in the sub several times. You are correct, Full Height Cards is meant to show the full height of the image, but it's also affected by your reddit configuration.

Go to your [reddit preferences](https://www.reddit.com/prefs/) on the web, and make sure to set:

* **media** > *Thumbnails* > *Show thumbnails next to links*
* **media** > *Media Previews* > *Auto-expand media previews*

Those two settings affect the way in which the reddit API returns the data to the app.

Check if that fixes the view for you, and if so, please close this issue. Thanks!

**Comment by anonymous-user** [comment]
Thank you that fixed it!
