### ISSUE TITLE
[Enhancement] Check reddit preferences when selecting Full Height Cards

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1871]
Right now the *Full Height Cards* view depends on proper configuration of a couple of reddit preferences under **media**. And the required configuration is **not** the default one, so the view almost never behaves in the expected way.

This is further aggravated by the fact that those reddit preferences currently can't be managed in-app.

Please consider either:

* checking the configuration on reddit, and change it through the API (if the API exposes such and endpoint);
* alert users explicitly what they need to change and where for the *Full Height Cards* view to work as expected;

**Comment by laurencedawson** [comment]
I've added a dialog explaining to the user Sync needs to update a preference on their behalf if they accept. This is shown the first time they click on the full sized card option.
