### ISSUE TITLE
[BUG] Some links put Sync into a re-launch/open infinite loop

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1873]
Certain links that are handled by the app are forcing Android's "open with" prompt again and again in an infinite loop. If the user sets up Sync as the default handler, the app effectively enters in a loop that can only be ended force-closing it. 

**Scenario**

1. Tap a problematic link inside a post, comment or sidebar. A couple examples:
  * https://www.reddit.com/r/redditsync/about/rules/ (`Rules` link on /r/redditsync's sidebar);
  * https://www.reddit.com/user/Dking_293/comments/84shzs/found_an_awesome_use_for_a_broken_android_phone/?utm_source=reddit-android (reported by /u/MillionMileM8 o the sub);

**Result(s)**

* If Sync is **not** set up as the default handler:
  * The standard Android's "open with" dialog pops-up.
  * Choose open with Sync, just once.
  * The "open with" pop-up appears again.
  * The user needs to cancel the opening, or choose another app to effectively open the link.
* If Sync **is** the default handler, the app enters an infinite loop and has to be force-closed.

**Device Info**

    Sync version: 16 (beta 4)
    Sync flavor: pro

    View type: Fixed height cards
    Player type: ExoPlayer
    Push enabled: true

    Device: potter_n
    Model: motorola Moto G (5) Plus
    Android: 7.0

This has been reported in the sub several times. Here's a recent thread about the issue:

https://www.reddit.com/r/redditsync/comments/84szc7/trying_to_opening_reddit_links_with_sync_set_as/

**Comment by chaghi** [comment]
Here's another example: https://np.reddit.com/user/GallowBoob/comments/857uqd/just_closing_the_circle_nothing_to_see_here/

(from [this](https://www.reddit.com/r/redditsync/comments/85ae9x) thread)

**Comment by laurencedawson** [comment]
This has since been fixed with a handy little popup too,
