### ISSUE TITLE
[BUG] Images randomly appearing with a semi-transparent white overlay

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1875]
Sorry, I don't have a pattern to reproduce this (seems pretty random!), and it's never happened to me personally, but this is something that's been going on for a while, and has been reported several times during the past months.

Adding it here so it doesn't get lost.

These are just *some* of the threads on /r/redditsync where this has been reported, with examples and details:

- https://www.reddit.com/r/redditsync/comments/843hu3/bug_seemingly_random_images_would_get_the_read/
- https://www.reddit.com/r/redditsync/comments/863f0f/weird_highlighting_of_images/
- https://www.reddit.com/r/redditsync/comments/80t4d1/this_image_gets_much_more_washed_out_when_clicked/
- https://www.reddit.com/r/redditsync/comments/7zs28a/washed_out_image/
- https://www.reddit.com/r/redditsync/comments/7ym6kz/bug_image_becomes_washed_out_upon_opening/
- https://www.reddit.com/r/redditsync/comments/7r7l6y/bug_anyone_else_getting_images_where_the_color/
- https://www.reddit.com/r/redditsync/comments/7lzf7m/bug_this_image_gets_washed_out_after_loading/
- https://www.reddit.com/r/redditsync/comments/7kozqh/bug_images_become_washedout_when_opened/
- https://www.reddit.com/r/redditsync/comments/7bjpzy/some_ireddit_pictures_become_brighter_and_washed/

**Comment by laurencedawson** [comment]
This has since been fixed.
