### ISSUE TITLE
If a paragraph (within comments/selftext) contains a literal '<h1>', it's rendered as html

### ISSUE THREAD

**Issue by fictionic** [laurencedawson/reddit-sync-development#1877]
See [here](https://www.reddit.com/r/ProgrammerHumor/comments/86puxe/the_complexities_of_a_shitpost/dw7zopg/). Displays normally on the site, but on the app it's as though there were a double newline and then a '#'

**Comment by laurencedawson** [comment]
This has since been fixed.
