### ISSUE TITLE
[Improvement Suggestion] When push notifications are enabled, don't clear reddit chat PMs

### ISSUE THREAD

**Issue by carlylemiii** [laurencedawson/reddit-sync-development#1878]
Until reddit releases an API for chat features, it would be a nice middle ground if Sync didn't clear the notifications from the official client *for chat PMs*, which happens when Sync has push notifications enabled, since Sync intercepts all those notifications. Since Sync doesn't support chat, the notifications just get lost in translation (I can see multiple reddit client notifications in my notification log, but nothing from Sync).

This is a pain point because I don't frequently open the official app, and I use Sync more than I do the desktop site, so I have no way of knowing these PMs are coming in unless I disable push notifications or just use the official app exclusively, which I by no means want to do!

**Comment by laurencedawson** [comment]
Sadly after checking today, the contents of the notification are not accessibly.

**Comment by evanc577** [comment]
Can this issue be re-opened? Boost for Reddit has the same push notification functionality but does not clear chat notifications.
