### ISSUE TITLE
[Enhancement] Make subscriptions manager and its features more discoverable

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1879]
Sync has a lot of advanced subscriptions configuration somehow "hidden" behind the Subscriptions Manager. These are very hard to discover for new users (and seasoned users too!).

It's disheartening to read comments comparing Sync with the competition and diminishing it because "with app foo I can set different views per sub" or "with app bar I can set different ordering by sub" and so on, **all** features that Sync supports, and many times have been supporting for way before its competitors.

- Getting to the Subscriptions Manager is hard right now. Not for you, not for me. *But*, I don't know exactly why, *many* users fail to discover it. I have touched this issue on several comments on the sub, and on different issues here. Part of it might have to do with the Edit button being hard to spot, and/or confused with the search field, and/or failing to convey its function ("Go to the Subscriptions Manager").

- Part of it has to do with the separation between "Settings" and "Subscription Manager". Many users expect to configure the app through Settings. They don't expect to have a completely separate "thing" to configure other aspects of the app. They go to Settings, don't find what they're looking for, and end up assuming that what they want doesn't exist.

- The Subscriptions Manager hides several of its many features (some of which are exclusive to Sync and meant to set it apart from the competition!) under a menu that is only accessible by tapping on each sub. There's no hint on the UI that suggests that the subs are actionable/configurable, and that tapping them will bring more (useful!) options. While we are at it, the options on that pop-up menu are awkwardly worded in some cases. I have mentioned some of these issues [here](https://www.reddit.com/r/redditsync/comments/827tyf/sync_for_reddit_v16_beta_4_is_now_going_live_on/dw3lupb/).

I'm not sure what is the solution to all this, I'm no UX expert. But I'm sure it's something that it's worth improving, somehow.

Some ideas:

- Consider changing the current Edit button so it more clearly conveys its function: **configuring** the subscriptions.
- Consider moving the Subscriptions Manager to Settings altogether, or making a shortcut to the Subscription Manager there.
- Make explicit that there are options for individually configuring each sub. Maybe a "cog" icon at the far right of each line?
- Consider adding hints elsewhere in the app that some things might be set up on a per-sub basis. Maybe the "Change view" option in the overflow, the "Sort" menu on the toolbar and the "Use subreddit themes" under Theme customization could somehow mention this, or include shortcuts to the Subscriptions Manager. Maybe a "customize sub" button on the sub sidebar that opens the pop-up with the Update color/sort/etc options.

**Comment by chaghi** [comment]
Re the last point, u/SuperNanoCat [mentions](https://www.reddit.com/r/redditsync/comments/87aa4d/did_you_know_that_you_can_set_the_view_mode/dwc3h1u/) that the sidebar exposes settings for multis, so it would make sense if it exposed settings for subs too. They have a point...

**Comment by kbhutchinson** [comment]
I just spent ten minutes looking through every setting to find view customization, and finally gave up and searched the Sync sub to find out how to do it. And this is something I've already done before.

Honestly I think putting sub-specific customization under Settings _and_ in the sidebar would be a good idea. Features should be easy to find where users would naturally look.

**Comment by laurencedawson** [comment]
I've added a new section to the main settings today:

https://i.imgur.com/vO25F1C.png

And I've also added a little more icon to each row to hint to the user they can click on each item:

https://i.imgur.com/bAqJHzX.png

**Comment by laurencedawson** [comment]
I think this just about covers it?

**Comment by kbhutchinson** [comment]
This is great! Thank you.
