### ISSUE TITLE
[Enhancement] Settings > Data options > Image preloading section is a mistery for most users

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1880]
Right now almost no one knows what the different preloading options do. I've been using the app for years, I consider myself an advanced user, I have tried to explain the feature several times on the sub, but I'm not sure if even I get it, and if I'm not spreading misinformation every time I try to explain what it does.

The most common issue by far seems to be confusing "preloading" with "(don't) load thumbnails", which is not.

**Comment by laurencedawson** [comment]
Added a little description for the next release:

https://i.imgur.com/3XwRQTp.png
