### ISSUE TITLE
[Enhancement] Make the "HD button" and the setting that controls its default configuration consistent in their naming/description

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1881]
The feature is commonly known to the users as "the HD button".

The option that controls its default behaviour is named "Increase Reddit video quality". Users seem to never been able to find it by themselves (that the setting is buried in Data options, where nobody seems to look for anything doesn't help, but that's a separate issue).

Searching for "HD" in Settings brings no results.

Please consider renaming the setting to include "HD" somewhere, so at least the Setting could be found using the search feature.

- https://www.reddit.com/r/redditsync/comments/87evtx/auto_hd_videos/
- https://www.reddit.com/r/redditsync/comments/85he07/auto_enable_hd_playback_on_gifs/
- https://www.reddit.com/r/redditsync/comments/82b5ix/is_it_possible_to_make_hd_playback_for_vreddit/
- https://www.reddit.com/r/redditsync/comments/82424f/request_is_there_a_way_to_automatically_choose/
- https://www.reddit.com/r/redditsync/comments/7xorix/how_do_i_force_hd_playback_for_all_videos_and/
- https://www.reddit.com/r/redditsync/comments/7uaet4/is_there_any_way_to_have_hd_playback_the_default/
- https://www.reddit.com/r/redditsync/comments/7tllxu/is_there_any_way_to_open_all_reddit_in_hd_by/
- ...

**Comment by laurencedawson** [comment]
I've since changed this quite a bit. Cheers!
