### ISSUE TITLE
[Enhancement] "Peeking" is not clearly a synonym of "long-pressing" an image for many users

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1888]
This is similar to #1881.

For many users they are just "long pressing an image". Yet all the settings related to the feature are worded around "peeking", and many users don't see the connection. Searching for "long pressing" in settings yields no results.

Please consider adding some additional hints in settings (maybe using the description field), or changing/improving the wording, or both, so the relevant options can be spotted more easily, or at least became searchable.

**Comment by laurencedawson** [comment]
Added for the next release.
