### ISSUE TITLE
[Feature request] Option to show post author and commenter account age

### ISSUE THREAD

**Issue by thallada** [laurencedawson/reddit-sync-development#1892]
With the rise of Russian bots flooding Reddit, I think it would be really useful to have an option that displayed a user's account age inline with a post or comment. It's easy to check on the website because hovering over a username shows an info card that includes the account age. I know that the reddit sync profile page shows a user's age, but I want to know if an account is new right in the subreddit and comment thread view without having to load another page.

Though, if the user account age was added next to the post age then it would be hard to differentiate the two. I know that special users have their username highlighted in certain colors (admin: red, OP: blue, etc.). Maybe a new color could be added to indicate that an account is less than a month old. Or, to make it more subtle, change the text color of the username but keep the normal background color.

**Comment by laurencedawson** [comment]
Sadly to do this would require another call per user account which would massively slow down comments loading.

But, in the latest beta build you can enable clicking on a username which quickly links to the profile.
