### ISSUE TITLE
[Enhancement] Suggest turning HD on by default upon first use of the button

### ISSUE THREAD

**Issue by chaghi** [laurencedawson/reddit-sync-development#1893]
Somehow related to #1881.

This is just another idea for making the "reddit video quality setting" more discoverable.

It could be helpful if when the user tapped the HD button, a pop-up offered to "remember my choice [never] [always] [wifi only]", along with a note telling that this decision can be changed in settings at any time.

Ideally this would appear just once, so either the dialog should include a "Never show me this again" checkbox (ticked by default), or the app should "remember" somehow that the question was already answered.

**Comment by laurencedawson** [comment]
I'd say renaming it should be added but it's not enabled by default due to the huge amount of data it consumes.

Like it can be a few hundred mb for a 10-20 second video...

**Comment by laurencedawson** [comment]
This has since been added.
