### ISSUE TITLE
[BUG] App freezes upon opening a specific link

### ISSUE THREAD

**Issue by aflamant** [laurencedawson/reddit-sync-development#1894]
# Description

My app completely freezes and I have to force close it when I try to open [this link](https://www.reddit.com/user/vincest/comments/8d7ctd/friend_missing_please_upvote_and_contact_if_you/). 

# Scenario (steps to reproduce)

1. Open [this link](https://www.reddit.com/user/vincest/comments/8d7ctd/friend_missing_please_upvote_and_contact_if_you/)
2. Alternatively, I was trying to open it from [here](https://www.reddit.com/r/france/comments/8d7we6)

# Result(s)

App completely freezes. I have to lock my screen to be able to close it from the app drawer. If I try to open sync from Nova it freezes Nova too. 

# Device Info

OnePlus One
Android 7.1.2
LineageOS 14.1
Sync v16

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
