### ISSUE TITLE
[Enhancement] Reddit Native Inline Spoiler Support

### ISSUE THREAD

**Issue by technizor** [laurencedawson/reddit-sync-development#1895]
I just noticed a user using new Reddit Markdown that appears to be a universal, natively supported spoiler marker.

[Fire Emblem Radiant Dawn Ending Spoilers](https://www.reddit.com/r/FireEmblemHeroes/comments/8e4o4l/if_you_remove_micaiahs_tome_it_looks_like_her/dxsh4m0/)
[My own comment testing this on a test subreddit with different CSS on desktop: no actual spoilers for anything](https://www.reddit.com/r/TechnizorCSSStage/comments/7igyxw/image_macro_test/dxskwrp/?context=0)

And this was added to the Reddit wiki about [a month ago](https://www.reddit.com/wiki/revisions/commenting).

The syntax seems to be `>!spoiler content goes here!<`, and it renders as a nested `md-spoiler` class span, which needs to be clicked on to reveal.

This should be something to start tracking for when it gets officially acknowledged, as I haven't seen any official posts about it yet.

**Comment by laurencedawson** [comment]
This has since been added. Cheers.
