### ISSUE TITLE
[BUG] Toasts are not showing in v16.1

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/reddit-sync-development#1897]
When selecting flairs for a post it used to show a toast at the bottom something like 'flairs are not present for this sub' (don't know the correct sentence) if that sub has no assigned flairs, but after updating to v16.1 these toasts are not showing. I posted a few days back regarding the same issue but with ['that link has already been submitted'](https://www.reddit.com/r/redditsync/comments/8er2lk) warning toast not showing bug. Dev, can you please check this issue ?

User: /u/johnny_w94

**Device information**

    Sync version: 16.1    
    Sync flavor: pro    
    Android: 8.0.0

**Comment by laurencedawson** [comment]
Have you disabled notifications for the app on a system level?

**Comment by johnnyw94** [comment]
@laurencedawson yes, I have turned off the notifications, should I enable them ?

**Comment by johnnyw94** [comment]
@laurencedawson I enabled the app notifications & the toasts are showing again. Thank you Dev :)
