### ISSUE TITLE
Some images have weird color differences between the app and viewing them anywhere else

### ISSUE THREAD

**Issue by Muscarv2** [laurencedawson/reddit-sync-development#1900]
User /u/watdachtjijnou on reddit found that some images have a very high saturation within the app, independent of the apps image settings. Here are some images comparing how it looks inside the app versus in a browser for example: https://imgur.com/gallery/on85EJ7

We both have a Huawei P20, running Android 8.1 with the latest Sync for reddit version. I have tried changing all available screen settings in the phone but none of them makes any difference. This only seems to affect a few images too. The ones I've found are all hosted directly by reddit.

**Comment by laurencedawson** [comment]
This has since been fixed.
