### ISSUE TITLE
'Mark as Read' in notification shade is not working

### ISSUE THREAD

**Issue by johnnyw94** [laurencedawson/reddit-sync-development#1902]
Scenario:

1. After you receive a notification for a post or comment reply
2. Press "mark as read"
3. Nothing happens.
4. Repeat step 2 - Nothing happens again.

Result:

Notification is marked as read (background) but the notification doesn't close.

https://www.reddit.com/r/redditsync/comments/8j19re

https://www.reddit.com/r/redditsync/comments/8eb2tb/_/dxugzue

**Comment by laurencedawson** [comment]
Fixed in the latest beta.
