### ISSUE TITLE
V.reddit video's stop playing after a few seconds

### ISSUE THREAD

**Issue by jheiselman** [laurencedawson/reddit-sync-development#1907]
> Especially annoying because I can't seem to open them in the browser or download them to play offline.
> 
> Tried both the default video player and the new one and also tried disabling gif streaming.
> 
> Device information
> 
> Sync version: 16.3    
> Sync flavor: pro    
> 
> View type: Fixed height cards    
> Player type: Legacy    
> Push enabled: false    
> 
> Device: potter_n    
> Model: motorola Moto G (5) Plus    
> Android: 7.0

Original discussion:
https://www.reddit.com/r/redditsync/comments/8ut2q0/vreddit_videos_stop_playing_after_a_few_seconds/

**Comment by laurencedawson** [comment]
This has since been fixed.
