### ISSUE TITLE
[Feature Request] Relay subredit popular on notifications

### ISSUE THREAD

**Issue by co5mo** [laurencedawson/reddit-sync-development#1915]
whe using notifications listening the app doesnt show official app "popular on" notifications. Please implement to show also this type of notifications thanks

**Comment by laurencedawson** [comment]
Unfortunately I can't inspect the contents of notifications.

**Comment by co5mo** [comment]
can you at least let them through they are blocked when using the notification listening service

**Comment by laurencedawson** [comment]
It's all or nothing sadly
