### ISSUE TITLE
[Bug] On Android P, the previous app View won't render if the screen has been turned off and then back on (until leaving and coming back to the app).

### ISSUE THREAD

**Issue by corylulu** [laurencedawson/reddit-sync-development#1917]
**Video / Reddit Post**
https://v.redd.it/y4h90k7w65h11/DASH_9_6_M
https://redd.it/98p0nw

**Description**

On Android P, the previous app View won't render if the screen has been turned off and then back on (until leaving and coming back to the app). The app is still fully processing my taps, it just won't render.

I've seen this on more than just Sync, but it's very reproducible and frequent on Sync and has been for most of the Android P Betas, but I didn't mention anything because I knew it was still beta. 

**Scenario** (steps to reproduce)

1. Open app and go to a Reddit List View
2. Click a post to go to the comments
3. Once there, turn off phone screen and turn back on
4. Go back to List View

**Result(s)**

Scrolling will not appear to do anything, app will appear frozen, but it's not. It's just not rendering; the clicks and scrolls are still being processed though. 

**Restore Functionality**

By pressing the multitask button/gesture and entering the Multitask view, then going back to the Sync app, the List View will function normally again.

**Device Information**

>**Device** Google Pixel (North America)   
>**Android:** 9.0.0  
>**Sync Flavor:** Dev and Free   
>**Sync Version:** 16.5   
>**View Type:** Small cards, Fixed height cards

**Comment by OvermindDL1** [comment]
I was curious about this so I tried reproducing it on my Pixel 2 XL with Android 9.0.0 and couldn't do so by following the instructions above and a few variants.

**Comment by corylulu** [comment]
@OvermindDL1 Did you do it as I did in the video? The reddit thread had others say they couldn't reproduce the issue. But several devices were able to reproduce it... Based on a limited sample size, it seems to be consistent for people with the same device.

**Comment by corylulu** [comment]
It's been occurring for several weeks on several devices that other reported in the reddit thread (also linked above). Definitely not just me or just the Pixel and only started to happen in Android P (and at least 3 versions of the beta prior to the final release. But no other app appears to have this problem like Sync does. 

I might have seen it in another app before, but I definitely haven't recently... where Sync does it all the time, and not just in this situation. This was just the most easily reproducible one.

**Comment by laurencedawson** [comment]
This has since been fixed
