### ISSUE TITLE
[BUG] Gfycat streaming does not work in Swipe Mode

### ISSUE THREAD

**Issue by Fanolian** [laurencedawson/reddit-sync-development#1918]
Currently if I open a gfycat video in Swipe Mode, it has to be downloaded completely in order to watch instead of play-as-it-loads.

Steps to reproduce:
(A slow internet connection is preferable for testing.)
1. Open https://www.reddit.com/r/MilitaryGfys, which contains many long gfycat videos.
2. In non-Swipe Mode, tap on a gfycat video and observe that streaming is working as intended for now.
3. Open the subreddit in Swipe Mode.
4. Tap on a non-cached gfycat video.

Actual result:
I cannot watch the video until it is fully downloaded.

Expected result:
Streaming should be available in Swipe Mode.

Note:
Streamable and v.redd.it videos are streaming in Swipe Mode as expected. I did not test imgur videos because I cannot find a subreddit with many imgur videos...

**Device information**

    Sync version: 16.5    
    Sync flavor: pro    
    
    View type: Fixed height cards    
    Player type: ExoPlayer    
    Push enabled: false    
    
    Device: sailfish    
    Model: Google Pixel    
    Android: 9

Thank you for the app!

**Comment by laurencedawson** [comment]
Added for the next release.
