### ISSUE TITLE
[Feature Request] Preload more Imgur album images (when on WiFi)

### ISSUE THREAD

**Issue by Fanolian** [laurencedawson/reddit-sync-development#1919]
It seems that Sync preloads only the next image in an Imgur album. When I quickly swipe through an album, I have to wait for downloading even if I have a very fast (>100Mbps) internet connection.

Steps to reproduce:
1. Open https://imgur.com/gallery/tY6en in Sync.
2. Wait a bit so all (pre)loading are completed.
3. Quickly swipe left at least twice to advance the album for more than 1 image.

Actual result:
(If you start at pic1) Pic2 is instantly shown, but pic3 and beyond are not loaded until I scroll to it (or its previous image).

Expected result:
More images can be preloaded for a smoother viewing experience. (Maybe the next 10 images? Amount being adjustable, separately for WiFi and mobile data, is ideal but definitely not necessary.)

I understand this request will increase wasted data usage if preloaded images are never viewed. Therefore I suggest adding an option to select enabling such behaviour on WiFi-only or WiFi & mobile data.

**Device information**

    Sync version: 16.5    
    Sync flavor: pro    
    
    View type: Fixed height cards    
    Player type: ExoPlayer    
    Push enabled: false    
    
    Device: sailfish    
    Model: Google Pixel    
    Android: 9

Thank you for your app.

**Comment by laurencedawson** [comment]
I'd love to add this but I think it's just too much for now.
