### ISSUE TITLE
[BUG] Open angle brackets are not displayed in some situations

### ISSUE THREAD

**Issue by m42a** [laurencedawson/reddit-sync-development#1922]
### Description
This appears to be an issue when there are 2 open angle brackets in code markup followed by a close angle bracket, also in code markup.

### Steps to reproduce
View https://www.reddit.com/r/test/comments/9amkmu/testing_reddit_sync_comment_parsing/e4wjkxy/ or https://www.reddit.com/r/cpp/comments/9aashr/what_is_the_purpose_of_the_three_way_comparison/ in reddit sync.

### Result
Linked comment displays as

>First open angle bracket
> Second open angle bracket `<`
> Close angle bracket `>`

but it should display as

>First open angle bracket `<`
> Second open angle bracket `<`
> Close angle bracket `>`

Linked post is completely borked, as are many of the comments

### Device Info
Galaxy Note 5 SM-N920C
Android 7.0
Free version 16.5

**Comment by laurencedawson** [comment]
This has since been fixed in the betas.
