### ISSUE TITLE
[Feature Request] Categories for saved posts

### ISSUE THREAD

**Issue by TheFragen** [laurencedawson/reddit-sync-development#1924]
I'm the kind of user who saves a lot of posts, so naturally my 'saved' list is quite huge. Would it be possible to be able to create categories for your saved posts?

I know this isn't native to Reddit, so obviously the categories would only be saved in the app, but I would be more than happy in that case.

**Comment by laurencedawson** [comment]
This is actually build into reddit if you have reddit gold. Long press the
star to add to a category.

**Comment by TheFragen** [comment]
I'll be dammed. I take it it won't be a Sync feature for non-gold subscribers then?

**Comment by laurencedawson** [comment]
Unfortunately not, I don't duplicate gold features.
