### ISSUE TITLE
Auto-mute everything marked as "GIF" 

### ISSUE THREAD

**Issue by shoffing** [laurencedawson/reddit-sync-development#1932]
https://www.reddit.com/r/interestingasfuck/comments/9dt8q8/_/

This post is labeled as GIF, but it has an audio stream. This led to me frantically lowering my volume in public. I usually assume GIF = no audio.

If post type inference cannot be done perfectly, could you at least make it so anything inferred as "gif" is guaranteed not to make any noise?

**Comment by laurencedawson** [comment]
You can already enable this in the settings.
