### ISSUE TITLE
[Bug] Bottom Sheet menu is Transparent

### ISSUE THREAD

**Issue by rozPierog** [laurencedawson/reddit-sync-development#1935]
I think it may be related to the autonight mode. Still there after restart.
If you need additional information please let me know.
Device: OnePlus 3T
Sync Version: 17 beta 8
![screenshot_20180919-183106](https://user-images.githubusercontent.com/23499434/45767348-3c43c700-bc3a-11e8-8231-1a984885c196.jpg)

**Comment by laurencedawson** [comment]
This has been fixed for the next release.
