### ISSUE TITLE
[BUG] ANR on Android P (Pixel 3)

### ISSUE THREAD

**Issue by MichaelEvans** [laurencedawson/reddit-sync-development#1947]
I'm seeing a pretty consistent ANR on App launch on Pixel 3. Stack trace is:

Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago)

I've submitted the ANR info via feedback, so likely will find them in the Play Console.

Let me know if there's anything I can do to help diagnose!

**Comment by laurencedawson** [comment]
Which version? Pro?

**Comment by MichaelEvans** [comment]
Seems to be fixed (or happening way less frequently) on 17.2 (beta 2).

I'll close this and re-open if I can repro again!
