### ISSUE TITLE
[BUG] Renderer issues

### ISSUE THREAD

**Issue by MrXpertt** [laurencedawson/reddit-sync-development#1950]
Nexus 7 2013, Android 6.0.1 stock

Can't view many v.redd.it videos because it displays a message saying the renderer is at fault.
I can confirm this not only on the app but also on the chrome player, as some videos played there won't load at all. I suspect both players may have some similarities.

What I think may have to do with it:
- Restarting and software resetting (holding power down until the device turns off) solves the problem temporarily, which makes me think it may be an Android caching issue. HOWEVER, clearing sync's cache doesn't even temporarily solve it.
- Some videos on the VLC player stutter. Disabling hardware acceleration fixes it. That may also be related to the issue.
- The YouTube app's player stutters (showing only ≈2frames/sec) on 60fps videos. However, using YouTube Vanced's experimental player (ExoPlayer V2) solves this.

What isn't the issue:
- I have tried to disabling battery optimization on every app (including system apps) and performed a software reset, after a while the problem persisted. So it isn't the battery optimization's fault.
- I have enabled "Force GPU rendering" and "Disable HW overlays" and those haven't fixed the problem.
- I have tried the legacy player on the app and the problem persists.
- I have reinstalled the app multiple times and it persisted.

More info:
- I have flashed lineage OS 14.1 before, but due to WiFi problems (5ghz band not appearing), I moved back to stock.
- Sometimes, before the error occurs, the lower quality video preview plays fine. But most of the time even the preview doesn't play.

I know that, if it doesn't have to do with the app, you might not feel the need to fix this or at least attempt to. But I just don't want to change platforms, or waste any more money on stuff that may not be worth it. I have been trying to fix this for a while, but haven't found any solution yet.
I just wanted some help from people who know more about Android than me.

All of these problems don't reproduce on my Nexus 5X Android 8.1.0 stock.

**Comment by laurencedawson** [comment]
Sync uses ExoPlayer for video rendering. Often third party ROMs have issues
with this. I'd suggest trying a different ROM or switching back to stock.
