### ISSUE TITLE
Sync removes apostrophes when searching.

### ISSUE THREAD

**Issue by xwilx** [laurencedawson/reddit-sync-development#1973]
When searching for posts with an apostrophe, Sync returns results without an apostrophe.

For example, I would type the word ```What's ``` into the search bar but Sync will return results for ```Whats``` instead. It has been reported on the subreddit nearly 2 years ago, Lawrence commented on one of them:    

[Report 1](https://www.reddit.com/r/redditsync/comments/4ai716)      
[Report 2](https://www.reddit.com/r/redditsync/comments/6guzea)

**Comment by laurencedawson** [comment]
Fixed for the next build.
