### ISSUE TITLE
Some image previews zoom in when peeking

### ISSUE THREAD

**Issue by amiyuy** [laurencedawson/reddit-sync-development#1977]
Scenario (steps to reproduce)

1. View an image post in your feed or on the subreddit. 
2. Long press to preview. 

Result(s)

Image is zoomed in when previewing.

Note

Does not happen with all or even most images, but I've seen it multiple times over the past several days. 

Device Info

    Sync version: 18.1 and 18.1.1
    Sync flavor: free    
    Removed ads: true    
    
    View type: Full height cards    
    Player type: ExoPlayer    
    Push enabled: false    
    
    Device: beyond0q    
    Model: samsung SM-G970U1    
    Android: 9

Screenshot
 https://www.reddit.com/r/thelastairbender/comments/be3its/_/

1. [In feed](https://i.imgur.com/dfPAZUX.jpg)
1. [When opened with tap](https://i.imgur.com/1NDVTqS.jpg)
1. [Long press preview ](https://i.imgur.com/UOrix1C.jpg)

Also happens with: 

* https://www.reddit.com/r/teslamotors/comments/be4340/_/
* https://www.reddit.com/r/vexillology/comments/be4iau/_/
* https://www.reddit.com/r/libertarian/comments/beyj0r/_/
* https://www.reddit.com/r/kenm/comments/bfjr6s/_/
* https://www.reddit.com/r/funny/comments/bfgqet/_/
* https://www.reddit.com/r/selfawarewolves/comments/bfdo15/_/
* https://www.reddit.com/r/decreasinglyverbose/comments/bfojjw/_/
* https://www.reddit.com/r/apexlegends/comments/bfqcxa/_/
* https://www.reddit.com/r/trashy/comments/bfoyw5/_/

(Reddit post: https://www.reddit.com/r/redditsync/comments/be9oe8/_/ )

**Comment by laurencedawson** [comment]
Fixed for the next release.
