### ISSUE TITLE
Implement Android 10 system-level theming

### ISSUE THREAD

**Issue by carlylemiii** [laurencedawson/reddit-sync-development#2002]
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app

Should be three options on Android 9 (and earlier) devices:

- Light
- Dark
- Set by Battery Saver (the recommended default option)

**Comment by dudeofawesome** [comment]
3rd option should be "Follow system theme"

**Comment by carlylemiii** [comment]
Whoops, thanks, @dudeofawesome. We're both half-right. It's even in the link I provided, but I left half of it for this issue accidentally.

> When running on Android 10 (API level 29) and higher, the recommended options are different, to allow the user to override the system default:
> - Light
> - Dark
> - **System default** (the recommended default option)

**Comment by leifalbor** [comment]
+1 from me.  I'm using a workaround method via Tasker to modify shared_prefs to set follow the system theme, but would much rather a solution be baked into the app itself.

**Comment by laurencedawson** [comment]
This has since been added.

**Comment by carlylemiii** [comment]
Where? I don't see a "system default" option.

**Comment by laurencedawson** [comment]
Added to the latest alphas and pre production builds.
