### ISSUE TITLE
[BUG] v.redd.it Dash videos can't be opened

### ISSUE THREAD

**Issue by JohannesPertl** [laurencedawson/reddit-sync-development#2005]
Videos in this format https://v.redd.it/9pgfmshg9rz31/DASH_1080 - where 'DASH_1080' determines the quality and could also be 'DASH_720' or 480 and so on - can't be opened in the app. Instead, this error gets shown:

     ERROR: COULD NOT LOAD VIDEO

**Comment by laurencedawson** [comment]
Fixed for the next release.
