### ISSUE TITLE
[BUG] Toggling Dark mode/Light mode ON and OFF

### ISSUE THREAD

**Issue by josephmalonda** [laurencedawson/reddit-sync-development#2101]
When you toggle Dark mode or Light mode, 

**The app itself does not automatically renders the whole app into Dark mode.**
![Screenshot_20210118_184321](https://user-images.githubusercontent.com/65003163/104907368-f0e38400-59bf-11eb-9b25-53c0a14bbf36.jpg)

**Same as toggling back into Light mode.**
![Screenshot_20210118_184330](https://user-images.githubusercontent.com/65003163/104907414-0658ae00-59c0-11eb-85dd-de62b9c18e18.jpg)

**And it leaves broken transition where the top UI is completely not affected with the changes.**
![Screenshot_20210118_184334](https://user-images.githubusercontent.com/65003163/104907498-28523080-59c0-11eb-8c57-dff2d057289b.jpg)

**Comment by laurencedawson** [comment]
Any reason why this was closed?

**Comment by josephmalonda** [comment]
> Any reason why this was closed?

@laurencedawson I don't know which version fixed it but the problem does not happen to occur anymore when you toggle the modes through settings. It might be probably the version where fixed the modes transition. 😃
