### ISSUE TITLE
Bottom sheets too narrow

### ISSUE THREAD

**Issue by osiride** [laurencedawson/reddit-sync-development#2106]
I know supporting tablets [is not a priority](https://www.reddit.com/r/redditsync/comments/kzo31o), but bottom sheets are awkwardly narrow on an 8 inches tablet (1280x800, 189 ppi).

Using Sync Pro v20 (beta 28), screenshots attached.
![Screenshot_20210124-222719](https://user-images.githubusercontent.com/733811/105644411-bbdea200-5e95-11eb-8c88-194d411ab6d1.png)
![Screenshot_20210124-222818](https://user-images.githubusercontent.com/733811/105644412-bda86580-5e95-11eb-8db3-90c42b07a134.png)

**Comment by laurencedawson** [comment]
Look ok in landscape?

**Comment by osiride** [comment]
> Look ok in landscape?

Screenshots in landscape: 
![Screenshot_20210124-225540](https://user-images.githubusercontent.com/733811/105644744-74f1ac00-5e97-11eb-9cff-44d8814a3524.png)
![Screenshot_20210124-225528](https://user-images.githubusercontent.com/733811/105644748-7622d900-5e97-11eb-902c-96be9a9529a9.png)

**Comment by laurencedawson** [comment]
Better. I'll get it sorted for portrait.

**Comment by osiride** [comment]
Fixed in beta 32, thanks!
