### ISSUE TITLE
[BUG] comment navigation bar no padding in full screen 

### ISSUE THREAD

**Issue by jkgao** [laurencedawson/reddit-sync-development#2112]
On devices with gesture navigation but with the navigation bar hidden (root or natively) the comment navigation bar has no padding.

Looks like this issue started in beta 30. 

![b29](https://user-images.githubusercontent.com/5335323/107915274-71df5e00-6f21-11eb-9cbb-bfd9708198a7.png)

![b30](https://user-images.githubusercontent.com/5335323/107915296-7ad02f80-6f21-11eb-97f2-daa1945348d2.png)

**Comment by laurencedawson** [comment]
How does one even hide the gesture nav bar?

**Comment by jkgao** [comment]
There’s native methods from OnePlus and Samsung. As for the technicalities, I’m not sure. Here’s a comment thread of people experiencing this issue on Samsung devices.

https://reddit.com/r/redditsync/comments/lfssy7/_/gmnt89l/?context=1

I had a OnePlus that was able to do this but switched to a Pixel device earlier last month. It didn’t have a native method so those screenshots above are via root. 

You can see in the thread that I was questioning whether it was a root issue but before I switched to the Pixel, the version I had On my OnePlus was v29 which didn’t have the issue.

**Comment by jkgao** [comment]
If it wasn’t clear, the top screenshot is v29 and the bottom one is v30. Got these from Aurora with the build numbers. Screenshot only taken minute apart.

**Comment by laurencedawson** [comment]
Fixed
