### ISSUE TITLE
Use URL links to go to Reddit content

### ISSUE THREAD

**Issue by alecloudenback** [laurencedawson/reddit-sync-development#2148]
With Reddit's well known dark practices related to browsing on mobile, it would be nice to be able to go to content on Sync by pasting a URL into the app.

For example, a friend sends a link and clicking on it opens the reddit website where they will only show the content if you download the official Reddit app. This is on Android (Google Pixel 6)

It would be nice to be able to copy the shared URL and open the content in Sync somehow.

**Comment by anonymous-user** [comment]
Can't you use the apps' share function to open the link in Sync?

**Comment by alecloudenback** [comment]
Yep, that works. Didn't know about that.
