### ISSUE TITLE
Improved Sub-Reddit Search (Sub-Reddit Manager)

### ISSUE THREAD

**Issue by bmcclure937** [laurencedawson/reddit-sync-development#228]
I think an improved UI is needed to go along with the many requests for subscribing to sub-Reddits from Reddit Sync. 

The UI should show "top sub-Reddits", have the ability to search for sub-Reddits, etc. 

---

This would pair nicely with the requests to have the ability to subscribe to sub-Reddits. The new UI could be a "sub-Reddit manager" of sorts.

**Comment by laurencedawson** [comment]
I think this has been fixed by implementing subscribe from the sidebar.
