### ISSUE TITLE
Support for subdomains such as np.reddit.com

### ISSUE THREAD

**Issue by MillenniumFalc0n** [laurencedawson/reddit-sync-development#237]
Could you have Redditsync recognize reddit subdomains as valid Reddit links? I.E. when I click a link such as http://np.reddit.com/r/NoParticipation/comments/10mqi3/how_to_install_noparticipation/[1] could you have it open in the app instead of in the browser?

**Comment by laurencedawson** [comment]
Added support for np links in the next release. Hurrah!

**Comment by chaghi** [comment]
It seems that if the np link is used to point to a sub (example `http://np.reddit.com/r/oddlysatisfying`) as opposed to a specific thread, the link is opened in the browser, not in-app.

Example comment with such a link: https://www.reddit.com/r/DesirePath/comments/70p7ge/the_paths_around_these_bombers_xpost_from/dn4uk9l/ (see the link to `/r/oddlysatisfying` there)

Relevant discussion on `/r/redditsync`: https://www.reddit.com/r/redditsync/comments/70p7e4/pro_subreddit_linking_and_swipe_view_escaping/?ref=share&ref_source=link
