### ISSUE TITLE
"Gallery Mode" for browsing image-heavy subreddits

### ISSUE THREAD

**Issue by acarlson1029** [laurencedawson/reddit-sync-development#250]
**Browse posts via "Gallery Mode"**

Inspired by your "gallery viewer" post from earlier. With the current state of affairs, browsing a subreddit like /r/aww or /r/earthporn is best done by clicking the thumbnail, hitting back, clicking the next thumbnail, hitting back, etc. Some people have released reddit clients *just* for browsing images in certain subreddits. The "Gallery Mode" wouldn't replace traditional browsing, but would be a feature that could be activated in the Menu (maybe click on Gallery Mode in the menu to enable it for the current subreddit). It's great for quickly browsing the dozens of image-heavy subreddits on the website, and could be used for videos as well (as far as preview images go), but I'm not sure how it would handle browser or reddit links.

(1) http://i.imgur.com/xX2kzaG.png

* Similar to the submission card when opening a post, but doesn't show comments
 * Tapping the image will bring it up in the gallery, just like with a submission
* Persistent post action bar on the bottom
 * Perhaps more stripped down than the full version?
* Button in top action bar to open up the comments
 * Could use a swipe up from the bottom to get there as well
 * Or, dragging the card up reveals comments hidden below the screen
* Missing:
 * Vote count on the card itself
 * NSFW badge
 * Album indicator

(2) http://i.imgur.com/Yeekb3O.png

* Swipe to the right to reveal the next submission, similar to the internal gallery

(3) http://i.imgur.com/7HCLXPS.png

* Puppy

***

Here is a GIF mockup for the animations:

* [Gallery Mode](http://i.minus.com/ibdQkLfHRQh05v.gif)

**Comment by laurencedawson** [comment]
For the moment this can be resolved using "Swipe for reddit".

**Comment by agret** [comment]
I have downloaded swipe for reddit but can find no way to login to the app

**Comment by laurencedawson** [comment]
Merging with #883.
