### ISSUE TITLE
Support table formatting...

### ISSUE THREAD

**Issue by matthileo** [laurencedawson/reddit-sync-development#260]
Tables that are formatted on reddit look like blobs of text on Reddit Sync

**Comment by laurencedawson** [comment]
At long last I've added this. Will be in the 10.2.0 release.

**Comment by Knoxie** [comment]
AWESOME!

**Comment by jamesdaily** [comment]
Great, thank you!

http://reddit.com/r/buildapc makes heavy use of this if you'd like to test some real world tables.

**Comment by laurencedawson** [comment]
That's where I've been testing!
