### ISSUE TITLE
Add intent filter to open redd.it links in app.

### ISSUE THREAD

**Issue by cfsharp** [laurencedawson/reddit-sync-development#287]
I was browsing my twitter feed and I came across an AMA that was posted using reddit's truncated URL system redd.it, and when I clicked on it I got the options to open the link in Reddit News, or the two browsers on my phone. Opening in the browser takes the user to the redd.it page, then redirects to the actual reddit post, which then allows the option of opening the link in Reddit Sync. Adding the ability to open redd.it links directly would streamline this process.

**Comment by laurencedawson** [comment]
Added support for redd.it links in 10.7.8. Cheers!
