### ISSUE TITLE
The dedicated comments page uses space poorly on 10-inch Tablets

### ISSUE THREAD

**Issue by matthileo** [laurencedawson/reddit-sync-development#295]
The current dedicated comments page for tablets has _a lot_ of whitespace. I like whitespace as much as the next guy, but only to a point.

Solution 1: Expand the comment area's width, and the image preview's height.

![ozu65l9](https://f.cloud.github.com/assets/2176622/867137/47a1387c-f6d7-11e2-897d-699417ec2b3d.png)

Solution 2: Change the dedicated comments page to a popup, like google+.

![0mfrbao](https://f.cloud.github.com/assets/2176622/867140/576c1ee8-f6d7-11e2-97ac-2c27637cfa9e.jpg)

**Comment by laurencedawson** [comment]
This has been updated for v22.
