### ISSUE TITLE
Toggle to hide links I've read/seen.

### ISSUE THREAD

**Issue by THM-KLA** [laurencedawson/reddit-sync-development#310]
A way to hide links/posts I've already read or seen. Reddit: Never Purple does this I think. https://play.google.com/store/apps/details?id=com.akasoft.reddit

**Comment by gatorheel** [comment]
I would really love to see this too.  When I'm on a reddit binge but briefly multitask to a different app, often Reddit Sync Pro will refresh my frontpage and I'll have to scroll through dozens of links I've already seen.  Bonus points if you also add a toggle to automatically mark-as-read links as you scroll through them (like Feedly does).

**Comment by laurencedawson** [comment]
Added in 10.2.0.
