### ISSUE TITLE
2 bugs with "View more" as a top-level comment that can't be loaded.

### ISSUE THREAD

**Issue by Moter8** [laurencedawson/reddit-sync-development#316]
1. View more as top-level comment which when pressed shows Loading for some seconds but then returns to View more with no change.
2. View more as top-level comment with no "closed box".

Screenshot album with the 2 bugs appearing:
http://imgur.com/a/3MGOe

SGS3 CM10.1 if that matters. And seems to only happen on high-upvote-threads/comments such as in askreddit etc

**Comment by laurencedawson** [comment]
Haven't seen this in a long long time. Closing for now.
