### ISSUE TITLE
Option to move "action bar" to the bottom (for large phones)

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#319]
Hi! To upvote or downvote a comment, the action bar is placed at the top of the screen. Unfortunately, for large phones, this requires you to stretch your hand as it usually rests near the bottom of the phone because of the home button. 

I would like to request a setting to allow the user to decide to place the bar on the bottom versus the top. Users with software navigation buttons (see Nexus and now other phones), the bottom action bar is harder, though, so a setting/toggle/option is preferred. 

A discussion we had in /r/Android: http://www.reddit.com/r/Android/comments/1fnkyh/action_bar_on_top_sucks_for_large_phones/

**Comment by laurencedawson** [comment]
Voting options now appear under each comment. I'll not be adding an option to move the entire ActionBar.

**Comment by Presto99** [comment]
thanks so much!!
