### ISSUE TITLE
[Request] Option to change pane area ratio in dual pane mode for smaller screens (resolutions).

### ISSUE THREAD

**Issue by kefkf** [laurencedawson/reddit-sync-development#327]
The area ratio of left pane to right pane in the dual pane mode is about 40% to 60% in reddit sync.
Screenshot:
![Screenshot](http://i.imgur.com/Lqi1jSo.png)

This used to be the case in reddit sync developer version.
Screenshot:
![Screenshot](http://i.imgur.com/CenPxms.png)

In the latest versions (8.0.29+) however the pane ratio has changed from 40% - 60% to 50% - 50%.
Screenshot:
![Screenshot](http://i.imgur.com/gqFL1Ct.png)

As a result the screenspace that can be used for the right pane (in my opinion the more important pane) is wasted on the left pane.
This issue is even more prominent on devices with smaller screens (resolutions) where the screenspace is already limited.

Therefore I request a new option "Small Screen Mode for Dual Pane" which, when toggled, would change the pane area ratio 40% - 60% in dual pane mode.

Thank you.

**Comment by laurencedawson** [comment]
I've since switched to a more suitable default ratio.

I've also added the ability to configure multiple columns for the card view and enable / disable dual pane mode.
