### ISSUE TITLE
Multireddit management

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/reddit-sync-development#359]

**Comment by LoveIsGrief** [comment]
Are multireddits supported now? I can't seem to find it :\

**Comment by mattcooperkay** [comment]
Have you implemented the edit feature yet? Can only find a refresh... Thanks

**Comment by Nxt3** [comment]
I didn't realize this was from a year and a half ago. Dang.

**Comment by laurencedawson** [comment]
These have now been added for the upcoming v12.1 release. Cheers.
