### ISSUE TITLE
Add notification quick actions for reply and mark as read (and maybe view profile).

### ISSUE THREAD

**Issue by matthileo** [laurencedawson/reddit-sync-development#384]
~~1. Option to turn on notifications for all accounts.~~

~~2. Give users a choice of multiple notification light colors, OR switch back to blue, OR find a shade of orange compatible with more devices~~

~~3. Add an option to show each notification separately, instead of grouped.~~
1. Add notification quick actions for reply and mark as read (and maybe view profile).

**Comment by laurencedawson** [comment]
Added for the next beta. Cheers.
