### ISSUE TITLE
Use a padded view for the subreddit manager on tablets

### ISSUE THREAD

**Issue by matthileo** [laurencedawson/reddit-sync-development#388]
The subreddit manager currently looks like this

![2013-11-10](https://f.cloud.github.com/assets/2176622/1509886/c560a33a-4a68-11e3-80b9-e4ce925728a7.png)

Using a padded view similar to the settings page will make it more agreeable on tablets

![2013-11-10 1](https://f.cloud.github.com/assets/2176622/1509888/d3dcd9a6-4a68-11e3-84c2-ec99e0ca193d.png)

**Comment by laurencedawson** [comment]
Closing as these days the settings uses the full width too.
