### ISSUE TITLE
Please add option to disable Dual Pane in LANDSCAPE as well as in PORTRAIT

### ISSUE THREAD

**Issue by whatsupbras** [laurencedawson/reddit-sync-development#416]
Wish that you could add a toggle in the settings to disable dual pane in landscape mode since the text is too scrunched together on a Nexus 7 tablet.

Also I know apeing or copying off another app is not good practice, but please check out the mobile version of BaconReddit. That apps search function makes it very useful. You can search all of reddit, specific subreddits you are browsing or you type in, and reddit users. Reddit sync is not missing many features and I would love to see it become THE reddit app on Android like AlienBlue is on iOS.

Keep up the good work!

**Comment by laurencedawson** [comment]
Yup this falls under the magazine layout. 

In the new material redesign 2.0 the number of columns will be a configurable option.
