### ISSUE TITLE
Double tap or other gesture for next parent

### ISSUE THREAD

**Issue by mondO** [laurencedawson/reddit-sync-development#426]
The little arrows used to jump between parent posts are really nice, but the one in the bottom right corner overlaps slightly with the quick scroll bar area. When quick scroll is on, I frequently touch the quick scroll area when trying to advance to the next parent post, causing the thread to jump almost all the way to the bottom and losing my spot. 

I turn off quick scroll to avoid this, but I like using quick scroll occasionally, so it would be great if there was some way to avoid hitting the quick scroll area when advancing to the next parent comment. I think that using a double tap to skip forwards and a triple tap to go backwards would be one possible workaround (I don't think there is anywhere else to put those buttons unfortunately.) 

It's your call LJD, I really like your app and just thought this could be one small improvement to an awesome reddit browser. Ultimately, I think some other feature requests and bugs should be given higher priority, but you should be the judge. Thanks for your time!
![screenshot_2013-11-29-00-39-10](https://f.cloud.github.com/assets/6064021/1643182/c8d68e72-58b8-11e3-8223-08ca0601f94a.png)

**Comment by laurencedawson** [comment]
I've since added volume buttons to navigate comments and a navigation bar.
