### ISSUE TITLE
[Request/bug fix?] Sharing images to other apps

### ISSUE THREAD

**Issue by traveltoaiur** [laurencedawson/reddit-sync-development#450]
Pro user here.
Sharing an image to other apps ( in this case, Whatsapp ), always results in this text being shared:
"LINK - LINK" ( same link posted twice )
instead of
"Reddit post title - LINK"
I'm pretty sure this is not intended

Can this be fixed or implemented? Thank you!

**Comment by laurencedawson** [comment]
Added for the next release. Cheers.
