### ISSUE TITLE
Newest post hides itself when new posts come in

### ISSUE THREAD

**Issue by xxdmnxosxx** [laurencedawson/reddit-sync-development#475]
So this is tested confirmed on both my Verizon Galaxy S3 both on Carbon JB 4.3.1 and CM 11 latest Nightly (8th) and mostly confirmed AT&T Galaxy S3 stock unrooted where if I hide I think 3 or so cards using the swipe to hide function, if I scroll down to where more posts load, the top most post that comes in will hide itself, it fixes itself if you go into a different subreddit or restart the app, but it will continue once you hide more things.  Also mostly confirmed that it only happens with magazine view 

Additional info: Everything works peachy on my Nexus 10, only happens on my phone.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
