### ISSUE TITLE
Collapsing comments leave behind "Load more" children

### ISSUE THREAD

**Issue by Eseb** [laurencedawson/reddit-sync-development#479]
This is a bug I've noticed ever since the cards UI version of the app came out. Currently using RS Pro v8.0.53.

In this screenshot what happened was that there was a "Load more" option under _houad_'s (purple) comment. After pressing it, it loaded all the other children.
http://i.imgur.com/b8GYQ1w.png

After I finished reading what I wanted to read I collapsed the top-level comment in the thread which was _ailetoile_'s, but a bunch of child posts were left over.
http://i.imgur.com/MYH9HuP.png

This bug happens very often when using the "Load more" thing and then collapsing the parent. It doesn't _always_ happen -- I'd say maybe 2/3 of the time.

**Comment by laurencedawson** [comment]
This has since been fixed.
