### ISSUE TITLE
Option to only display top-level comments by default and tap to expand comment thread?

### ISSUE THREAD

**Issue by TehCrucible** [laurencedawson/reddit-sync-development#490]
Hopefully my title is self explanatory.  Had a quick browse of issues and didn't see this one suggested.  Was using reddit sync this morning and realized how great it would be to be able to quickly skim top-level comments to avoid getting bogged down in pun threads and nonsense that inevitably rise to the top of almost every post.

**Comment by laurencedawson** [comment]
This has since been added. Cheers.
