### ISSUE TITLE
Android crashes after clicking multiple links

### ISSUE THREAD

**Issue by inasm** [laurencedawson/reddit-sync-development#533]
For example go to this link in RedditSync:

http://www.reddit.com/r/talesfromtechsupport/comments/20mhpl/security_it_queen_to_it/

Keep clicking next at the bottom of each post, when I get about 5 layers deep, it starts getting laggy. After I got a few posts deeper graphic glitches started to occur(think a graphics card without a proper driver installed), and after a while it crashed android.

I am running ParanoidAndroid on a Galaxy Nexus.

**Comment by laurencedawson** [comment]
I think this was caused by the expanded comment links. Can't seem to replicate these days.

**Comment by inasm** [comment]
I actually seem to still have the issue. It hasn't bothered me though, and it does seem like it takes longer to crash it now. There have been similar issues reported on other apps, so I think the issue is device specific and doesn't need fixing(the galaxy nexus will be obsolete in 5 years anyway).
