### ISSUE TITLE
Share image instead of link

### ISSUE THREAD

**Issue by FatherMadman** [laurencedawson/reddit-sync-development#538]
I would like to be able to share an image instead of the url link. Reddit Flow has this ability but is severely lacking in others. Another would be able to save the file to Google Drive, Dropbox, or Box instead of locally on your device.

Reddit Flow had two separate share submenus. One is the normal share menu which is what Reddit Sync has and then there was a second share menu that would allow you to share the image you are viewing out as the file itself to say Hangouts, SMS, G+, Google Drive, Dropbox, PushBullet, etc. Sharing to Google Drive it makes creates a file with the URL as the name.ext @ 0KB. Sharing the image out shares the link instead of the image.

The request is for more than just to share images in this manner but images would probably be the highest shared out of any other file using this request.

**Comment by laurencedawson** [comment]
Added for the next release. Cheers.

**Comment by iamcanadian2222** [comment]
You are the best. I've been waiting for this feature for quite some time!
