### ISSUE TITLE
Add Multi Window support for Samsung phones.

### ISSUE THREAD

**Issue by torin1001** [laurencedawson/reddit-sync-development#552]
It would be a really cool feature, I don't think other Reddit apps have support for it.

Edit, here is this if it helps 
http://developer.samsung.com/samsung-mobile-sdk#multiwindow

**Comment by RagingRoosevelt** [comment]
Has the feature been implemented? It doesn't x seem to work on the galaxy S6.

**Comment by laurencedawson** [comment]
@RagingRoosevelt No, the issue is still open.

**Comment by laurencedawson** [comment]
Added for the upcoming 10.7.12 release. Cheers.
