### ISSUE TITLE
Text in code tags does not retain spaces

### ISSUE THREAD

**Issue by CMahaff** [laurencedawson/reddit-sync-development#558]
Example Image:
![http://i.imgur.com/7xACC5W.png](http://i.imgur.com/7xACC5W.png)

This also messes up various types of ASCII reddit users submit. 

Indenting multiple times might be too much within a comment window though, it could lead to a lot of line wrapping. I suppose another solution would be an option in the comment overflow menu to open the segment in a separate pane that let you scroll horizontally.

Sorry if this is fixed in the nightly - I know it has a new markdown parser but we can't open comments in the available apk. Cheers.

**Comment by laurencedawson** [comment]
Fixed in 10.7. Cheers.
