### ISSUE TITLE
Ignore spaces in sub-reddit fields

### ISSUE THREAD

**Issue by RTLM** [laurencedawson/reddit-sync-development#569]
Sub-reddits can't have spaces in them so it would be nice if when entering a sub-reddit it would ignore any spaces I've entered. I say this because of keyboards auto correcting and it's a lot easier for me to enter "reddit sync" than it is for me to enter "redditsync" especially if I make an error

**Comment by laurencedawson** [comment]
This was fixed in a previous release.
