### ISSUE TITLE
When logging in, if the dialog is dismissed, user is logged in but not shown 

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#579]
I was logging in. I accidentally cancelled the dialog and I got a Toast saying it was canceled. I then tried to open the side bar and log in again but it said the account was already added. However, the account wasn't listed. I closed the app and opened it again. Still, I wasn't logged in but my account showed up in  the drop down so I can select it.

**Comment by laurencedawson** [comment]
This has since been fixed when sync switched to using OAuth.
