### ISSUE TITLE
When a subreddit doesn't exist...

### ISSUE THREAD

**Issue by pishee** [laurencedawson/reddit-sync-development#589]
...maybe show some kind of message?
With a blank page seems like you have an error, not that the page doesn't exist.

![image](https://cloud.githubusercontent.com/assets/7676575/3072339/cf563dfa-e2c5-11e3-8442-195873b66585.png)
![image](https://cloud.githubusercontent.com/assets/7676575/3072336/be3d0346-e2c5-11e3-8bb6-5982e329c789.png)

**Comment by laurencedawson** [comment]
This has since been added. Cheers.
