### ISSUE TITLE
Changing the font size and then flipping the phone crashes everything

### ISSUE THREAD

**Issue by pishee** [laurencedawson/reddit-sync-development#590]
1. Go to the Settings
![image](https://cloud.githubusercontent.com/assets/7676575/3072487/ad2dc8d0-e2c8-11e3-957c-5df150935ace.png)

2. Change the font size
![image](https://cloud.githubusercontent.com/assets/7676575/3072490/c0a1ecc0-e2c8-11e3-8f63-c911aac804fd.png)

3. Back to the reddit sync home screen
![image](https://cloud.githubusercontent.com/assets/7676575/3072491/c6b95396-e2c8-11e3-8833-8dfe07e00634.png)

4. Go again to the Settings
![image](https://cloud.githubusercontent.com/assets/7676575/3072501/cebef708-e2c8-11e3-854e-ec1aa4ad38ed.png)

5. Change the font size on more time
![image](https://cloud.githubusercontent.com/assets/7676575/3072503/d267f58a-e2c8-11e3-8082-24e7a0ff5892.png)

6. Flip the phone to landscape
![image](https://cloud.githubusercontent.com/assets/7676575/3072513/fae22558-e2c8-11e3-92ec-b0208b7d50e3.png)

7. Scroll down a bit
![image](https://cloud.githubusercontent.com/assets/7676575/3072514/fe0dd092-e2c8-11e3-87f1-1922d3040598.png)

8. Flip again to portrait
![image](https://cloud.githubusercontent.com/assets/7676575/3072517/05297a34-e2c9-11e3-821e-193bdce1d214.png)

9. Black screen
![image](https://cloud.githubusercontent.com/assets/7676575/3072521/099dba80-e2c9-11e3-9341-b827fe675790.png)

**Comment by laurencedawson** [comment]
Closing as I'm unable to replicate this issue.
