### ISSUE TITLE
Arrow Buttons Skipping Comments

### ISSUE THREAD

**Issue by Sibelius343** [laurencedawson/reddit-sync-development#591]
When using the arrow buttons to move between parent comments, it will skip over some parent comments sometimes. This especially happens when moving between parent comments with few/no replies.

In previous versions, this would only happen if "autohide action bar" was enabled. However, now the issue occurs when the autohide function is disabled as well.

Using the latest Dev version.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
