### ISSUE TITLE
More formal handling of multireddits

### ISSUE THREAD

**Issue by jliu168** [laurencedawson/reddit-sync-development#594]
At the moment, multis are created by going to the edit subreddit menu and adding a subreddit in the form of "[subreddit1]+[subreddit2]+[subreddit3]", and so on and so forth.  It would be a little more user-friendly if setting up multis was like how you do it on the desktop site, where you give a multi a name and populate it with subs.  For example, I could create a multi called "games" and populate with /r/gaming and /r/gamedeals.

**Comment by laurencedawson** [comment]
Merging into the big multireddit thread:

https://github.com/laurencedawson/reddit-sync-development/issues/359
