### ISSUE TITLE
Frontpage sidebar

### ISSUE THREAD

**Issue by pishee** [laurencedawson/reddit-sync-development#599]
![image](https://cloud.githubusercontent.com/assets/7676575/3075453/f64a5780-e378-11e3-82d8-1e3252897834.png)
[Animated GIF](http://i.imgur.com/1l7JvUT.gif)

Maybe it's not really handsome, but I wonder if it's not the kind of information to put in the Frontpage and the "all" sidebar.

**Comment by laurencedawson** [comment]
In the latest upcoming beta I've added trending subreddits to the sidebar. Cheers.
