### ISSUE TITLE
New subscribed subreddits topping the subreddit list

### ISSUE THREAD

**Issue by pishee** [laurencedawson/reddit-sync-development#600]
From reddit: ["The new subreddit is listed first (above the front page and out of alphabetical order) regardless of if I have switched back to the front page/closed the app."](http://www.reddit.com/r/redditsync/comments/268a5i/bug_after_subscribing_to_new_subreddits_the_next/)

**Comment by laurencedawson** [comment]
Added in 10.7.8.
