### ISSUE TITLE
make X w/i thread auto-back to sub w/undo therein

### ISSUE THREAD

**Issue by sigosaur** [laurencedawson/reddit-sync-development#602]
the X in the sub hides the thread immediately ... one tap ... awesome!

if ya open a thread, and tap the X therein, it says it hid the thread, and pops up the undo, but you're still in the thread, and need to tap back, to return to the sub

IMO, no one would tap the X inside a thread, expecting anything different than the X in a sub

moreover, if the undo is still available, even if they tapped it by mistake, they can still recover

regardless, the net result of both X's would then be identical ... looking at the list of threads in the sub, with the X'd one missing, and the undo popped up

this makes the function of the X consistent in both cases ... and a smoother experience for the user

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
