### ISSUE TITLE
Better "refresh"

### ISSUE THREAD

**Issue by pishee** [laurencedawson/reddit-sync-development#603]
For now we have at least three types of refresh.
![image](https://cloud.githubusercontent.com/assets/7676575/3085858/b448d3b6-e51c-11e3-9654-4a680ba0e164.png)

I know the "push to refresh" have some bugs, and maybe for that it's better maintain the "refresh button". But fixing this, perhaps the "circle animation" can be replaced for once by the bars for a more solid design. And removing the "refresh button" it could leave space for another button, let's say a "day/night theme toggle" like [this Gmail mockup](http://www.androidpolice.com/2014/04/02/purported-shots-of-upcoming-gmail-features-show-a-new-ui-pinned-and-snoozed-messages-and-more/) or something else.

*Edit:* Just noted that in the Messages the "push down to refresh" active both refresh bar animations.

**Comment by laurencedawson** [comment]
Fixed with the material design update.
