### ISSUE TITLE
Limit a number of characters in the preview of the Magazine View

### ISSUE THREAD

**Issue by pishee** [laurencedawson/reddit-sync-development#605]
Because subreddits high text-based like [/r/buildapcforme](http://www.reddit.com/r/buildapcforme) can takes up several screens to display a single post.

![image](https://cloud.githubusercontent.com/assets/7676575/3093401/29418434-e5b2-11e3-8b8f-9427c80533ce.png)

From reddit: http://www.reddit.com/r/redditsync/comments/26k937/why_do_some_topics_collapse_in_the_card_view/

**Comment by laurencedawson** [comment]
Merging into #883.
