### ISSUE TITLE
Advanced Post Editor

### ISSUE THREAD

**Issue by pishee** [laurencedawson/reddit-sync-development#606]
From reddit: http://www.reddit.com/r/redditsync/comments/26lwpf/biggest_thing_i_do_miss_from_reddit_news/

* Markdown formatting;
* Ability to add a picture to a comment (like creating a Photo post);
* Preview.

Something like the Evernote buttons?
![image](https://cloud.githubusercontent.com/assets/7676575/3095685/cd58abde-e5ca-11e3-9d68-02fe5f974750.png)

**Comment by laurencedawson** [comment]
This was added in a previous version.
