### ISSUE TITLE
Steam image result in 404 error. 

### ISSUE THREAD

**Issue by aminecmi** [laurencedawson/reddit-sync-development#608]
When opening a steam image like http://cloud-4.steampowered.com/ugc/576771829435544142/2EF496879026D7F8156806FC5A7CC022B05183DD/ I nearly always have a 404 error in the internal browser. 

Sometimes, refreshing resolve the problem, but I didn't find a real solution.

**Comment by laurencedawson** [comment]
Fixed in 10.2.0.

**Comment by sethkinast** [comment]
Doesn't appear to be completely fixed. Running 10.2.6, this post 404s in sync.

http://www.reddit.com/r/warframe/comments/2vjdec/_/

**Comment by laurencedawson** [comment]
Goddamn it was fixed for "steampowered" but not "steamusercontent". Fixed for 10.3.
