### ISSUE TITLE
reddit sync will sometimes load posts from subreddits I don't subscribe to

### ISSUE THREAD

**Issue by RyanMorrison04** [laurencedawson/reddit-sync-development#609]
Tested and reproducible on reddit sync pro 9.0.18.

On occasion, when more posts on the front page are loaded by scrolling down, it will include content from subreddits I don't subscribe to and are not default subreddits. They are not also corresponding with the trending subreddits of the day either. It does not happen every time I use reddit sync, I'd say there's about a 1/5 chance of it occurring though. If I load more posts beyond that, it will also show content I'm not subscribed to. Fully reloading the front page typically resolves it.

**Comment by laurencedawson** [comment]
I think this was fixed after the switch to OAuth.
