### ISSUE TITLE
Reddit Gold icon goes off the screen if flair is too long

### ISSUE THREAD

**Issue by 535A2** [laurencedawson/reddit-sync-development#611]
![](http://i.imgur.com/GVmRnSf.png)

And now the gold icon isn't visible at all. I think it's because it now says "around a day ago" which has pushed the gold icon even further off the screen and is now not visible at all.

Here is the comment where I saw it: http://www.reddit.com/r/writingprompts/comments/2786lw/wp_in_a_world_where_puns_are_illegal_one_man_rises_up_in_opposition/chybk8e

**Comment by laurencedawson** [comment]
Fixed in a previous release.
