### ISSUE TITLE
HTML5 video keeps playing while page is reloaded due to a rotation

### ISSUE THREAD

**Issue by otaconix** [laurencedawson/reddit-sync-development#614]
When viewing a link containing an HMTL5 video, starting the playback of this video, and then rotating your device, Reddit Sync reloads the page, but keeps the video playing back in the background.

This is most noticeable when watching a video with sound. As a user, you're then left with sound in the background, and no way to stop the playback whatsoever.

**Comment by laurencedawson** [comment]
Merging into #884.
