### ISSUE TITLE
Spoilers don't work in previews

### ISSUE THREAD

**Issue by jmriebold** [laurencedawson/reddit-sync-development#616]
When previewing text posts with spoiler tags in them, clicking on the spoiler opens a browser window with the text of the spoiler as the address.

![screenshot_2014-06-14-09-48-46](https://cloud.githubusercontent.com/assets/6983392/3279018/fbd17000-f3e3-11e3-800c-ada91d11a8a1.png)
![screenshot_2014-06-14-09-48-58](https://cloud.githubusercontent.com/assets/6983392/3279019/fe6f06d8-f3e3-11e3-947d-779333a97777.png)

**Comment by laurencedawson** [comment]
This is no longer available a problem as inline text previews are no longer supported.
