### ISSUE TITLE
Remember order when refreshing subreddit list

### ISSUE THREAD

**Issue by ramenchef** [laurencedawson/reddit-sync-development#617]
Everytime I refresh the list of subscribed subreddits, I have to reorder them as they get sorted alphabetically. Is there any chance we could have the app remember the order?

**Comment by laurencedawson** [comment]
Also incorporate:

https://github.com/laurencedawson/reddit-sync-development/issues/971

**Comment by co5mo** [comment]
also can you backup the order of subredits too thanks

**Comment by laurencedawson** [comment]
Added for the next release.
