### ISSUE TITLE
Casual subreddit dropdown to show subscribed subreddits only

### ISSUE THREAD

**Issue by daryndr** [laurencedawson/reddit-sync-development#618]
If I want to view a specific subreddit, I press casual and type for example in the letter 's'. The current dropdown behaviour shows 'sandiego' and 'sanfrancisco' which, while they may be popular, are not 2 subreddits I'm subscribed to or personally would probably ever use. 

It seems more intuitive to me to at least have a menu option where the ONLY subreddits that show in the dropdown are ones I am subscribed to - or possibly have another system that uses this behaviour. Cheers, love the app!

**Comment by laurencedawson** [comment]
I think it would be better to be a mix of subscribed subs and the top available subs. 

Merging with #865.
