### ISSUE TITLE
Settings > Show comment vote numbers

### ISSUE THREAD

**Issue by m-p-3** [laurencedawson/reddit-sync-development#620]
Hi,
since the [reddit announcement](http://www.reddit.com/r/announcements/comments/28hjga/reddit_changes_individual_updown_vote_counts_no/) that upvotes and downvotes aren't available anymore through the API, I don't see any reason for me to have the upvote/downvote values showing up beside each comments. However, I disabled the option but the numbers are still showing up, even after Force Closing the app to make sure it didn't keep the setting in memory for some reason.

Is that what the option is supposed to do, or I'm expecting something else?

**Comment by laurencedawson** [comment]
This has since been removed.
