### ISSUE TITLE
Viewing YouTube video in landscape resets position in submission list

### ISSUE THREAD

**Issue by matthieugrieger** [laurencedawson/reddit-sync-development#622]
Hi!

I've been experiencing this for awhile now and thought I would post it up. Whenever I view a YouTube video in landscape, I am put back to the beginning of the submission list. This does not happen if I keep the YouTube video in portrait. This issue occurs anywhere a YouTube video is viewed in landscape (submissions, comments, etc). 

I'm currently running on Android 4.4.3 on a Nexus 5.

**Comment by machinator2** [comment]
Are you still experiencing this?

**Comment by laurencedawson** [comment]
This should since been fixed with the V11 re-release and the latest betas.
