### ISSUE TITLE
Subreddit wiki links in right sidebar just lead to the subreddit itself

### ISSUE THREAD

**Issue by wafflecopter05** [laurencedawson/reddit-sync-development#627]
There's been a couple self posts about this issue on /r/redditsync (for example: http://www.reddit.com/r/redditsync/comments/25v3ms/_/

If you go to a subreddit like /r/malefashionadvice and click any of the Reddit wiki links in the sidebar, it will just direct back to the subreddit, instead of showing the wiki in the in-app browser.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/reddit-sync-development/issues/405
