### ISSUE TITLE
Comment navigation buttons stop working after 3-4 presses

### ISSUE THREAD

**Issue by matthieugrieger** [laurencedawson/reddit-sync-development#636]
Hi!

So I have been experiencing this bug (or what I assume is a bug) for quite awhile now and I figured I would finally report it. It seems that the comment navigation buttons (which I almost always use, especially in AMAs and AskReddit threads) stop working after a few presses.

Here is a video showing what I mean: https://www.youtube.com/watch?v=1hc8FSYqVak

I am using a rooted Nexus 5 running Kit Kat, using the beta update released today (9.2.0).

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers!
