### ISSUE TITLE
[Enhancement] Clicking a link (ex: YouTube link) inside the in-app browser doesn't invoke app chooser/default app

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#642]
This is annoying for YouTube videos and Google+ albums, which would be so much easier to view in their respective standalone apps instead of in the in-app browser.

**Comment by laurencedawson** [comment]
Since the v11 re-release I've added the ability to whitelist domains so you can force the system to open them in their respective apps.

Cheers!
