### ISSUE TITLE
Suggestion: full height image cards

### ISSUE THREAD

**Issue by ZakTaccardi** [laurencedawson/reddit-sync-development#652]
Currently cards have a max height, so the top and bottom of an image can get cut off. To see the whole image, you have tap to open it, which is an additional step

It would be nice if the whole height of the image could be displayed in the card (as an option).

Dynamically sized large cards would allow the user to continually scroll through the feed without tapping to open a large image, and save time.

**Comment by laurencedawson** [comment]
This is pencilled in for an upcoming release. Cheers.

**Comment by laurencedawson** [comment]
This will be part of the material design second iteration (see #883).
