### ISSUE TITLE
Links with trailing slashes do not open correctly

### ISSUE THREAD

**Issue by Dragory** [laurencedawson/reddit-sync-development#653]
Reddit Sync seems to remove the trailing slash from links you open in the app. Some websites are particularly picky about this, resulting in links not opening properly.

For example, this recent post on r/prisonarchitect:
http://www.reddit.com/r/prisonarchitect/comments/2coxgl/i_dont_think_there_is_a_worse_prisoner_bio_than/

The image link opens properly if you open it in an external browser, but reddit sync results in this:  http://i.imgur.com/huijhnu.png
[(You can see the same page if you go to the URL without the trailing slash)](http://cloud-4.steampowered.com/ugc/38597471949960072/B35DB4386CEBA5EA5A1238455B3CE12F58BC8FDF)

#608 describes the same problem, but I thought I'd make a new issue on what I believe is the root cause.
Further evidence of this behaviour can be seen by comparing the resulting URL of ["Open in Browser" from the list or comment view](http://i.imgur.com/4xrBCsg.png) (url has the trailing slash) and the ["Open in browser" from the in-app browser's menu](http://i.imgur.com/1FgRWDq.png) (url doesn't have the trailing slash).

**Comment by laurencedawson** [comment]
Fixed for the upcoming v11 release.

**Comment by okungnyo** [comment]
For the curious, what was causing this unique issue?

**Comment by laurencedawson** [comment]
I was stripping off the trailing slash for parsing. I've rewritten the
parser to not to this...

**Comment by okungnyo** [comment]
Thanks.
