### ISSUE TITLE
Random native crashes on the web browser

### ISSUE THREAD

**Issue by richardg867** [laurencedawson/reddit-sync-development#657]
Sometimes, the built-in web browser crashes (native crash at Chrome_IOThread) on my Nexus 5 when a link I clicked starts loading. I submit a report every time that happens, and I put my username (/u/RichardG867) in one of them.

**Comment by laurencedawson** [comment]
Is this still the case? Haven't been able to reproduce.

**Comment by laurencedawson** [comment]
Merging into #884.

**Comment by richardg867** [comment]
This was the case back in KitKat, but it somehow fixed itself after a while.
