### ISSUE TITLE
App slows down when post/comments view has many links

### ISSUE THREAD

**Issue by adriantomic** [laurencedawson/reddit-sync-development#659]
If a post or comment section has many hyperlinks (more than 10), the app slows down to a crawl (unable to scroll/swipe) and touch becomes unresponsive for the whole system. I have to restart the app to be able to use it again.

I have an LG G2 with Android 4.4.2.

**Comment by laurencedawson** [comment]
Expanded comments view is disabled as it doesn't perform well. I'd suggest disabling it.
