### ISSUE TITLE
[Bug] (if you scroll down long enough) after a certain amount of pages, posts stop loading 

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#660]
Use case: I like to browse AskReddit by /top/all

What happens: after a certain amount of pages, the loading bar at the bottom still moves, but posts don't load.

What should happen: they should load!

Thanks and please fix this!

**Comment by laurencedawson** [comment]
When this happens reddit is either serving up duplicate posts or no new posts.

**Comment by okungnyo** [comment]
OK thanks for the info.
