### ISSUE TITLE
Cannot access posts in /r/promos

### ISSUE THREAD

**Issue by OneGoodReason** [laurencedawson/reddit-sync-development#661]
Within the app, trying to access posts in /r/promos results in an error. Might be because you cannot directly access /r/promos, but only posts within it. 

An example of a post where this occurs is this: http://www.reddit.com/comments/1pm7ya/if_you_care_about_your_gaming_you_should_care/

**Comment by laurencedawson** [comment]
/r/promos is forbidden so this seems correct.
