### ISSUE TITLE
Truncated post titles in small cards view.

### ISSUE THREAD

**Issue by creisman** [laurencedawson/reddit-sync-development#662]
The small cards view seems to truncate some of the titles. It's fairly frequent, but here's an example.

Small cards view:
http://i.imgur.com/64PuX5x.png
Post view:
http://i.imgur.com/DQR6Dna.png

**Comment by stokholm** [comment]
Still present in 10.6.5: http://i.imgur.com/Klomskz.png

**Comment by laurencedawson** [comment]
Merging into #883.

**Comment by creisman** [comment]
@laurencedawson Can we reopen this? It's still reproducible in v11 :(

http://i.imgur.com/06MVR3G.png
