### ISSUE TITLE
Screen rotation on WebView causes unnecessary reloading

### ISSUE THREAD

**Issue by averageapps** [laurencedawson/reddit-sync-development#670]
Steps to reproduce:
Rotate device while being on a WebView (opened by clicking on a link inside the app).

Expected results:
Activity / Fragment / Views rotate accordingly without destroying WebView contents and reloading page.

Actual results (on Android 4.4.4):
Screen rotates, but WebView seems to restart and reload its content, leading to unnecessary data usage and redraws; scroll position is lost.

Probable Solution:
I assume that you forgot to add a configChanges property in your AndroidManifest.xml somewhere, something like
> android:configChanges="keyboardHidden|orientation|screenSize"

For more details on this (if my assumption is right) see this similar issue: https://github.com/manmal/hn-android/issues/42.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
