### ISSUE TITLE
Crash when trying to read spoiler text

### ISSUE THREAD

**Issue by jcoin** [laurencedawson/reddit-sync-development#671]
In this comment : http://www.reddit.com/r/fantasy/comments/2dsiyt/just_finished_robin_hobb_the_rain_wilds_chronicles_disappointed_in_the_ending_is_this_typical_of_her_writing_spoiler/cjt2q9p

When I click on the first spoiler text, the app crashes (IllegalArgumentException in UriCodec.decode)

**Comment by laurencedawson** [comment]
Fixed but also those spoilers have the wrong format. 

Cheers.
