### ISSUE TITLE
Can't pan around on zoomed in photos normally

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/reddit-sync-development#672]
This is a weird bug. Just zoom into a photo slightly, then try to pan back and forth without lifting your finger (like you can in any other app). You'll have to lift your finger before trying to pan again.

Here is a video of the issue: https://www.dropbox.com/s/duq20mbliuyncsv/SCR_20140828_175728.mp4?dl=0

**Comment by laurencedawson** [comment]
Unable to reproduce.
