### ISSUE TITLE
Long pressing a comment after clicking a link in that comment shows the context menu for that link and not the comment.

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#678]
When viewing a submission with a comment that has a link, click the link to bring it up.  Then close the link and long press the comment with the link (but not the link itself).  Instead of hiding the comment which is the expected behavior, it shows the context menu for the clicked link.

This also happens in self-text posts.

**Comment by laurencedawson** [comment]
Can't seem to reproduce this any more so I'm closing the issue for now.

If you can still make this happen let me know. Cheers.
