### ISSUE TITLE
Specific links don't work when opened

### ISSUE THREAD

**Issue by kbrantley** [laurencedawson/reddit-sync-development#679]
I've encountered several instances where links in either posts or comments don't load properly. I've found two specific examples of this:

* https://www.reddit.com/r/linuxadmin/comments/2huwhd/shamirs_secret_sharing_should_this_be_a_best/ckwaunx

It appears that the apostrophe isn't being encoded properly, breaking the link.

* https://www.reddit.com/r/tf2/comments/2hvgpd/nothing_can_separate_us_scrumpy/

The link in this post has the trailing slash stripped off of it in the actual HTTP GET request. This means that the link being requested isn't the link that was posted, and in this case, it actually breaks the image loading (and 'open in browser' functionality) entirely.

**Comment by laurencedawson** [comment]
Will look into this. Cheers.

**Comment by laurencedawson** [comment]
Fixed for the upcoming v11 release.
