### ISSUE TITLE
Youtube timestamp doesn't work 

### ISSUE THREAD

**Issue by Primeey** [laurencedawson/reddit-sync-development#682]
If you view a video inside Reddit Sync and the OP provided a timestamp the video doesn't start at the timestamp

http://youtu.be/u9_rlCnfigM

**Comment by laurencedawson** [comment]
Correct but the YouTube player is largely broken at the moment and I won't be working on fixing parts my end until Google fixes their end!

**Comment by l3d00m** [comment]
Api for reference: https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer#seekToMillis%28int%29

**Comment by twig** [comment]
Has this been fixed or what exactly is broken on the Google API side of things?

**Comment by okungnyo** [comment]
Lol @l3d00m, I didn't know you were here as well.

**Comment by l3d00m** [comment]
long ago @okungnyo. I was pretty active here and on reddit.

**Comment by okungnyo** [comment]
What made you jump ship?

**Comment by okungnyo** [comment]
And what do you mean "was" pretty active on Reddit?

I just looked you up (copy-pasted your username into 'reddit.com/u/') and you seem pretty active to me.

**Comment by l3d00m** [comment]
Open source is the main reason I gave Slide a try. I stayed at it because it has more features and looks better.

**Comment by okungnyo** [comment]
Yeah, I believe Sync was planned to be open-sourced some day as well...

And my second question?

**Comment by l3d00m** [comment]
I meant that I was pretty active on /r/redditsync. I'm still active on reddit. 

Really? Never heard that one before!

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers!
