### ISSUE TITLE
Opening frontpage's "sidebar" gives your inbox

### ISSUE THREAD

**Issue by The0x539** [laurencedawson/reddit-sync-development#684]
Since the frontpage doesn't have a sidebar, might as well give an easy and glanceable inbox.

**Comment by laurencedawson** [comment]
I've got to disagree on this one. I think maybe it should load trending but not the inbox.

**Comment by The0x539** [comment]
Yeah, I honestly disagree too after this long, but either get rid of being able to open it, or put something there.
