### ISSUE TITLE
coloured cards for images

### ISSUE THREAD

**Issue by snalty** [laurencedawson/reddit-sync-development#686]
Using the palette API on image cards would  be a great way to add some flair to posts.

Google Play movies does this using the poster of a film shown here: 
![image](https://cloud.githubusercontent.com/assets/9409534/4785100/d1b17c18-5d72-11e4-96f9-ab0537fcfe55.png)

**Comment by laurencedawson** [comment]
Looking into using palette in the second iteration of the material redesign (#883).
