### ISSUE TITLE
Problems in landscape

### ISSUE THREAD

**Issue by mikeo562** [laurencedawson/reddit-sync-development#687]
Hi, 
I have a Moto x (2013) completely stock, un-rooted and have problems any time I turn the app into landscape mode. If I am viewing a link and turn it landscape it always reloads the link. The bigger though is that whenever I watch a video and start it in portrait and switch to landscape the video reloads but the audio continues on in the back. Any solutions for this? 
Thanks

**Comment by laurencedawson** [comment]
This has since been fixed with the V11 re-release.
