### ISSUE TITLE
Swiping down from action bar can disable menus

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#688]
Steps to reproduce:

1. View front page
2. Press down on the sort button and swipe down from it. 
3. Raise your finger off the menu to select "Rising" 

Expected: I can tap the sort button and a menu will pop up. 

Actual: The sort button seems to be disabled. No touch indicator or anything.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
