### ISSUE TITLE
App keeps crashing on Start up on nexus 9

### ISSUE THREAD

**Issue by weigel23** [laurencedawson/reddit-sync-development#690]

**Comment by dtseiler** [comment]
Having same problem on Galaxy Note 10.1 tablet. Try to launch Reddit Sync Pro, screen goes black then back to launcher screen saying could not launch.

**Comment by laurencedawson** [comment]
Closing as this was for the builds prior to the v11 re-release. If this is still occurring for anyone please letme know.
