### ISSUE TITLE
Check for ROM enabled on screen navigation bar

### ISSUE THREAD

**Issue by xxdmnxosxx** [laurencedawson/reddit-sync-development#691]
This has been an issue for a long time and I feel as though it should finally be fixed since there have been multiple complaints now that the OnePlus One is gaining popularity. The issue is RS doesn't check for on screen buttons, just whether or not the device is supposed to have them, so none of the OPO users with on screen controls can use the transparent option, they either have to disable or use expanded desktop.  If you find it is too difficult to do or there isn't a library to accomplish this then so be it but a lot of people really want this even if it's a toggle or something.
Edit: wasn't too clear on the issue, it is transparent but everything is behind them, it doesn't move the elements up.

**Comment by laurencedawson** [comment]
I guess this is no longer relevant as transparent browsing is no longer supported.
