### ISSUE TITLE
Some text (primarily links) color breaks on night mode

### ISSUE THREAD

**Issue by creisman** [laurencedawson/reddit-sync-development#692]
Known affected text:
'View more'
Domain names on cards preview
Links in posts
The number of gildings for a post (white on yellow)
Edit for 10.1: Now flair is impossible to read because the background color is gone.

One of the posts pointed out that the link colors match the action bar color. While that's pretty cool, it might be good to have some combinations that aren't allowed and use a default instead (ie, if the action bar is dark in night mode, use blue for links anyway). That should solve the first three instances. The gilding one should probably just always be black text since it's surrounded by the yellow.

Reddit posts:
http://www.reddit.com/r/redditsync/comments/2lxr98/link_cant_be_seen_with_dark_grey_color_scheme/
http://www.reddit.com/r/redditsync/comments/2lx2dk/cant_really_read_the_selected_subreddit/
My own screenshot:
http://i.imgur.com/vVLHjqY.png

**Comment by laurencedawson** [comment]
Merging into #832.
