### ISSUE TITLE
"Group by Subreddit": sort front page items by subreddit of origin

### ISSUE THREAD

**Issue by seascape** [laurencedawson/reddit-sync-development#695]
There's a web browser userscript called Group by Subreddit that rearranges Reddit's front page by grouping all stories from any given subreddit in the same place. Userscript source and screenshot here:

http://userscripts-mirror.org/scripts/show/151561.html
![large](https://cloud.githubusercontent.com/assets/1672115/5059972/2c2538d2-6cec-11e4-8eb8-9f154b4faa14.png)

I honestly find it indispensable for easy and enjoyable browsing of my daily subreddit highlights. No longer having to squint at each story to verify its source -- and constantly switch mental gears based on randomly changing subreddit topic -- greatly eases my browsing. I really miss it in Reddit Sync, and hope you'll consider implementing something similar.

Beyond that, I love RS so far.

**Comment by laurencedawson** [comment]
This would be great but I think it's probably a little out of the scope of Sync.
