### ISSUE TITLE
Ripple issues

### ISSUE THREAD

**Issue by vemacs** [laurencedawson/reddit-sync-development#696]
- Sidebar entries have no ripple, they do on Google apps
- The ripple on messages in Messages goes from the center, not the touch point as it should be
- No ripples on comments in profiles, but there are ripples on posts.
- Trending card is missing ripples on tap, the entries have ripples though

**Comment by laurencedawson** [comment]
Also drawer items.

**Comment by laurencedawson** [comment]
Added for the next release:

- ~~Sidebar entries have no ripple, they do on Google apps~~
- ~~Trending card is missing ripples on tap, the entries have ripples though~~

Still pending:

- The ripple on messages in Messages goes from the center, not the touch point as it should be

- No ripples on comments in profiles, but there are ripples on posts.

http://stackoverflow.com/questions/38625193/how-to-disable-the-android-ripple-effect-for-quick-taps

**Comment by muffinz** [comment]
Long pressing an item in the menu and long pressing an item in the navigation drawer produce different results.

[Picture](http://imgur.com/STNr60u)
- active subreddit item is #EDEDED / #000 7% opacity
- long pressed item in navigation drawer is #E9E9E9 / #000 9% opacity
- long pressed item in three-dot menu is #EBEBEB / #000 6% opacity

**Comment by muffinz** [comment]
related: when long-pressing _Subreddits_ or _Multireddits_ in the navigation drawer, their backgrounds are not aligned (the background is shifted slightly up, clipping into the dividers).

**Comment by muffinz** [comment]
related: add ripples to comments

**Comment by muffinz** [comment]
ripples are missing on recently viewed items in sidebar as well as the close button

**Comment by laurencedawson** [comment]
This has all since been added.
