### ISSUE TITLE
Inconsistent status bar and navbar coloring in comment interface

### ISSUE THREAD

**Issue by vemacs** [laurencedawson/reddit-sync-development#697]
Colors on thread viewing: 

![](http://i.imgur.com/wkPw1ez.png)

Colors on commenting interface (reply to thread or comment):

![](http://i.imgur.com/IeybzCW.png)

**Comment by laurencedawson** [comment]
This is a restriction of using a FragmentDialog for that page. Unfortunately there isn't much I can do.
