### ISSUE TITLE
Cards are not Material-styled

### ISSUE THREAD

**Issue by vemacs** [laurencedawson/reddit-sync-development#698]
Current appearance:

![](http://i.imgur.com/DjbhuPk.png)

White with grey border on bottom.

Expected appearance:

![](http://cdn.androidpolice.com/wp-content/uploads/2014/10/nexus2cee_Screenshot_2014-10-02-11-58-09.png)

Drop shadow on all four sides, Material paper z-layer 1: https://www.polymer-project.org/components/paper-shadow/demo.html

**Comment by laurencedawson** [comment]
This will be part of the second iteration of material design (see #883).
