### ISSUE TITLE
Use ByakuGallery for viewing hires photos

### ISSUE THREAD

**Issue by vemacs** [laurencedawson/reddit-sync-development#699]
Demo: https://play.google.com/store/apps/details?id=com.diegocarloslima.byakugallery.sample&hl=en

Repos (linked in app description): 

https://github.com/diegocarloslima/ByakuGallery

https://github.com/azki/ByakuGallery

**Comment by laurencedawson** [comment]
Switched to using "Subsampling Zoom Image View" instead.
