### ISSUE TITLE
Slug links cause infinite loops when opening in RedditSync

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#700]
Opening the following link with RedditSync prompts me to open it in RedditSync agian

https://www.reddit.com/comments/2fokb2/slug/ckb7lpb

**Comment by laurencedawson** [comment]
Will look into this for the next release. Cheers!

**Comment by laurencedawson** [comment]
These seem to be working fine now so I'm finally closing this issue!

I've also added your example link to the test suite. Cheers!
