### ISSUE TITLE
App doesn't resume via  launcher  icon 

### ISSUE THREAD

**Issue by Flozzo** [laurencedawson/reddit-sync-development#701]
Occurs when I browse a subreddit or comment section, exit the app with the home button and then launch it again with the app icon. Instead of resuming the previous state it resumes to the default screen (frontpage in my case). Using recept apps instead of the launcher  icon it resumes as expected. 
Device is a HTC One M8 running Android 5.0, although there have been reports of this occurring on other devices too.

**Comment by machinator2** [comment]
I believe this has been fixed now.

**Comment by laurencedawson** [comment]
Closing as the latest betas have added a fix.
