### ISSUE TITLE
Frontpage not showing my specified user subreddits

### ISSUE THREAD

**Issue by VorticalBeans** [laurencedawson/reddit-sync-development#702]
My frontpage shows the exact same items as if I was viewing /r/all.

While viewing the Frontpage as a user, my specified subreddits do not show up on the frontpage. I see many subreddits that are not in my user subreddits.

Repro Steps:
1: Sign into a user with custom subreddits.
2: View the frontpage.

Result:
The Frontpage shows the exact same thing as viewing /r/all.

Expected:
The Frontpage shows my custom subreddits only.

**Comment by hacam00** [comment]
I am having this exact same problem. I'm on the newest app version & pro. This is occurring with a brand new reddit account. I have tried refreshing subreddits, refreshing frontpage, rebooting, etc.

**Comment by laurencedawson** [comment]
I've been unable to reproduce this and since switching to OAuth have had far fewer reports. Closing for now but if it happens again let me know!
