### ISSUE TITLE
Fonts and UX

### ISSUE THREAD

**Issue by pull-request-me-your-tits** [laurencedawson/reddit-sync-development#705]
I appreciate your work for the new update. It looks beautiful! I have a feature request though:

If the font in the comments section were changed to dark gray (#303030) the interface would look a lot more paper-esque. 
Also the ability to change the subreddit fragment's font to a lighter weight, or a custom color would make the UX more exciting.

**Comment by laurencedawson** [comment]
I've since added options to change the font and font size everywhere!
