### ISSUE TITLE
Alphabetical Ordering Confirmation

### ISSUE THREAD

**Issue by cmeka** [laurencedawson/reddit-sync-development#707]
Low priority request but it would be an improvement nonetheless.
Add an "Are you sure?" popup when pressing the A/Z button on the subreddit ordering page.
I've pressed it 4 times by accident when I meant to press + to add a subreddit, since they're right next to each other, then have to reorder everything.
As always, keep up the great work and thank you for your awesome app!

**Comment by laurencedawson** [comment]
Added in the upcoming 10.7.10 release.
