### ISSUE TITLE
Upcoming a long post will scroll the post all the way to the top 

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#708]
http://www.reddit.com/r/gaming/comments/2n97b1/_/

Recreate by:

1) Scroll down to see the up vote button for the self text.
2) Up vote the top level post

I expect the up vote button to change colors 

What happens is I get scrolled all the way to the top.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
