### ISSUE TITLE
Load more than 9 child comments

### ISSUE THREAD

**Issue by Gruts** [laurencedawson/reddit-sync-development#711]
[https://www.reddit.com/r/circlejerk/comments/2nuwma/an_ice_cube_after_15_minutes_on_my_keychain/cmh55tf](https://www.reddit.com/r/circlejerk/comments/2nuwma/an_ice_cube_after_15_minutes_on_my_keychain/cmh55tf)

Clicking on load more in the above thread do not bring up any further child comments

**Comment by laurencedawson** [comment]
Pencilled in for the next release.

**Comment by laurencedawson** [comment]
This has since been added. Cheers.
