### ISSUE TITLE
Next comment button issues

### ISSUE THREAD

**Issue by Gruts** [laurencedawson/reddit-sync-development#712]
Scrolling the opening post (link or text) and then the next comment button will cause the first comment to be skipped, jumping directly to the second one.

Using the next comment button tend to skip parent comments that do not have any child comments. Original issue was reported [here](https://github.com/laurencedawson/reddit-sync-development/issues/390) but marked as fixed in v9. This issue is still present in v10.0.7.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
