### ISSUE TITLE
Pressing hardware menu button causes Reddit Sync to crash

### ISSUE THREAD

**Issue by anonymous-user** [laurencedawson/reddit-sync-development#713]
According to this: https://code.google.com/p/android/issues/detail?id=78154

It seems to affect LG devices running Android 4.1. Currently Reddit Sync does show the three-dot icon so I can still access the menu. I would appreciate if the crashes could be avoided if I ever accidentally press the button though.

**Comment by laurencedawson** [comment]
Pencilled in for the next release.

**Comment by laurencedawson** [comment]
Closing as I've been unable to reproduce this issue and the button has since been removed.
