### ISSUE TITLE
[Request] Font color for self posts

### ISSUE THREAD

**Issue by anonymous-user** [laurencedawson/reddit-sync-development#714]
Currently it is a grey color but I would like it to be the same color as the comments (black or white) to provide better contrast.

I've also seen a request to make the comment text grey however. To make both sides happy perhaps you can offer an option to set your own color for the text?

**Comment by Feltzer** [comment]
I agree. This is a severe accessibility issue. The low contrast makes self posts very hard to read. It's also inconsistent seeing how grey is used to signify read content in other parts of the app. If the color choice is meant as a way to differentiate between the self post and its comments then I have to point out that the different fonts are already taking care of that.

**Comment by laurencedawson** [comment]
This has since been changed.
