### ISSUE TITLE
Better Search functionality

### ISSUE THREAD

**Issue by orayzio** [laurencedawson/reddit-sync-development#715]
I suggest the following features be added:
1. Saved searches, including the ability to selectively delete search history
2. Ability to modify current search. If you mistype a search term, you have to retype the whole search to. The interface should allow you to edit your current search to get better results. Also, if you select a search from your search history, you should also be able to edit that search.

**Comment by machinator2** [comment]
The second request has now been implemented.

**Comment by laurencedawson** [comment]
Added 1.
