### ISSUE TITLE
Can't "full-screen" videos in the in-app browser

### ISSUE THREAD

**Issue by orayzio** [laurencedawson/reddit-sync-development#716]
If you use the in-app browser to open a page that has an embedded video, the embedded player will show the full-screen icon in the lower-right corner, but clicking it won't do anything.

**Comment by laurencedawson** [comment]
Merging with #884.

**Comment by laurencedawson** [comment]
Unmerging and re-opening as theres an issue with Lollipop hiding the fullscreen videos...

**Comment by laurencedawson** [comment]
With the addition of Chrome Custom Tabs I'm closing this issue. 

I strongly recommend using CCT over the WebView as it solves all of the common issues with the WebView.
