### ISSUE TITLE
App loads defaul subreddits after first chuck of pages

### ISSUE THREAD

**Issue by TeutonJon78** [laurencedawson/reddit-sync-development#717]
When I go into the app or refresh, it will load the correct subreddits that I've subscribed to.

After that I get to the bottom and it loads the next batch of pages, it tends to load the default subreddits rather than mine. This is only started to happen in the last release or two.

I'm current running 10.0.5.

**Comment by laurencedawson** [comment]
Is this still happening? After the switch to OAuth the number of reports went down significantly. Cheers.

**Comment by laurencedawson** [comment]
Closing for now unless this happens again.

**Comment by TeutonJon78** [comment]
I haven't had it happen in awhile, at least not since the bigger overhaul.
