### ISSUE TITLE
Links in night mode are white and hard to see

### ISSUE THREAD

**Issue by epidemicz** [laurencedawson/reddit-sync-development#720]
Previously, links in night mode were colored blue and you could easily locate them in a large block of text.  Currently, they are white which makes them harder to see.  I believe the same is also true with the "View More" option.

Here's an example:
http://imgur.com/hKowXZX

**Comment by lachieh** [comment]
OP names are hard to differentiate also. Night mode doesn't have to mean monochromatic. There's so many threads on reddit and bug posts on here that I'm surprised there's not a response about it yet.

**Comment by laurencedawson** [comment]
Fixed in 10.3.7.
