### ISSUE TITLE
Sharing a link comment has no content

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#723]
Steps to reproduce:

1. View a comment with a link in it
2. Long press the link (the text not the handle)
3. Press "Share Link"

Expected:

I can copy to clipboard, send a text, etc. 

Actual result:

I have all those options but they do nothing. The textual content is empty.

Probably related to #722

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
