### ISSUE TITLE
Viewing a message in your inbox does not mark the message as read

### ISSUE THREAD

**Issue by MKorostoff** [laurencedawson/reddit-sync-development#724]
Steps to reproduce:
1. Login to reddit on the desktop website (we'll call this "account A")
2. Leave a comment on any post
3. Logout of account A.
4. Login to an alternate account (account B)
5. Leave a reply to the comment left in step 2 above
6. From your cell phone, login to account A with reddit sync.
7. See that you receive a notification of a new message.
8. View the notification.
9. Login to account A on the desktop website.
10. See that you still have an orangered, despite having already viewed the message in reddit sync.

**Comment by jellyberg** [comment]
You have to tap on the message in your inbox in Reddit sync to mark it as read.

**Comment by laurencedawson** [comment]
Viewing doesnt but tapping on a message marks it as read. I'll be adding a "mark all as read" button too.
