### ISSUE TITLE
[Request] Support for tables

### ISSUE THREAD

**Issue by Peteriscool** [laurencedawson/reddit-sync-development#727]
Certain subreddits like /r/GameDeals make extensive use of tables. In Reddit Sync you are not able to view these tables as you do on desktop. Instead of seeing a proper table you get to see what looks like the original formatting. I'd like to see this feature added.

**Comment by jmouer** [comment]
See https://github.com/laurencedawson/reddit-sync-development/issues/260

**Comment by laurencedawson** [comment]
Duplicate.
