### ISSUE TITLE
App overheating phone, forcing the phone to reboot - since 10.1

### ISSUE THREAD

**Issue by TiboQc** [laurencedawson/reddit-sync-development#728]
Since version 10.1, at least on Cyanogenmod 11, the phone overheats and reboots after using the app. See thread here: http://www.reddit.com/r/redditsync/comments/2qphnc/

By buying the ad-free version, the issue seems to have stopped.

The last 100 lines of logcat before the phone crashed can be found here: https://drive.google.com/file/d/0Bwn6_yXvC2JzQjBwSmcxUXNyNms/view?usp=sharing

BTW, I have the full logs from app opening to crash if you want, it's only ~840kB

Thanks,

**Comment by laurencedawson** [comment]
This should have been fixed with the latest release. Cheers.
