### ISSUE TITLE
Swipe left/right to upvote/downvote [Feature Request]

### ISSUE THREAD

**Issue by hroyer** [laurencedawson/reddit-sync-development#734]
Title is self explanatory. Being able to upvote or downvote a post or comment by swiping left or right *à la* Google Inbox.

**Comment by jellyberg** [comment]
This would be so nice.

**Comment by laurencedawson** [comment]
Swiping to vote will not be part of sync any time soon as this is reserved for navigation between activities. 

Cheers.
