### ISSUE TITLE
Option to include Title when sharing a link

### ISSUE THREAD

**Issue by zsection** [laurencedawson/reddit-sync-development#736]
Not being able to easily share a link WITH its title to Twitter / Facebook etc. By sharing just the link(as it is now) we're forced to think up a title or find a way to copy the title (which appears impossible in the app). 

Would REALLY appreciate you adding this OR at least an easy way to copy/paste the title of the share.

**Comment by laurencedawson** [comment]
Duplicate, merging with:

https://github.com/laurencedawson/reddit-sync-development/issues/450
