### ISSUE TITLE
Action Bar Colors

### ISSUE THREAD

**Issue by tehdef** [laurencedawson/reddit-sync-development#740]
As a Reddit Sync user I noticed Action Bar colors in the settings menu are labeled as "Play Movies Red" etc, but do not actually match the new material design color palette that the apps are using.

http://www.google.com/design/spec/style/color.html

It seems beneficial to have the current colors updated to better reflect the intended app, while also expanding the colors to include some of the more vibrant choices for user preference.

**Comment by laurencedawson** [comment]
Fixed in 10.3.7.
