### ISSUE TITLE
Auto Night Mode breaks at midnight if starting time is before midnight

### ISSUE THREAD

**Issue by realrage** [laurencedawson/reddit-sync-development#748]
Start time - 18:00
End time - 06:00

Feature works until midnight, and then switches off Night Mode at midnight.

**Comment by m-p-3** [comment]
Just tested this last night, I indeed got blinded by the thousand suns of the light theme at 1AM.

**Comment by linuxman94** [comment]
This does not occur when the start time is set to midnight (0000) or later. If the start time is before midnight then it always reverts to day mode at midnight

**Comment by realrage** [comment]
Looks like it necessarily wants current time to be greater than start time, which would fail after midnight. This could be fixed by checking whether ((current time > start time) OR (current time < end time)).

I may be wrong about this because I haven't seen the source code.

**Comment by realrage** [comment]
Ay, there's all sorts of fail in the second part of the check I suggested in my previous comment. Please ignore.

**Comment by laurencedawson** [comment]
Merging into the master night mode issue.

#832
