### ISSUE TITLE
Imgur gifv do not play from Smaller Cards post list

### ISSUE THREAD

**Issue by rebug** [laurencedawson/reddit-sync-development#751]
When viewing Smaller Cards, any imgur gifv will not load unless I open the post, then tap the preview. I get an "Image failed to preview" toast. 

I do not have this problem when using Small Cards or Cards view. 

Reddit Sync Pro 10.2.6 / Android 5.0.2 on a 2013 Nexus 7.

**Comment by rebug** [comment]
Working great with 10.4.2! Thanks for the fix.

**Comment by rebug** [comment]
As of 10.6.5, Imgur gifv do not play from Small Cards view. I get no error message.

**Comment by laurencedawson** [comment]
This was fixed in the latest update (10.7.7).
