### ISSUE TITLE
I'm getting really large cache sizes lately, upwards of 1.4 GB before I cleared it

### ISSUE THREAD

**Issue by jellyberg** [laurencedawson/reddit-sync-development#753]
I probably should have taken a screenshot before I cleared it but ah well. 

Having such a large cache size seems to somehow cause other background processes like a Tasker and Gravity Screen to shut down, which is a really big deal. .

It seems to occur most often when browsing new subreddits (especially when sorting by top:all possibly or that might just be confidence).

Cheers.

**Comment by laurencedawson** [comment]
I've added additional steps to ensure the cache is fully cleaned in 10.3.8.
