### ISSUE TITLE
Long post flairs sometimes hide other post info (submission time, subreddit etc).   

### ISSUE THREAD

**Issue by jellyberg** [laurencedawson/reddit-sync-development#758]
http://imgur.com/mDJgDjR

**Comment by jellyberg** [comment]
Sorry for dumping all this at once Lawrence, I just came across this issue tracker and thought and dump all my pretty peeves. Love the app!

**Comment by laurencedawson** [comment]
Ah this is a duplicate bug and will be fixed in the material 2.0 redesign. Thanks for taking the time to submit though!
