### ISSUE TITLE
imgur.com/gallery/*/new links direct to gallery/new instead

### ISSUE THREAD

**Issue by blueshiftlabs** [laurencedawson/reddit-sync-development#759]
Some imgur gallery links are posted in this format:

http://imgur.com/gallery/hc9ikhF/new

The `/new` on the end doesn't appear to affect anything on imgur's side, so it just displays the image page as normal.

However, Sync displays a different link:

http://imgur.com/gallery/new

This causes the image to not open in the in-app imgur viewer. Using the "Open in Browser" option doesn't work either, as the URL opened is the same `/gallery/new` link, rather than the permalink to the actual image.

[Here's an example of a post with this issue.](https://www.reddit.com/r/Portal/comments/2w1u47/are_you_still_there/)

This is present in at least 10.2.6 - I haven't checked other versions.

**Comment by nguyenmp** [comment]
I reported this in #747 and @laurencedawson commented that it is fixed in 10.3.0.

**Comment by laurencedawson** [comment]
This has been fixed in the latest builds.
