### ISSUE TITLE
Weird drop shadow with in-app browser

### ISSUE THREAD

**Issue by vemacs** [laurencedawson/reddit-sync-development#761]
The drop shadow/progress bar in the in-app browser does not have a transparent background, resulting in it looking weird on non-white pages. Talon's built in web browser does not have this problem, it has a proper drop shadow.

**Comment by vemacs** [comment]
Sync: ![](http://i.imgur.com/tUFlnN1.png)

Talon Pro: ![](http://i.imgur.com/sCoefLd.png)

**Comment by laurencedawson** [comment]
Fixed in 10.5.
