### ISSUE TITLE
You cannot swipe away the sidebar of a subreddit you're not subscribed to without leaving the subreddit itself. 

### ISSUE THREAD

**Issue by HyvelTjuven** [laurencedawson/reddit-sync-development#765]
When trying the subreddit also disappears. 
https://i.imgur.com/ptp3xiI.jpg

**Comment by agret** [comment]
Duplicate, I submitted same thing 7hrs before yours and is the issue directly below this so would've been top of page when you came here. 

https://github.com/laurencedawson/reddit-sync-development/issues/764

**Comment by laurencedawson** [comment]
Duplicate.
