### ISSUE TITLE
Edit subreddit names in our subreddit list

### ISSUE THREAD

**Issue by pjjanak** [laurencedawson/reddit-sync-development#768]
It would be nice if we were able to edit the entries in our subreddit list so if we misspell something or want to add a filter to /r/all we don't have to delete and re-add the item. Obviously it's just a minor annoyance, but it would be nice.

**Comment by laurencedawson** [comment]
I think for now I'm going to close this but might revisit it again. Thanks for taking the time to report this issue and for contributing to sync :)
