### ISSUE TITLE
[Feature Request] Hide all child comments

### ISSUE THREAD

**Issue by ZealousEar** [laurencedawson/reddit-sync-development#769]
Like in RES, you can hide all comments which aren't top level making it much easier to read.

Example:
Child comments not hidden: https://i.imgur.com/Q1HExns.png
Child comments hidden: https://i.imgur.com/vPK1Oud.png

**Comment by laurencedawson** [comment]
Pencilling in for the v10.8 release.

**Comment by laurencedawson** [comment]
This has since been added. Cheers!
