### ISSUE TITLE
Phone slows down to a crawl when downloading images

### ISSUE THREAD

**Issue by nmoorthy1** [laurencedawson/reddit-sync-development#774]
Using a Nexus 5 running stock 5.0.1, just as the title implies, whenever I download an image with reddit sync, it causes the phone to lag like crazy. Here is a video of it in action: https://www.youtube.com/watch?v=2yBD55oidvw

Reddit Sync Pro version 10.2.6

**Comment by laurencedawson** [comment]
This has since been fixed.
