### ISSUE TITLE
Only show subscribed subreddits in the 'view subreddit' autocomplete dropdown

### ISSUE THREAD

**Issue by scottrrr** [laurencedawson/reddit-sync-development#776]
I don't really understand the current system. I browse /r/headphones several times a day via Sync and I have to type out the whole subreddit each time I navigate to it, while it shows /r/health and /r/heavymind in the autocomplete dropdown - 2 subreddits I don't subscribe to nor have ever even visited! That's only one example by the way, it does the same with many other popular subreddits and I'm sure almost everyone has noticed this particular behaviour themselves.

I really love this app but I feel like this current system is peculiar and takes away from the usability Sync as a whole. Thank you.

**Comment by laurencedawson** [comment]
Subscribed subreddits have been added for the upcoming release however I think other subs should also remain.
