### ISSUE TITLE
[Non-critical bug] Capitalization inconsistency in overflow context menu for posts

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#781]
[Share | View Profile | View Subreddit | Open in Browser | Copy text | Report]

would be more consistent with the rest of the app, if de-capitalized to:

[Share | View profile | View subreddit | Open in browser | Copy text | Report]

**Comment by laurencedawson** [comment]
Fixed in 10.7.8. Cheers!

**Comment by okungnyo** [comment]
Thank you!
