### ISSUE TITLE
[Non-critical bug] Manually-added subreddits should be automatically capitalized too, not just synced subreddits

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#785]

**Comment by laurencedawson** [comment]
If a user subscribes to "android" this is then returned later if they refresh their subreddits. Ideally reddit should captialise this to "Android". As I can't work out how to capitalise the subreddit I'm going to close this issue for now.

**Comment by okungnyo** [comment]
Yeah, it's a very minor issue. No biggie!
