### ISSUE TITLE
[Feature request] Ability to mark a post as unread

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#786]
For when you accidentally click a post that you want to read later, or when you want to come back to a post later when it has more replies.

**Comment by laurencedawson** [comment]
This is something that is not a feature on reddit and something I don't really think should be part of the app. In the use case described you'd be better upvoting / saving rather than marking as unread.

**Comment by okungnyo** [comment]
Sorry.
