### ISSUE TITLE
[Feature request] Show the [Profile > Saved/Comments/Submitted/Liked/Disliked/Hidden/Saved] sub-menus in the navigation drawer (example, how Inbox does it: http://imgur.com/a/g1Joi)

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#792]
http://imgur.com/a/g1Joi

**Comment by laurencedawson** [comment]
That album is empty. Would you mind reuploading? Cheers.

Moving to blocked until then.

**Comment by thang1thang2** [comment]
Just for the sake of discussion, here's how Inbox's sidebar looks right now. [Inbox sidebar on the desktop](http://img.wonderhowto.com/img/original/34/98/63549758230225/0/635497582302253498.jpg), and [Inbox sidebar on android app](http://img.wonderhowto.com/img/original/48/12/63549758223553/0/635497582235534812.jpg)

**Comment by okungnyo** [comment]
Yes, thang1thang2 cleared it up.

Basically, it would be great if we could access [Saved/Comments/Submitted/Liked/Disliked/Hidden/Saved] directly from the navigation drawer without any extra steps.

**Comment by laurencedawson** [comment]
Added for the next release. Cheers.
