### ISSUE TITLE
[Critical bug] Links in Imgur album descriptions should be clickable

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#793]

**Comment by laurencedawson** [comment]
Added to the upcoming v10.7.8 release. Thanks again for submitting. If you're ever in London I think it's only right I buy you a beer...

**Comment by okungnyo** [comment]
Oh. I should be the one thanking YOU for being so receptive to feedback.

You are a great developer and I hope you live a long and happy life!
