### ISSUE TITLE
[Feature request] Material toolbar color picker (http://i.imgur.com/NHvxcgp.png)

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#794]
http://i.imgur.com/NHvxcgp.png

**Comment by laurencedawson** [comment]
Pencilled in for the v10.8 release.

**Comment by okungnyo** [comment]
It will be quite a sight to behold, I'm sure!

**Comment by muffinz** [comment]
Related: Phonograph's [colour picker](http://imgur.com/a/qJOQD)

**Comment by laurencedawson** [comment]
Added for V12.1 and should make the first beta today.
