### ISSUE TITLE
[Feature request] Ability to switch (novelty) accounts on the fly to reply to a comment, without reloading everything (ex: Alien Blue)

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#795]

**Comment by CorruptedMinds** [comment]
Also useful in this request would be the ability to:
1: Switch back to original account after posting
2: Stay logged in to new account.

This makes it easy to comment as a novelty or business account in a post without having to reload everything and then find the original post.

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by okungnyo** [comment]
This will give Sync the edge over other Android apps, IMO, with an easily-explainable killer feature to tell people about.

I will wait patiently for the day it arrives!

**Comment by laurencedawson** [comment]
So I'm going to close this issue as I've since added the ability to change the current user when posting comments or sending messages.
