### ISSUE TITLE
[Feature request] Separate font size settings for post titles and comments

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#803]

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by okungnyo** [comment]
It's not that serious of an issue actually, I don't know why I submitted this!

**Comment by machinator2** [comment]
Might be worth implementing though; there have been several requests for this: https://www.reddit.com/r/redditsync/comments/382i9o/how_to_change_comment_font_size_without_changing/
https://www.reddit.com/r/redditsync/comments/362omw/font_size_options/

**Comment by machinator2** [comment]
And another: https://www.reddit.com/r/redditsync/comments/3q44tk/font_size_for_comments/cwoo5vx?context=3

**Comment by laurencedawson** [comment]
This has been added in the latest beta.
