### ISSUE TITLE
[Feature request] Drafts hub

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#804]

**Comment by laurencedawson** [comment]
Pencilled in for the next full release.

**Comment by okungnyo** [comment]
Good to hear!

It would be great if it worked in an automatic fashion.

Like, if the app detects that the post/comment failed to go through (error, Internet connection lost, "doing that too much", etc.) then it automatically saves the text as a draft.

Otherwise, I think it would be too much of a hassle and it would be better to just use Google Keep or something.

Thanks.

**Comment by laurencedawson** [comment]
Added for 12.6 (beta 1).
