### ISSUE TITLE
[Feature request] Web-browser-like tabs

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#805]

**Comment by laurencedawson** [comment]
This is something I won't be planning on adding. You'd be better off unchecking handle all other links and using chrome at that point...

**Comment by okungnyo** [comment]
Oh no, I meant tabs to browse multiple Subreddits, not tabs to browse webpages.

Sorry about the confusion.

Would you still consider it? Or would that make the app too convoluted?

**Comment by okungnyo** [comment]
Oh no, I meant tabs to browse multiple Subreddits, not tabs to browse webpages.

Like for example: when browsing /r/SubredditDrama which has a ton of links to other posts, it would be great to have those other posts open in the background to read later while you continue reading the post.

Does that change how you view the feature? Or would that make the app too convoluted?

Sorry about the confusion.
