### ISSUE TITLE
[Feature request] Threaded messaging

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#806]
Maybe one day, because it's not possible with the current API?

**Comment by laurencedawson** [comment]
Pencilled in for an upcoming release.

**Comment by okungnyo** [comment]
Wow, I'm happy to hear that!

Although I swear I remember reading that this wasn't possible with the current API?

But I'm not complaining, thanks!

**Comment by laurencedawson** [comment]
Merging:

https://github.com/laurencedawson/reddit-sync-development/issues/719
