### ISSUE TITLE
[Non-critical bug] Some pics can only be zoomed a little bit, or not at all (http://i.imgur.com/Te0WuIB.jpg)

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#815]
http://i.imgur.com/Te0WuIB.jpg

**Comment by laurencedawson** [comment]
Images can now be zoomed up to 25x with deepzoom enabled in the upcoming 10.7.8 release.

**Comment by okungnyo** [comment]
Awesome. Just awesome.

Thanks a lot.

**Comment by okungnyo** [comment]
Awesome. Just awesome.

There is no other word to describe the work you are putting into Sync.

Thanks a lot.
