### ISSUE TITLE
[Feature Request] Gallery Interface Material Housing Updated

### ISSUE THREAD

**Issue by tehdef** [laurencedawson/reddit-sync-development#817]
Looking over the Gallery, it suffers from 2 visual problems at the moment. 

1. Is the overall look. A more material look is in line Example: (http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7SlR2OWd6Z1ZhVzA/layout_structure_sidenav_structure2.png)

2. The gallery currently has a very jarring load in animation that is not in line with the material animations.   Example: (http://www.google.com/design/spec/animation/meaningful-transitions.html#meaningful-transitions-visual-continuity) under continuation segment of the page, you'll see 2 videos. The Don't example is how the gallery currently functions. 

Looking for this to be the start of what I feel is proper material implementation to begin the kickoff for more animations from the guidelines to make it into Sync.

**Comment by laurencedawson** [comment]
Pencilled in for the next release.

**Comment by laurencedawson** [comment]
I'm going to close this for now as there's been lots of visual changes since this was reported but feel free to comment or reopen it with new suggestions. 

Cheers!
