### ISSUE TITLE
Subreddit sidebar should slide under the status bar

### ISSUE THREAD

**Issue by vemacs** [laurencedawson/reddit-sync-development#819]
Left sidebar (correct): 

![](http://i.imgur.com/y69viu1.png)

Subreddit sidebar (incorrect):

![](http://i.imgur.com/vA7KCFx.png)

**Comment by FirestarPwns** [comment]
I also think you should get the header image and display it at the top of the sidebar for a subreddit.

**Comment by laurencedawson** [comment]
According to the material design guidelines, only the left drawer should go under the status bar.
