### ISSUE TITLE
FAB - different actions

### ISSUE THREAD

**Issue by LeonSolmyr** [laurencedawson/reddit-sync-development#820]
Hi,

I'm a long time Reddit reader, but almost never a writer, so I don't have any use for current FAB "post new" action. 
According to Material Design philosophy FAB should be used for most used action per site, and for me it is "sorting".

What I would love to have as a new feature is ability to chose what action is default for FAB ("write", "sort", "chose subreddit").

Secondary, I'd like to have an ability to hold FAB for different uses mentioned above. Expanded FAB if You like.

I hope You like this idea and can implement it in future. 
It does not hurt any UI design choices You've made so far, and give end user options to freely choose action they prefer.

**Comment by laurencedawson** [comment]
It might be a little overkill but you can disable the fabs altogether (Settings > General).
