### ISSUE TITLE
Pressing the back button when viewing subreddit sidebar closes the subreddit

### ISSUE THREAD

**Issue by jellyberg** [laurencedawson/reddit-sync-development#824]
Expected behaviour: close the sidebar alone.

**Comment by creisman** [comment]
This is also true when viewing a page in the webview with the new '[BETA] Load post content' option enabled.

**Comment by laurencedawson** [comment]
Noted and added to the backlog. Cheers.

**Comment by laurencedawson** [comment]
This has been fixed for the upcoming v10.7.8 release. Thanks for the report.

**Comment by FirestarPwns** [comment]
Is this the same for [BETA] Load post content? It was my only issue with it?

From,
    Owen
