### ISSUE TITLE
Pull-to-refresh doesn't clear unread messages

### ISSUE THREAD

**Issue by Nxt3** [laurencedawson/reddit-sync-development#826]
If you go to the inbox and in the spinner, select "Inbox Unread", then read everything--when you pull to refresh, the messages aren't cleared. Pressing the refresh button in the actionbar does work as intended.
![screenshot_2015-03-03-20-27-31](https://cloud.githubusercontent.com/assets/2940826/6476481/3e27df88-c1e4-11e4-9cc2-7fb2ab25562e.png)

**Comment by laurencedawson** [comment]
Noted. Thanks.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
