### ISSUE TITLE
Ability to change the color and enable/disable the new Submit button

### ISSUE THREAD

**Issue by heath1024** [laurencedawson/reddit-sync-development#827]
I'm very picky about my color combinations and the inability to determine the color of this new icon in the bottom right, http://imgur.com/nbbN9nQ (or at least be able to disable it) drives me crazy! I imagine this isn't a big deal to fix but it would be a feature to include that I am surprised already isn't.

**Comment by FirestarPwns** [comment]
You can disable it.

**Comment by laurencedawson** [comment]
Added to the backlog. You can already disable it though. Look under "general" in the settings.
