### ISSUE TITLE
[Critical bug] Images are downloaded each time they are viewed

### ISSUE THREAD

**Issue by TaylorSanchez** [laurencedawson/reddit-sync-development#828]
At first I though they were only loaded twice, but it seems the app will continually re-download images. This happens whether I have "Prefetch images" option off or on. I have already attempted a clear cache, clear settings, uninstall, reboot, hard reboot, etc.

Reddit link: http://www.reddit.com/r/redditsync/comments/2y6nxu/preload_images_download_again/ 

Temporary work around is that you can turn off data and the images will use the cache, otherwise the app will download the image again.

**Comment by TaylorSanchez** [comment]
Regarding the screenshots in the reddit link: The numbers near the top of my screen come from a Network Monitor Mini app. The number on the left is download, the right is upload. That is what first alerted me to this problem.

**Comment by laurencedawson** [comment]
Still can't actually replicate this issue. If you grab the latest version, you can check the debug log to see exactly what is happening.

**Comment by TaylorSanchez** [comment]
Fixed with latest update. Sorry should have put that in the bug report, not
just the reddit Post

**Comment by laurencedawson** [comment]
No worries, glad it's sorted!
