### ISSUE TITLE
Image Failed To Preview in List View

### ISSUE THREAD

**Issue by jthieling** [laurencedawson/reddit-sync-development#829]
This issue has existed for quite awhile, but seems to have gotten worse recently.

When you enable 'Images' in Link Handling settings and you try to open an image from List View, 80%+ of the time you will get the "Image Failed to Preview" toast. This is using the Beta channel on a Note 4.

Thanks for looking into it, Lawrence. 

JT

**Comment by laurencedawson** [comment]
80% of all images or just gifs? cheers

**Comment by jthieling** [comment]
It seems to be limited to gifs/gif variants. I just spent 6-8 minutes testing just now, so not an exhaustive study by any stretch.

Let me know if you need anything else.

Thanks!

John

**Comment by laurencedawson** [comment]
Thanks, I'll look into this.

**Comment by laurencedawson** [comment]
This has been fixed in 10.7.2.
