### ISSUE TITLE
Night Mode tweaks

### ISSUE THREAD

**Issue by miladmaz12** [laurencedawson/reddit-sync-development#832]
https://imgur.com/yrMvN75

a) the drop down menu is holo not material. Reddit is fun has a similar drop down menu that is already materialized. 
b) the comment and link karma are grey instead for white.

**Comment by laurencedawson** [comment]
a. This is an issue with the support lib
b. Will look into this. Cheers

**Comment by SharpMelon** [comment]
I browsed through the previous issues that were closed but didn't find one that matched this:

![](http://cactus.rocks/Screenshot_2015-05-09-22-53-21.png)

**Comment by laurencedawson** [comment]
This has since been fixed with the v11 release. Cheers.
