### ISSUE TITLE
Implement a small indicator as to when the content / subreddit etc was last refreshed.

### ISSUE THREAD

**Issue by twizzlebizzle** [laurencedawson/reddit-sync-development#833]
It's sometimes nice to know when it was last refreshed, especially if it was a while ago refreshing is going to replace all the content you can see and you're going to pretty much lose everything else there, also saves data if it was done only 5 mins ago.

Not an issue per se, but something small which I think would be a good addition :)

**Comment by FirestarPwns** [comment]
Settings ⇒ Posts ⇒ Uncheck Hide NSFW Card Previews

**Comment by laurencedawson** [comment]
Added to the backlog. Cheers.

**Comment by laurencedawson** [comment]
After reviewing this ticket I won't be adding this in but thanks for the report.
