### ISSUE TITLE
[Feature Request] Transparent Nav Bar

### ISSUE THREAD

**Issue by schott12521** [laurencedawson/reddit-sync-development#836]
I think the option to have a transparent nav bar would be awesome. I don't know if I'm recalling this correctly but Lawrence but have said this was against the Design Guidelines, so maybe make it a hidden option that users have to seek out or something?

**Comment by laurencedawson** [comment]
Added to the backlog. Cheers.

**Comment by laurencedawson** [comment]
I'll look into this as part of the second iteration of the material redesign (#883).
