### ISSUE TITLE
[Feature request] resume where you left off on another device

### ISSUE THREAD

**Issue by osnapitsjoey** [laurencedawson/reddit-sync-development#837]
Maybe make a pop up show up asking if you want to start fresh or continue where you left off.

**Comment by laurencedawson** [comment]
Sorry this isn't on the roadmap for Sync.

**Comment by osnapitsjoey** [comment]
I didn't think so, but you told me to out it here just to be safe.

**Comment by laurencedawson** [comment]
Thanks anyways!
