### ISSUE TITLE
Can't submit top level comments on a tablet with FABs disabled. 

### ISSUE THREAD

**Issue by ollien** [laurencedawson/reddit-sync-development#841]
![screenshot_2015-03-22-13-18-32](https://cloud.githubusercontent.com/assets/977151/6770437/209ec434-d096-11e4-991f-fbab7f680b6b.png)

**Comment by laurencedawson** [comment]
Have you tried clicking on the overflow menu top right?

**Comment by ollien** [comment]
I'm blind. Didn't see that. Could we move that into the action bar?

**Comment by laurencedawson** [comment]
Perhaps!
