### ISSUE TITLE
Reddit Sync using lots of background data in one day

### ISSUE THREAD

**Issue by ColossalChaz** [laurencedawson/reddit-sync-development#843]
At the start of today I had ~200mb remaining on my monthly data plan, however by the end of the day I got a text telling me I had used it all up, which could not have been possible as I had barely used the internet. However when i looked in the data usage, I noticed that Reddit Sync had spiked in background data use for the one day, using 175mb in one day whilst the foreground data was only 19.02 mb. This is quite an annoyance as it now means that I wont be able to use mobile data until the 4th of april..

Do you have any idea why this may have happened, for the record i used the app on mobile data for about 20 minutes in the morning but that was it. Please see the attached images of my data usage for reference.

![screenshot_2015-03-24-15-51-17](https://cloud.githubusercontent.com/assets/11633664/6806444/ab216afc-d240-11e4-8582-c1af68e0a672.png)
![screenshot_2015-03-24-15-50-10](https://cloud.githubusercontent.com/assets/11633664/6806446/ae881d62-d240-11e4-958f-aabedd15f65f.png)

**Comment by laurencedawson** [comment]
This is very odd. Any chance you had literally thousands of messages that day?

**Comment by ColossalChaz** [comment]
Hello, my apologies for the long time replying to this. No I didn't
actually receive any emails, which makes this all the more odd... I just
the app as normal for probably  about a total of 20-30 minutes during the
day.
