### ISSUE TITLE
Menu button doesn't open overflow menu in webview

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#844]
Version 10.5.4 with AOSP 5.0.1 on a Samsung S4 Developer Edition.

1. Open this link in Sync for Reddit. http://www.reddit.com/r/androiddev/comments/305k8o/_/

2. Click the link to open it in the in app browser/webview

3. Press the hardware menu button. 

I expect the menu to show up but it doesn't.

Note, I do have overflow menus forced on.

**Comment by laurencedawson** [comment]
Will look into this for the next release.

**Comment by laurencedawson** [comment]
I've since switched to chrome custom tabs over webviews and Android has started to ditch the hardware menu buttons.
