### ISSUE TITLE
Editing a comment doesn't properly unescape greater than characters 

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#845]
Comment on something and include a quote:

> like this

When you edit it, it'll appear

&gt; like this

**Comment by nguyenmp** [comment]
I mean 

&gt; like this

And

&amp;gt; like this

**Comment by laurencedawson** [comment]
Can't seem to replicate this.

**Comment by nguyenmp** [comment]
It seems to only occur when you edit a comment immediately after posting it, without refreshing the page.

**Comment by laurencedawson** [comment]
Got it! Fixed for 10.7. 

Cheers!
