### ISSUE TITLE
No option to add a title when creating a post

### ISSUE THREAD

**Issue by skylineKid712** [laurencedawson/reddit-sync-development#846]
When submitting a new link there's no option to add a title. If you click on the submit button it gives a toast saying "You must enter a title" but it still doesn't provide a title field. I'm running Sync Dev 10.6 on a Nexus 5 running Android 5.1.
![screenshot_2015-03-26-01-10-19](https://cloud.githubusercontent.com/assets/6434803/6840881/2730c0cc-d357-11e4-9940-03d63c97ec0c.png)

**Comment by laurencedawson** [comment]
Sorry for the delay but this has since been fixed. Cheers.
