### ISSUE TITLE
Can't use purchased pizza theme. Can't buy bacon theme. Google Play Services error, Failed to load inventory.

### ISSUE THREAD

**Issue by danrant** [laurencedawson/reddit-sync-development#847]
I was one of the early pizza theme adopters. Bought it using Sync Dev right after it was announced. I used it for awhile then switched to standard. Now for the last two-three weeks I can't enable the purchased pizza theme or even worse I can't buy bacon. As soon as I enter the theme screen I get "Google Play Services error, Failed to load inventory." notification. I uninstalled and reinstalled the app twice, I erased Google Play Services data and I still get the same error!

Reddit Sync Dev version: 10.6
Google Play Services: 7.0.97
Android: 5.0.1
Phone: Nexus 4

**Comment by laurencedawson** [comment]
Thanks for the report and sorry for the slow delay. I'll fix this for the next release.

**Comment by laurencedawson** [comment]
All themes are now free so this should no longer be an issue.

**Comment by danrant** [comment]
After one hour long extensive testing I can confirm this bug is indeed fixed. Thanks!
