### ISSUE TITLE
UX/Bug - No ability to refresh multireddits if account had none previously

### ISSUE THREAD

**Issue by FineWolf** [laurencedawson/reddit-sync-development#850]
**Steps to replicate:**
 1. Add an account which has no multireddits.
 2. Create a new multireddit using the web interface
 3. Observe: There is no option to refresh multireddits

**Mitigation:**
 1. Remove the account from redditsync;
 2. Re-add account (however, if you have multiple accounts, the order of your accounts is now messed up)

**How to fix:**
 1. Do not remove the multireddit section if there are none.

**Comment by laurencedawson** [comment]
Thanks, added to the backlog.

**Comment by laurencedawson** [comment]
This has been fixed for the upcoming 10.7.8 release. Cheers!
