### ISSUE TITLE
Refreshing image doesn't fix images corrupted during download

### ISSUE THREAD

**Issue by creisman** [laurencedawson/reddit-sync-development#851]
An image was corrupted during download in the new 10.6 update. I expected refresh to not use the cache so it'd be fixed, but refresh seemed to just reload it from cache, which wasn't super useful.

http://i.imgur.com/PuIS93W.png

**Comment by laurencedawson** [comment]
This has been fixed in the 10.6.5 update. Clicking refresh will now delete the previous image on disk and attempt to re-download and display the image.

Thanks for the report.
