### ISSUE TITLE
Lose position while using the 'hide read' option

### ISSUE THREAD

**Issue by creisman** [laurencedawson/reddit-sync-development#853]
If you have several posts read and you click hide read, they collapse and go away, but your scroll position is maintained so a whole bunch of posts can move above the viewport. It'd be nice to attach to the first unread post above the viewport and scroll to it so no posts are accidentally skipped.

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by laurencedawson** [comment]
Merging into proposed design changes for the material design phase 2 (#883).
