### ISSUE TITLE
Random Theme Color 

### ISSUE THREAD

**Issue by awitkowski79** [laurencedawson/reddit-sync-development#855]
Not an entirely needed option but...... Is it possible to get a toolbar color randomizer? It could change the color of the toolbar every 24 hours or something along those lines and it would make the app less stale looking overtime for those who like having their theme changed often

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by laurencedawson** [comment]
I actually don't think I'll be adding this. Most users tend to pick a color and stick to it. Thanks for the suggestion though.
