### ISSUE TITLE
Comment text that says <big company> gets progressively larger text over time

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#856]
http://www.reddit.com/r/cscareerquestions/comments/316v0y/intern_at_small_quickly_growing_startups_or_large_wellknown_companies/cpyuqtm

When viewed in the browser, the content is properly displayed. When viewed in the app, you get a ridiculously growing font size.

**Comment by nguyenmp** [comment]
http://imgur.com/oFchxwd

**Comment by laurencedawson** [comment]
This has since been fixed!
