### ISSUE TITLE
Blank app

### ISSUE THREAD

**Issue by RickyWars1** [laurencedawson/reddit-sync-development#858]
After reddit sync being, and closed, all items disappear. 
Clearing cache and data have no effect. 
Reinstalling app or restarting device fixed the issue. 
Refreshing has no effect. 

Users using EuphoriaOS and Bliss pop have the issue, whether or not it happens on other roms is unknown. 

![screenshot_2015-04-04-18-25-56](https://cloud.githubusercontent.com/assets/10256339/6994910/30958cb2-daf8-11e4-8c35-ba510fbefcd3.png)
![screenshot_2015-04-04-18-26-06](https://cloud.githubusercontent.com/assets/10256339/6994911/35a76450-daf8-11e4-9491-9a2554d9b98c.png)

**Comment by laurencedawson** [comment]
Looks like a Google Play Services issue. Do you have it enabled?

**Comment by DerHighwayMan** [comment]
Same issue here.  I was having it on 4.4.2 with Xposed installed, but am still having it on Resurrection Lollipop 5.1 rom with no Xposed.  I was greenifying Play Services but have disabled that and still no difference despite wiping cache and data, uninstalling, rebooting and reinstalling.

**Comment by machinator2** [comment]
Are you still seeing this issue?

**Comment by laurencedawson** [comment]
Closing for now.
