### ISSUE TITLE
Ability to switch accounts without leaving a comment threas

### ISSUE THREAD

**Issue by dscottboggs** [laurencedawson/reddit-sync-development#859]
I need to be able to switch from one account to another depending on which account I want to comment with.

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by dscottboggs** [comment]
Thanks!

**Comment by BakedBroccoli** [comment]
Shoot, I didn't see this one. I just made a new, more detailed thread here:
https://github.com/laurencedawson/reddit-sync-development/issues/1202

**Comment by laurencedawson** [comment]
Merging:

https://github.com/laurencedawson/reddit-sync-development/issues/795
