### ISSUE TITLE
[Request] - gif to gifv in link handling

### ISSUE THREAD

**Issue by kf6nux** [laurencedawson/reddit-sync-development#861]
Imgur link handling load times could be improved by converting the image URLs to the .gifv extension. Imgur will fallback on its own to whatever format it has for the given image.

**Comment by laurencedawson** [comment]
This is already the default behaviour.

**Comment by kf6nux** [comment]
Oops!  Thanks for correcting me!  Neat to know you guy(s) already thought of that.
