### ISSUE TITLE
[Request] - Always redirect gfycat links to zippy.gfycat

### ISSUE THREAD

**Issue by glha** [laurencedawson/reddit-sync-development#862]
Giant gfycat files are usually ~20MB, while zippy gfycat files are ~1MB, less expensive both on RAM and Data plans.

**Comment by laurencedawson** [comment]
This is already the behaviour. Cheers.

**Comment by glha** [comment]
Thanks for answering, Laurence, but seems like it is not working. I loaded 2 gifs and was warned by my data usage app that Sync used 40MB of data (http://imgur.com/4E382i7). I think this link is one of them (http://www.reddit.com/r/CitiesSkylines/comments/323d1o/my_grand_central_station/), but it happens so often that I didn't marked them down. I will provide you with more links, as soon as I go back to a mobile data covered area. Thank you again.

**Comment by glha** [comment]
Found one of those links: http://www.reddit.com/r/perfecttiming/comments/3354dp/

Here's the info from the internal image viewer: http://imgur.com/7BtqSoX

I hope this helps. Thanks!
