### ISSUE TITLE
Rotating Phone Breaks Videos

### ISSUE THREAD

**Issue by Isaiahfeldt** [laurencedawson/reddit-sync-development#863]
If you rotate your phone while watching a video in a new tab ( like when you click a link that takes you to a website in another tab) it will refresh the page and video but will still play the sound of the video before you rotated your phone. 

Instructions to recreate error:
1. Use Sync for Reddit and open a link to a page that has a video.
2. Play the video. Rotate your phone to landscape and you will still hear the video but you will see that the page has refreshed and the video appears to be stopped, although you can still hear it.

**Comment by laurencedawson** [comment]
Merging into known webview issues (#884).

**Comment by laurencedawson** [comment]
This has been fixed as part of fixing:

https://github.com/laurencedawson/reddit-sync-development/issues/730
