### ISSUE TITLE
View Subreddit pulling auto-complete(suggestions) from subscribed subreddits

### ISSUE THREAD

**Issue by RogerFederer17** [laurencedawson/reddit-sync-development#865]
This is the only feature that prevents me for using Sync. I have a lot of subscrives subs, so the fastest way is to press view subreddit and write it, but it seems only some big subreddits appear as suggestions.

**Comment by laurencedawson** [comment]
Added to v10.7.8.

**Comment by RogerFederer17** [comment]
OMG THANKS DUDE

2015-05-03 18:32 GMT+03:00 Laurence Dawson <notifications@github.com>:
