### ISSUE TITLE
Reddit Sync fails to log into user accounts fully when set to have traffic proxied through Orbot [root]

### ISSUE THREAD

**Issue by Techman-** [laurencedawson/reddit-sync-development#866]
Hi,

I have `Sync for Reddit` and `Android WebView` set to be proxied through Orbot. However, the app will fail to grab subreddits from an account. The actual logging in and granting access part works fine, but after that, there is an issue.

I suspect that this might have something to do with Cloudflare and how you might need to punch in a code to grant temporary access to the site. @laurencedawson can you do some debugging and look into this for me? If this turns out to be the case, perhaps adding built in support for opening a quick WebView to enter in the code would be nice.

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by laurencedawson** [comment]
Just tested this again and it seems to be working again.
