### ISSUE TITLE
Streamable support

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#867]
If possible, please add in-app support for the streamable format (HTML5, see http://streamable.com/about). See http://www.reddit.com/r/nba/comments/2u9nbp/post_game_thread_the_atlanta_hawks398_extend/co6ewwj for examples of streamable links.

Request thread: http://www.reddit.com/r/redditsync/comments/32a0jb/can_we_please_get_streamable_support/

**Comment by laurencedawson** [comment]
Pencilled in for the next release.

**Comment by laurencedawson** [comment]
This has been added to the v10.7.8 release.
