### ISSUE TITLE
_Underscore italics_ support

### ISSUE THREAD

**Issue by richardg867** [laurencedawson/reddit-sync-development#868]
A rarely-used feature of Reddit's markdown is \_underscore italics\_, which renders the same way as \*normal italics\* but is not currently supported by Sync.

From Github's Markdown guide:

    *This text will be italic*
    _This will also be italic_
    
    **This text will be bold**
    __This will also be bold__

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
