### ISSUE TITLE
Totally blank app. (Sync Pro)

### ISSUE THREAD

**Issue by cdtf** [laurencedawson/reddit-sync-development#869]
Hi,

When I open the app, I get a blank page. I can slide the left panel, but this one is blank too.

If I try to use the search button or refresh, the app forces close.

Tried to clear the cache and app data, this does nothing.

Reinstalling the app fixes the issue. For a few hours only, then it's back to blank app.

Using 4.3.3 on an HTC One M7.
![screenshot_2015-04-17-12-49-24](https://cloud.githubusercontent.com/assets/11992521/7200768/6b56b7c4-e500-11e4-934b-35599add4ce2.png)
![screenshot_2015-04-17-12-49-35](https://cloud.githubusercontent.com/assets/11992521/7200781/8f280acc-e500-11e4-9df9-6285ec1f9e9c.png)

**Comment by laurencedawson** [comment]
Running exposed?

**Comment by cdtf** [comment]
Running xPosed, with Sense Toolbox, Greenify, and Unicon (an Icon themer).

**Comment by DerHighwayMan** [comment]
As I posted in #858..

Same issue here. I was having it on 4.4.2 with Xposed installed, but am still having it on Resurrection Lollipop 5.1 rom with no Xposed. I was greenifying Play Services but have disabled that and still no difference despite wiping cache and data, uninstalling, rebooting and reinstalling.

**Comment by laurencedawson** [comment]
@cdtf It's not a mater of chosing between them. I just need to figure out why xposed (or you can report to the xposed team) why their extension is stopping Google Play Services from running.
