### ISSUE TITLE
Ability to easily subscribe/usubscribe from a subreddit 

### ISSUE THREAD

**Issue by dennisonuy** [laurencedawson/reddit-sync-development#871]
First of all excellent work, the app has a lot of potential. That said I am not too fond of subscribing and unsubscribing from subs by editing the subreddit list.

It would be cool if we can do this from within the context menu of a subreddit, or from a context menu action on the item within card view.

**Comment by FirestarPwns** [comment]
Swipe in from the right side when viewing a subreddit. That is the sidebar and there is a subscribe/unsubscribe button. I do agree that there should be button in the context menu so this is more obvious.

**Comment by dennisonuy** [comment]
Whoah, I did not know there was a swipe right function. I am impressed. Perhaps there should be a tutorial, or make it evident somehow that there is a swipe right function for dumb users like me 😉






From: FirestarPwns
Sent: ‎Thursday‎, ‎April‎ ‎23‎, ‎2015 ‎1‎:‎04‎ ‎AM
To: laurencedawson/reddit-sync-development
Cc: Den Uy





Swipe in from the right side when viewing a subreddit. That is the sidebar and there is a subscribe/unsubscribe button. I do agree that there should be button in the context menu so this is more obvious.

**Comment by FirestarPwns** [comment]
+1 On the tutorial. Relay has one and sync really needs one too.
