### ISSUE TITLE
Zoom is not sufficient for many images

### ISSUE THREAD

**Issue by cschanck** [laurencedawson/reddit-sync-development#872]
I persistently have to switch back to Relay (formerly RedditNews) because Sync won't zoom far enough.

For example, consider this link: http://www.reddit.com/r/movies/comments/33ih6u/i_made_a_timeline_diagram_for_paul_blart_mall_cop/

Relay lets me zoom far enough to read the text no problem, whereas Sync doesn't come close. This can be a big deal on tall screencap images, or images which are large and heavy on text. 

Imgur gallery with screenshots: http://imgur.com/a/XdrPD

Additional example was mentioned here: http://www.reddit.com/r/redditsync/comments/30t7rf/an_illustration_of_image_zooming_issues/

**Comment by FirestarPwns** [comment]
Deepzoom is your friend.

**Comment by cschanck** [comment]
Does the same thing, deep zoom or not.

**Comment by cschanck** [comment]
It feels like Relay let's me zoom far past the resolution that matches to my screen. Note 4, pretty high resolution screen.

**Comment by laurencedawson** [comment]
OK so with the next release Deepzoom can now zoom up to 25x in and zooms into 2x when double tapped.
