### ISSUE TITLE
setting the primary material color

### ISSUE THREAD

**Issue by moben** [laurencedawson/reddit-sync-development#873]
I use the Minuum keyboard[1] which has a theme that adapts its color to the primary "material" color of the current app. However, it doesn't seem to work with Sync for Reddit.

Not sure what is going on here, but I assume it is related to the runtime-changable color.
Is Sync maybe not setting android:colorPrimary/android:colorPrimaryDark as per [2] and coloring the status bar in another way? Or is the problem Minuums end?

[1] https://play.google.com/store/apps/details?id=com.whirlscape.minuumkeyboard
[2] https://developer.android.com/training/material/theme.html

**Comment by laurencedawson** [comment]
Sync sets the primary color at runtime. Not sure about that specific keyboard but I guess they should look for the runtime value and not the hard coded value.
