### ISSUE TITLE
In-app web browser is always blank

### ISSUE THREAD

**Issue by ajm83** [laurencedawson/reddit-sync-development#875]
Opening pages using the in-app browser just shows a blank white page. There is no error message, or progress bar. It just immediately appears white. Opening in the normal browser using Open With Browser works correctly.
This StackOverflow post for example:
![screenshot_2015-04-25-07-02-03](http://i.imgur.com/rHPijzbl.png)
Show in the in-app browser:
![screenshot_2015-04-25-07-02-11](http://i.imgur.com/V2g5IVfl.png)
And in the main device browser:
![screenshot_2015-04-25-07-02-38](http://i.imgur.com/dxG6NYwl.png)

App is the free version. Device is a GNex running Android 4.4.4. Used to work with this ROM, but it broke recently.  Clearing the cache or all the app data has not fixed it.

Thanks for the app.

**Comment by laurencedawson** [comment]
Merging into #884.
