### ISSUE TITLE
NSFW previews not matching reddit preferences

### ISSUE THREAD

**Issue by rolandsdrktower** [laurencedawson/reddit-sync-development#879]
I currently have option selected in my reddit account:
![image](https://cloud.githubusercontent.com/assets/6371063/7400026/f1b8a85a-ee87-11e4-8688-d26d19f9e95a.png)

And it appears to be working on the web:
![image](https://cloud.githubusercontent.com/assets/6371063/7400017/e0c84366-ee87-11e4-879e-bd7e035b77be.png)

However, in redditsync, it still shows the thumbnail:
![image](https://cloud.githubusercontent.com/assets/6371063/7400142/baa2c94e-ee88-11e4-85c0-acc45501b244.png)

This is a pretty recent development; it actually only started happening since I cleared app data and re-added my account.  I am aware of the "Hide NSFW previews" in the menu, however I've never had to use that before.  This would throw up previews in subreddits that are NSFW only, which I'm not looking to do.  Any thoughts?

**Comment by laurencedawson** [comment]
This preference is independent of reddit. By default the app has to have nsfw previews disabled but you can remove this. Cheers!
