### ISSUE TITLE
Posts with links to PDFs try to automatically download file when opening thread with '[BETA] Load post content' enabled

### ISSUE THREAD

**Issue by creisman** [laurencedawson/reddit-sync-development#880]
This is the view immediately after opening the thread: http://i.imgur.com/B1K9HfL.png.

It should probably not try to load the post content when it would require a download.

**Comment by creisman** [comment]
Post in screenshot: http://www.reddit.com/r/Android/comments/349ve2/htc_reports_13_billion_in_revenue_with_a_net/

**Comment by laurencedawson** [comment]
Duplicate: #878.
