### ISSUE TITLE
HTML-Code in "code-format" get interpreted as HTML-Code

### ISSUE THREAD

**Issue by Ch1lli** [laurencedawson/reddit-sync-development#881]
What it looks like on desktop: http://www.reddit.com/r/DotA2/comments/34g9sk/how_to_read_the_684changes_without_tabbing_out_or/cquw1xd

What it looks like on the phone: http://i.imgur.com/JhEYMnn.png

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by laurencedawson** [comment]
This has been fixed for the next release.
