### ISSUE TITLE
Material design update phase 2

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/reddit-sync-development#883]
Redesign of the current subreddit view + comments view.

http://www.reddit.com/r/redditsync/comments/32p7ti/material_design_update_phase_2/

**Comment by laurencedawson** [comment]
- Make it easier to vote comments

**Comment by laurencedawson** [comment]
Ongoing done list:

- Cards now use the CardsView (#698)
-

**Comment by jvnknvlgl** [comment]
I don't know if you need it, but you should definitely look at the new Design Support Libary.

http://android-developers.blogspot.nl/2015/05/android-design-support-library.html?m=1

**Comment by laurencedawson** [comment]
This has since been released!
