### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/reddit-sync-development#886]

**Comment by mimischi** [comment]
Any comment on how this will be implemented? Can everyone use those features like in any other reddit android app or will this be a reddit gold subscriber feature only?

**Comment by Pink401k** [comment]
Was about to make a feature request for filtering /all when I saw this.  

This is a huge feature that would improve sync even further in my eyes.  Would love to see this implemented :) :+1:

**Comment by laurencedawson** [comment]
Added for the 10.7.12 release.
