### ISSUE TITLE
Option to disable cache (internal and WebView)

### ISSUE THREAD

**Issue by martinml** [laurencedawson/reddit-sync-development#889]
In a few hours of browsing Reddit, the Sync cache can reach almost a gigabyte, always according to Settings > Applications. After a couple of years, the flash on my phone isn't what it used to be and it would be great if I could avoid caching altogether. Also, I browse on wifi pretty much all the time and I don't usually open the same item twice, so I guess my use case doesn't take advantage of a cache.

This hypothetical option would disable both the internal cache (thumbnails, etc) and the WebView cache (including Local Storage). I saw that [you plan to clear the WebView cache each time it's loaded](https://github.com/laurencedawson/reddit-sync-development/issues/884#issuecomment-98420552), but I'm not sure it's possible to totally disable it.

**Comment by laurencedawson** [comment]
The webview cache is now cleared each time it's loaded and that will suffice.

Will add addition cache options for the 10.7.12 release. Cheers.

**Comment by laurencedawson** [comment]
Added for the 10.7.12 release.
