### ISSUE TITLE
"Go to subreddit" from post menu

### ISSUE THREAD

**Issue by joshproehl** [laurencedawson/reddit-sync-development#892]
A feature I miss from other reddit browsers I've used is the ability to see a post, go "that's interesting, I wonder what else..." and jump to the subreddit that post is from.

Implementing this as a "Go to Subreddit" option when long-pressing a post would be excellent!

**Comment by jellyberg** [comment]
If you tap the overflow menu (3 dots) there's an option for "view subreddit".

**Comment by joshproehl** [comment]
Ah, if you go INTO the post you can view the subreddit. That's very good to know, thank you!

I do think that adding it as an option to the long-press when viewing a post on the list would still be helpful though, and would improve the discoverability of the feature. (If I've opened the post from the list, I don't necessarily want to have to load the comments and make two more taps to check out the subreddit.)

**Comment by jellyberg** [comment]
Yeah fair point, agreed!

**Comment by laurencedawson** [comment]
This is a restriction of the current list view not having this as an option. In the material redesign this will be covered so I'm going to close this issue. Thanks for reporting.
