### ISSUE TITLE
Saved posts do not load (Error loading posts)

### ISSUE THREAD

**Issue by karmck** [laurencedawson/reddit-sync-development#895]
On my Galaxy S4, the 'Saved' subsection under 'Profile' does not load anything and a text label in the middle of the screen says "Error loading posts". 

All the other subsections under the 'Profile' section work well.

This has been an issue since I started using Reddit Sync about a year ago on my S4.

**Comment by karmck** [comment]
I deleted all the saved posts from the website, thinking that one of the saved posts might be causing the problem. I logged out from reddit sync, cleared cache, and logged back in.

It didn't help. Same error message.

**Comment by laurencedawson** [comment]
Odd. Will look into this.

**Comment by karmck** [comment]
OK. Let me know if I can provide any further info.

**Comment by laurencedawson** [comment]
Are you still having this issue?

**Comment by karmck** [comment]
Hi, no, the issue is resolved.
Thanks!

**Comment by laurencedawson** [comment]
Cheers!
