### ISSUE TITLE
Sorting menu breaks when dragged

### ISSUE THREAD

**Issue by SirFadakar** [laurencedawson/reddit-sync-development#898]
When you drag to select the sorting, it stops working altogether as soon as you let go. If the sorting menu is tapped then it will continue working fine for as long as you continue tapping instead of dragging.

Video is posted here: https://youtu.be/j6yaaha-4b0

I changed subs to get the point across that it won't work again, but if I had tried switching it back from new to hot immediately after it still wouldn't have worked, whether by dragging or tapping.

**Comment by SirFadakar** [comment]
I changed subs to get the point across that it won't work again, but if I had tried switching it back from new to hot immediately after it still wouldn't have worked, whether by dragging or tapping.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
