### ISSUE TITLE
Broken scrolling of text when creating a text post

### ISSUE THREAD

**Issue by twig** [laurencedawson/reddit-sync-development#899]
When the keyboard is showing, scrolling up/down will move the activity layout but not the text within the text area.

![screenshot_2015-05-07-12-48-56 1](https://cloud.githubusercontent.com/assets/59689/7507725/8e2d5d5e-f4b7-11e4-97fb-f8f0c16262f7.png)

**Comment by machinator2** [comment]
Are you still seeing this?

**Comment by twig** [comment]
Yep this is still an issue.

* go to submit text post
* type in a lengthy blurb into the description field
* try to scroll the text
* whole screen moves instead of text content

**Comment by laurencedawson** [comment]
Unable to reproduce. 

What version of Android?

**Comment by twig** [comment]
Android 6

**Comment by laurencedawson** [comment]
I've increased the size of the input box for the next release. This should solve the issue.

Cheers.

**Comment by twig** [comment]
I've taken a thorough look and realised it happens when the keyboard is showing.

Got a video of it happening. Not sure if it's to do with the activity layout or my keyboard app.

https://youtu.be/l4cTyF1B0y8
