### ISSUE TITLE
[Bug] Caret within code block is not displayed

### ISSUE THREAD

**Issue by Nightfirecat** [laurencedawson/reddit-sync-development#900]
Reproduced with this text:

    ; ctrl+Num1 -> item swap for slot 5
    ^Numpad1::
      invSwap(5)
    Return

What's shown:

    ; ctrl+Num1 -> item swap for slot 5
    Numpad1::
      invSwap(5)
    Return

Example: https://www.reddit.com/r/RotMG/comments/354m9w/new_realmscript_major_release_support_for/cr12map
Screenshot: https://www.reddit.com/r/RotMG/comments/354m9w/new_realmscript_major_release_support_for/cr22pmu

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.
