### ISSUE TITLE
[Bug] Night mode turns white when switching apps

### ISSUE THREAD

**Issue by bjh345** [laurencedawson/reddit-sync-development#902]
When reddit Sync is in Amoled night mode, using the multitasking button to switch back to it makes the background blinding white. Rotating to landscape and back fixes it until it happens again. 

Video: https://youtu.be/Aeszf3NginA

**Comment by laurencedawson** [comment]
Merging into the big night mode tweaks issue as this is a repeat:

https://github.com/laurencedawson/reddit-sync-development/issues/832
