### ISSUE TITLE
[Enhancement] Animate parent-comment arrow navigation

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#905]
It's very jarring and I have this worry that I must have tapped twice and skipped one of the parent comments or something.

An animation would not only be beautiful, but help clear up this uncertainty.

**Comment by laurencedawson** [comment]
This will probably be part of the material redesign.

**Comment by okungnyo** [comment]
Awesome!

**Comment by laurencedawson** [comment]
This *was* part of the redesign but was removed as it was a little flakey!
