### ISSUE TITLE
Random big NSFW-Tags

### ISSUE THREAD

**Issue by l3d00m** [laurencedawson/reddit-sync-development#906]
Happens in card view as well as in single post view. It happens random and the tags get normal after a short time in most cases. Same happens to gold tags. 
LG g2 android 5.0.2 as well as on 4.4.2

**Comment by laurencedawson** [comment]
Can you reproduce this?

**Comment by l3d00m** [comment]
No, not really. It's random. Thanks for your help.

![Picture of it](https://cloud.githubusercontent.com/assets/12055376/7751052/326ff540-ffd8-11e4-98fa-d16d916ba320.png)

**Comment by laurencedawson** [comment]
This has been fixed as part of the material redesign:

https://github.com/laurencedawson/reddit-sync-development/issues/883
