### ISSUE TITLE
[Enhancement] Capitalization and wording inconsistencies in Settings

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#909]
I think these changes would help make the Settings a bit more clear.

Style: Set colors, font sizes etc --> **Style: Change how the app looks**
General: Common UI options --> **Behavior: Change how the app behaves**
Night Options: Setup the night theme --> **Night theme: Change how the night theme works**
Images: Image specific options --> **Images: Change how images work**
Posts: Post specific options --> **Posts: Change how posts work**
Comments: Comment specific options --> **Comments: Change how comments work**
Messaging: Message specific options --> **Messages: Change how messages work**
Link handling: Setup in-app link handling --> **Link handling: Change how in-app links work**

Style

* *[popup dialog]* Toolbar color
  * Classic Slate gray --> **Classic slate gray**
  * Deep Purple --> **Deep purple**
  * Light Blue --> **Light blue**
  * Light Green --> **Light green**
  * Deep Orange --> **Deep orange**
* Toolbar color (night) --> **Toolbar color (night theme)**
* *[popup dialog]* Toolbar color (night) --> ***[popup dialog]* Toolbar color (night theme)**
  * Classic Slate gray --> **Classic slate gray**
  * Deep Purple --> **Deep purple**
  * Light Blue --> **Light blue**
  * Light Green --> **Light green**
  * Deep Orange --> **Deep orange**
* Themes --> **Theme**
* Pizza theme
  * Preview theme --> **Preview this theme**
  * Enabled --> **Use this theme**
* Bacon theme
  * Preview theme --> **Preview this theme**
  * Enabled --> **Use this theme**
* Autohide Toolbar: Phones only --> **Autohide toolbar: (for phones only)** ----- *The "for phones only" part is in parentheses for consistency with the other user notices/warnings, which all have parentheses.*
* Colored navigation bar: Color the soft-navigation bar with the Toolbar color --> **Colored navigation bar: Use the toolbar color for the navigation bar** ----- *The "soft" part is redundant and unnecessary, I think, because "navigation bar" by definition means "soft navigation bar".*

General

* Swipe to go back from comments, profiles, ... --> **Swipe to return to previous page**
* Show Floating Action Buttons --> **Show floating action buttons**

Night theme

* Night theme --> **Use night theme**
* AMOLED black night mode: Enable with nightmode for a true black background --> **Use true black AMOLED night theme: (requires night theme to work)**
* Start time --> **Auto night theme start time**
* End time --> **Auto night theme end time**

Images

* Quick dismiss: Tap to dismiss the open image --> **Quick close: Tap anywhere on the screen to close an open image**
* Reduce data usage (mobile): Use smaller fullscreen images to save bandwidth --> **Reduce data usage (mobile): Load lower-quality images to save bandwidth**
* Reduce data usage (WiFi): Use smaller fullscreen images to save bandwidth --> **Reduce data usage (Wi-Fi): Load lower-quality images to save bandwidth**
* Resample images as you zoom in --> **Resample images as they are zoomed in**
* Show image debug options: Display a detail image download debug log --> **Show image download details: Show a debug log overlay for loaded images**
* Decode Quality: Change the image decode quality --> **Decode quality: ARGB_8888/RGB_565** ----- *Show the currently selected option here, like how [Start time] and [End time] show the time. For example, it should say "ARGB_8888" or "RGB_565", not "Change the image decode quality".*
* *[popup dialog]* Decode Quality --> ***[popup dialog]* Decode quality**

Posts

* [BETA] Swipe to hide posts --> **Swipe to hide posts (beta)**

Comments

* Initial comment count: The number of comments to load --> **Number of comments to load initially: 25/50/100/200/All** ----- *Show the currently selected option here, like how [Start time] and [End time] show the time. For example, it should say "25" or "All", not "The number of comments to load".*
* Default comment sort: Sort by Top/Best/New/Old/Controversial/Q&A/Suggested --> **Default comment sort: Best/Top/New/Controversial/Old/Q&A/Suggested** ----- *This is a small thing, but this is the order in which the sorting options appear on the website itself. Also, I believe that the "Sort by" bit is redundant and can be removed.*
* Show colorful comment indents --> **Color-code comment indents** ----- *"Show" implies that it's something that can be hidden, as opposed to something that in actuality can only be changed.*
* Show user flair in comments --> **Show user flairs in comments**
* [BETA] Load post content: Swipe left to view post content next to the comments (phones only) --> **View posts alongside comments (beta): Swipe left to view posts alongside comments (for phones only)** ----- *I couldn't enable this feature, so I reworded it the best I could without understanding what it actually does.*
* Enable comment arrows: Show arrows at he bottom to navigate between parent comments --> **Show comment arrows: Navigate between parent comments**
* Enable comment expanded links: Relay all links within a comment to the bottom of the comment (may cause comments to scroll slower) --> **Show comment expanded links: Gather all the links within a comment to the bottom of it (may cause slower scrolling)**
* Enable fast comment scrolling --> **Fast scroll comments: Show draggable scrollbar in comments**
* Single click to hide comment: Reverse the comment click actions --> **Quick hide comments: Tap a comment once to hide it**

Also, it would be nice if all the items were re-ordered alphabetically.

I hope I could help. Thanks for reading.

**Comment by okungnyo** [comment]
Updated the list. Please check again. Sorry for the hassle.

**Comment by okungnyo** [comment]
Updated the list again.

**Comment by laurencedawson** [comment]
I'll look into merging some of these. 

Not a fan of "Change how the app looks". They're in the app so it seems redundant.

**Comment by okungnyo** [comment]
Thanks.

It's your app and you can do as you wish!

We're only here to make the app more awesome, hehe.

**Comment by okungnyo** [comment]
If you're going to keep the current ones, then could you add hyphens?

(So like 'Comment specific options' becomes 'Comment-specific options'.)

**Comment by laurencedawson** [comment]
Going to close this issue as the settings have had a bit of an overhaul with the v11 release.

If you see anything wrong with the new settings let me know and I'll re-open the issue. Cheers!
