### ISSUE TITLE
[Feature Request] Bottom Third Imgur album text 

### ISSUE THREAD

**Issue by Absalonius** [laurencedawson/reddit-sync-development#910]
It would be nice to have the imgur photo text to be overlayed over the image as a bottom third, instead of on top. most of the time that area is too small to display anything useful for subreddits such as DIY

I've made a mockup of what I'm thinking...
http://imgur.com/a/z5kJj

here is the source album for reference
https://imgur.com/a/ANU46

**Comment by laurencedawson** [comment]
I've since moved the text into the bottom sheet. Cheers.
