### ISSUE TITLE
[Bug] Duplicate sub entries in Subreddit dialogue if already subscribed

### ISSUE THREAD

**Issue by jhinder** [laurencedawson/reddit-sync-development#911]
Version: 10.7.11, Pro

Steps to reproduce:

1. Subscribe to one of the subs that are listed in the default list of suggested/popular subs inside the Subreddit dialogue in the sidebar. Example: AskMen.
2. Go to said dialogue, and enter the sub's name.
3. The sub is listed twice.

Example: [1](https://i.imgur.com/ItiP8Am.png), [2](https://i.imgur.com/LCTbnKr.png); [normal](http://i.imgur.com/sgc8pd4.png) behaviour

**Comment by laurencedawson** [comment]
Fixed for the upcoming 10.7.12 release.
