### ISSUE TITLE
Add ability to set search parameters when when starting a new search

### ISSUE THREAD

**Issue by OneGoodReason** [laurencedawson/reddit-sync-development#915]
Right now, if you want to search a subreddit for something and use a different sort method than "relevant / from all time," you still  have to load it that way first. Then you can redo the search with your desired parameters.

It would save time and eliminate an unnecessary search if these could be set at the start of a search.

**Comment by laurencedawson** [comment]
Duplicate. Merging with:

https://github.com/laurencedawson/reddit-sync-development/issues/330
