### ISSUE TITLE
[Feature Request] Show up/down-vote arrows in appropriate color when selected in comments

### ISSUE THREAD

**Issue by kraymars** [laurencedawson/reddit-sync-development#917]
Please make the upvote arrow orange and downvote arrow purple when selected in comments.  This works for main posts, but not with comments.  You can see the up/down-vote count change color when one of the comment arrows is selected, but on extremely long comments it requires scrolling to see if you voted on a comment.  Actual screen and mock-up screens attached.
![comment-arrow-actual](https://cloud.githubusercontent.com/assets/12465448/7660818/8212ae9c-fb1b-11e4-85e0-306373618782.png)
![comment-arrow-mock](https://cloud.githubusercontent.com/assets/12465448/7660819/8212e196-fb1b-11e4-946b-ac4957cc810f.png)

**Comment by laurencedawson** [comment]
Pencilled in for a future release.

**Comment by laurencedawson** [comment]
This has since been added.

Cheers.
