### ISSUE TITLE
Filter management bugs

### ISSUE THREAD

**Issue by Chakyl** [laurencedawson/reddit-sync-development#925]
There are two small issues currently with filtering subreddits.
1.) Selecting and removing one from the list removes the first subreddit alphabetically instead of the one selected.
2.) Filter blocks all subreddits that contain the filtered word. For example, if I filter out /r/gaming, /r/pcgaming and /r/truegaming get filtered also.

**Comment by laurencedawson** [comment]
1. Fixed the first
2. Will look into point 2 for the next release. Cheers!

**Comment by Chakyl** [comment]
Hey, thanks! I noticed the first fix but forgot to edit the ticket.

**Comment by laurencedawson** [comment]
2. Has since been fixed. 

Cheers.
