### ISSUE TITLE
Submissions not opened being marked as read

### ISSUE THREAD

**Issue by Vilkku** [laurencedawson/reddit-sync-development#928]
Most of the time when I open a submission the bottom-most submission in the view also gets marked as read, in addition to the submission I actually opened. I found [discussion about it on reddit](https://www.reddit.com/r/redditsync/comments/36h4tf/threads_being_grayed_out_even_though_i_didnt/), but nothing in the issues tracker.

This happens on both of my devices (Nexus 4 and Nexus 7 2013, both running Cyanogenmod 11) on the latest version of Sync Pro (10.7.2, I think - based on the latest entry in the Play Store changelog). I use the List view on both devices.

**Comment by laurencedawson** [comment]
Fixed for 10.7.4
