### ISSUE TITLE
Sync no longer compatible with device

### ISSUE THREAD

**Issue by GeneralMushroom** [laurencedawson/reddit-sync-development#929]
Hi,

I have used Reddit Sync on my HP Slate 7 device with Jellybean 4.1.1 for the past few months with no issues, and even paid the in app purchase to remove adds. 

I noticed yesterday that all in app attempts to open imgur links or other images failed. I quickly google searched and found somone suggested to reinstall it. On attempting to do so, I found it wasn't included in my "installed" apps, and when going to the store, it tells me that it is not compatible with my device.

However, it still works in all other functions, I can still post, comment etc using the app. Any help would be appreciated!

**Comment by laurencedawson** [comment]
Odd. Will look into this.

**Comment by laurencedawson** [comment]
Closing but I've since relaxed the requirements for sync. No more GPS etc.
