### ISSUE TITLE
[Enhancement] Material List View

### ISSUE THREAD

**Issue by tehdef** [laurencedawson/reddit-sync-development#930]
With the upcoming material update, I'd like to see list view changed to fall in line with Googles apps that feature a list view. Current list view is based off of ICS/JB, which is inconsistent and visually out of date. 

Circle images would be present, and would fill with either reddit alien for text posts, or a downsized image if one exists. Circle image should be clickable to bring up any images directly into the image gallery view, like it functions in card view. All actions (Downvote, upvote, profile, 3dot) should pop-out underneath in a material fashion from clicking something similar to the star from the GMail app. 

Additional consistent visual elements in line with the GMail app including spacing, text sizing and weight, etc.

**Comment by laurencedawson** [comment]
This is already planned!

https://github.com/laurencedawson/reddit-sync-development/issues/883
