### ISSUE TITLE
feature request: ability to disable all or certain notifications for modmail

### ISSUE THREAD

**Issue by honestbleeps** [laurencedawson/reddit-sync-development#931]
This is admittedly a really niche request, but I think moderators who use redditsync may appreciate it. I totally get that it probably belongs quite low on the priority list.

I'd like to be able to either:

- disable all modmail notifications, but not regular mail notifications

or:

- disable modmail notifications containing certain keywords

The reason for this is that I'm a mod of some large subs that use AutoModerator to filter out / alert us to profanity - so I'm often getting notification popups saying "A post with [really offensive word] was flagged, please review it" on my phone in public (and via pushbullet on my laptop, too).

This is a unique problem, so I completely respect that it probably won't be addressed above a huge number of other requests, but I wanted to put it out there!

**Comment by laurencedawson** [comment]
Pencilled in for a future release.

**Comment by laurencedawson** [comment]
This has since been added.
