### ISSUE TITLE
[Feature request] Controversial comments marker

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#935]
About a year ago, Reddit removed the ability to see the exact number of upvotes/downvotes a comment received. This change was negatively received by the community, because a comment that got 100 upvotes and 99 downvotes has entirely different connotations from a comment that got 1 upvote and 0 downvotes.

In response, Reddit added a dagger sign to signify controversial comments: http://i.imgur.com/s5dTVpq.png

The announcement can be read here: http://redd.it/293oqs

It would be great if Sync added support for this feature.

(For reference, Relay for Reddit implemented it as "?!" instead of a dagger.)

**Comment by laurencedawson** [comment]
Pencilled in for the next release.

**Comment by laurencedawson** [comment]
This has been added for the next release (v11.5.11).

Thanks again for reporting this, sorry it took so long!
