### ISSUE TITLE
Image Sharing Post Title

### ISSUE THREAD

**Issue by JamieH93** [laurencedawson/reddit-sync-development#938]
Hi there,

Little nitpick but would improve the app for me.

![1](https://cloud.githubusercontent.com/assets/8375853/7869933/a7e6a936-057d-11e5-89be-ca7870e0dadc.png)

If you share from the Main Frontpage list from this menu, It shares the URL Twice as seen below.

![2](https://cloud.githubusercontent.com/assets/8375853/7869934/a7e9f532-057d-11e5-8dec-49cce7dfc423.png)

However If you share from Within the Post itself where the Comments are shown, It sends the Title and URL when you share it.

![3](https://cloud.githubusercontent.com/assets/8375853/7869935/a7effef0-057d-11e5-82aa-20de158def40.png)

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by laurencedawson** [comment]
Merging:

https://github.com/laurencedawson/reddit-sync-development/issues/450
