### ISSUE TITLE
[Feature Request] Add option to filter subreddit to overflow menu

### ISSUE THREAD

**Issue by greenskye** [laurencedawson/reddit-sync-development#939]
I'd like the option to add a subreddit to the list of filtered subreddits directly from a post in /r/all. Right I remember the name and type it in manually. Not a huge deal if it doesn't get implemented, but it'd be nice to have.

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by laurencedawson** [comment]
This has since been added. Cheers!
