### ISSUE TITLE
[Feature Request] Message moderators 

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#941]
On the website, there is an option in the sidebar to message the moderators. For example, for r/redditsync, the URL/page is http://www.reddit.com/message/compose?to=%2Fr%2Fredditsync

Would it be possible to integrate this feature into the app instead of having to do this in the mobile browser?

**Comment by laurencedawson** [comment]
As far as I can tell, there is no easy way to get a list of mods from the API for a given sub.

**Comment by nandhp** [comment]
Although it might be nice to have a list of the moderators available, that's a separate issue.

The "message the moderators" link should just start composing a message to /r/subreddit.
