### ISSUE TITLE
[Feature Request] Report post/comment feature enhancement

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#942]
Sync for reddit already has a report feature, but the reddit website allows you to specify one of the given reasons (spam, vote manipulation, personal information, sexualizing minors, breaking reddit) or write your own (with a 100 character max). Can the app's report feature be changed to add these functions?

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/reddit-sync-development/issues/802
