### ISSUE TITLE
Certain gifs not playing fully

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#944]
See http://www.reddit.com/r/redditsync/comments/37lakc/gifs_not_playing_fully/. In particular, http://gfycat.com/FirmElegantDungenesscrab stops playing after 1 second; restarting app and clearing cache does not fix the issue.

Addendum: here's another thread on the issue: http://www.reddit.com/r/redditsync/comments/37c17d/gif_isnt_loading/

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by machinator2** [comment]
It's worth noting that I'm not experiencing these issues anymore on 11.5.10 on my Nexus 6P running 6.0.1.

**Comment by laurencedawson** [comment]
Since the v11 release I switched to a new GIF player. 

Closing for now.
