### ISSUE TITLE
Comments past 10th sublevel in comment tree do not load

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#945]
See http://www.reddit.com/r/redditsync/comments/37mk4q/comments_will_not_load/ for an example of current app behavior. Another example of where this occurs can be seen in the comment thread at http://www.reddit.com/r/AskReddit/comments/37tshq/people_who_have_been_to_prison_what_unexpected/crpuc8l

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/reddit-sync-development/issues/711
