### ISSUE TITLE
Text within angle brackets doesn't show up

### ISSUE THREAD

**Issue by YodaDaCoda** [laurencedawson/reddit-sync-development#948]
Example post: http://www.reddit.com/r/talesfromtechsupport/comments/37zz6p/thats_one_way_to_test_it/

At the end of the post it says:
My new nickname is \<my real first name\>! Thank you for playing with me today!

This shows up as:
My new nickname is ! Thank you for playing with me today!

**Comment by laurencedawson** [comment]
Repeat:

https://github.com/laurencedawson/reddit-sync-development/issues/783
