### ISSUE TITLE
Release for F-Droid

### ISSUE THREAD

**Issue by addisonamiri** [laurencedawson/reddit-sync-development#949]
Is there any possibility of releasing reddit-sync on F-Droid? It'd be hard if you guys depend on google play services but if it's minor I think it would definitely be cool to see. The only problem I see with it is how to have a pro version but maybe F-Droid release could be a dev build or even just the free version?

**Comment by laurencedawson** [comment]
The app isn't open source so won't be releasing to F-Droid. Cheers.
