### ISSUE TITLE
[Feature Requests]

### ISSUE THREAD

**Issue by Frumy** [laurencedawson/reddit-sync-development#952]
- Show image preview on the right
- Function similar to reddit relay where external links can be loaded concurrently with the comments and be able to drag up  and down for easy access once in the comments.
- Custom subreddit styles as toolbar colour theme

**Comment by l3d00m** [comment]
AFAIK the second one is already implemented. You can enable Preload Links in options and then swipe to the left when you're in the comments.

**Comment by laurencedawson** [comment]
- This is not part of the design of sync
- As l3d00m noted you can already do this
- I am not planning to support custom subreddit styles

**Comment by Frumy** [comment]
Wow, I am pretty stupid not to have seen the second point in the options. That's great, thanks!
