### ISSUE TITLE
Sliding/swipe seek, volume, brightness controls with YouTube videos?

### ISSUE THREAD

**Issue by jaredschaefer** [laurencedawson/reddit-sync-development#954]
Controls like Viral YouTube player and  MX player.  I know I can just open the videos with viral but I like to stay in app when possible and I don't know how much longer viral will work with the changes Google keeps making. Horizontal is seek, left side vertical is brightness and right side vertical is volume. 

On a side note, thank you for such a great app.

**Comment by laurencedawson** [comment]
Sorry but the YouTube player is a closed box and I can't change it at all.
