### ISSUE TITLE
[Feature Request] Text preview spoilers in card view

### ISSUE THREAD

**Issue by brianatlive** [laurencedawson/reddit-sync-development#955]
A lot of subreddits tag posts as NSFW when they contain a spoiler, but in post preview in card view, the first few line of the post are still visible. I've seen a few things I wish I hadn't because of this and I was wondering if there's anyway to fix it?

Is it possible to block text in the preview the same way spoilers in comments are or maybe to just not show the text at all if a post is marked as NSFW? I recognise that the second option could be a nuisance in blocking the text preview of some good wholesome non-spoilery smut so maybe there could be a way to block text previews if the post is marked NSFW and the word 'spoiler' is in the title.

**Comment by laurencedawson** [comment]
Do you have an example.?

**Comment by brianatlive** [comment]
For instance here there's enough text in the preview for the reader to take in the spoiler even if they don't want to.

![screenshot_2015-06-09-12-28-36](https://cloud.githubusercontent.com/assets/12753770/8057653/324e94ea-0eab-11e5-9847-449ff027fbfc.png)

**Comment by laurencedawson** [comment]
Added for the next release. Cheers!
