### ISSUE TITLE
[Feature Request] More consistent hamburger menu

### ISSUE THREAD

**Issue by erict4ng** [laurencedawson/reddit-sync-development#957]
At the moment the hamburger menu seems very inconsistent whereby it can only be accessed from subreddits that you are subscribed to and browsing, is it in the cards to add the ability to access the hamburger menu from places like inside posts, comments and searched subreddits.

**Comment by erict4ng** [comment]
I guess this would only work when the"swipe back from comments and posts " option is disabled.

**Comment by laurencedawson** [comment]
The hamburger can be accessed only on the root level as per the design docs.
