### ISSUE TITLE
[Feature Request] Use Chrome Custom Tabs api

### ISSUE THREAD

**Issue by sreich** [laurencedawson/reddit-sync-development#959]
New chrome custom tabs is now available in Chrome beta/dev with an enabled flag (enable hosted node). One can experience this by going into Google now and searching for something and clicking a site. It's a much better more integrated experience, and uses regular chrome. It was debuted in IO 2015. Would really love to see reddit sync get this.. Will make browsing so much better, especially for stuff that requires logins. 

https://developer.chrome.com/multidevice/android/customtabs

**Comment by richardg867** [comment]
Also make sure to allow opening with a browser normally if Chrome is not installed (ICS and Kindle Fire) or disabled.

**Comment by laurencedawson** [comment]
This is already in the works. Cheers!

**Comment by mbrevda** [comment]
I wonder if incognito tabs exist, too. Not everything belongs in history, y'know.

**Comment by laurencedawson** [comment]
This has been added in the upcoming V11 release.
