### ISSUE TITLE
[Feature Request] Use scrollbar from Google drive/docs

### ISSUE THREAD

**Issue by sreich** [laurencedawson/reddit-sync-development#960]
The scrollbar currently is a pretty odd one that is hard to hit properly and imho not too intuitive/easy on tablets or phones.. 

What I'd really like is a nice material scrollbar like Google docs has now. This one I personally find is much better for scrolling large amounts of content quickly, which I'm sure is why the gdocs team chose it.

**Comment by laurencedawson** [comment]
I'm not a fan of that scrollbar and it's actually custom sadly :(
