### ISSUE TITLE
Crash on android m when viewing long self posts. 

### ISSUE THREAD

**Issue by The-Nutty** [laurencedawson/reddit-sync-development#961]
The app crashes when viewing long text posts. Can be reproduced by viewing any long text post (for example go to /r/ama, sort by top, all time, then try to view the second post.

Phone: Nexus 5, Android M dev preview MPZ44Q.

>05-31 19:38:33.809  7882  7882 E AndroidRuntime: FATAL EXCEPTION: main
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: Process: com.laurencedawson.reddit_sync, PID: 7882
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: java.lang.IllegalStateException: Unable to create layer for CardLinearLayout
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5401)
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
>05-31 19:38:33.809  7882  7882 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)

**Comment by laurencedawson** [comment]
This is a known issue and will be fixed with the upcoming material redesign.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
