### ISSUE TITLE
Add List of Subreddits Contained within a Multireddit in the Sidebar

### ISSUE THREAD

**Issue by ehafling** [laurencedawson/reddit-sync-development#964]
![screenshot_2015-06-09-02-50-05](https://cloud.githubusercontent.com/assets/4794225/8054001/e7176498-0e5a-11e5-8321-6e46e9a888ee.png)

Currently the sidebar just states that it can't be used for Multireddits. Having a list of links for each of the subreddits contained within the Multireddit seems like it may be useful.

**Comment by laurencedawson** [comment]
Duplicate and already discussed in:

https://github.com/laurencedawson/reddit-sync-development/issues/359
