### ISSUE TITLE
Make the FAB more beautiful and animated

### ISSUE THREAD

**Issue by miladmaz12** [laurencedawson/reddit-sync-development#965]
https://www.reddit.com/r/redditsync/comments/30omsu/fab_comparison_with_inbox/

**Comment by laurencedawson** [comment]
Any reason why you closed and reopened?

**Comment by miladmaz12** [comment]
The original post kept getting me an error page. That's why I closed it and reopened it.

**Comment by laurencedawson** [comment]
I'll be leaving the FAB as it is for now.
