### ISSUE TITLE
No means to provide a context parameter when sharing comments.

### ISSUE THREAD

**Issue by kenklatt** [laurencedawson/reddit-sync-development#966]
I'm referring to the parameter 'context' as seen here...
https://www.reddit.com/r/redditsync/comments/2xy1dh/testing_a_new_feature_swipe_left_to_view_the_post/cp4gm8y?context=1

Presently I share to clipboard from reddit sync and manually add the context I want in Chrome or a text editor. It would be useful to choose the context level we want to provide when sharing a comment.

**Comment by laurencedawson** [comment]
Context is now applied automatically for the next release. Cheers.
