### ISSUE TITLE
[Feature Request] Browse posts by domain.

### ISSUE THREAD

**Issue by TheMrGhost** [laurencedawson/reddit-sync-development#967]
Hi, I'd love if you add a feature that allows to browse posts on a certain domain, like how you can click on the domain next to the post's link on Reddit's site and it takes you to a page like reddit.com/domain/imgur.com.  

Thanks.

**Comment by machinator2** [comment]
Related request post: https://www.reddit.com/r/redditsync/comments/51s8wl/request_get_support_for_domain_archives/

**Comment by laurencedawson** [comment]
This has since been added.

Cheers.
