### ISSUE TITLE
[Feature Request] Immersive Mode Option

### ISSUE THREAD

**Issue by j1my3p1x** [laurencedawson/reddit-sync-development#969]
Being able to hide the navigation bar and on screen keys would be awesome, especially on small screen sizes. Thanks so much Laurence for the app.

**Comment by laurencedawson** [comment]
Sorry for the slow reply.

The on screen keys api is just far too flakey. That's the reason I removed this initially.

However there are some nice xposed modules that force apps to run like this!

cheers.

**Comment by j1my3p1x** [comment]
Regardless, thank you for the reply. Much appreciated!
