### ISSUE TITLE
Automatic Sync & Background Sync in Notification Drawer

### ISSUE THREAD

**Issue by bmcclure937** [laurencedawson/reddit-sync-development#97]
The app currently syncs in the foreground and the user is unable to perform other tasks during this time. If the user taps on the screen it cancels the sync. Is there any way this can be scheduled as a background process? I know many apps create "notifications" that track status of things like this (downloads, syncs, uploads, backups, etc).

This would allow the user to do other things on the device while syncing. This would also create opportunities down the road to "schedule" this background process to run on certain intervals.

**Comment by laurencedawson** [comment]
Added for the next release!
