### ISSUE TITLE
Added, but not subscribed subbreddits get deleted on subreddit refresh

### ISSUE THREAD

**Issue by sqrt** [laurencedawson/reddit-sync-development#971]
This is closely linked to issue #617 and http://redd.it/18g0t6 (but not quite the same, so I file it as a separate issue just for reference).  Feel free to merge them.

It it possible to add subreddits to the list without subscribing to them. I often use this as simple bookmarks for subreddits I'd like to read from time to time, but which I don't want on my front page.

Now, refreshing the subreddit list removes those not-subscribed ones and they have to be re-added manually. It would be great if they sticked around at their respective position.

**Comment by laurencedawson** [comment]
Merging with:

https://github.com/laurencedawson/reddit-sync-development/issues/617
