### ISSUE TITLE
A hash sign in a search term will ignore the "Limit to subreddit" setting

### ISSUE THREAD

**Issue by jhinder** [laurencedawson/reddit-sync-development#973]
Version: 10.7.19

Steps to reproduce:
1. Go to any subreddit and bring up the search dialogue.
2. Enter text with a hash sign, e.g. "C#". (The bug occurs with and without the quotes.)
3. Check the "Limit to *subreddit*" box, and tap Search.

Expected result: The search is executed on the current subreddit using the search term.

Actual result: A search is done on /r/all, with everything after (and including) the hash sign being excluded from the search term.

Reproducible: yes, on any subreddit, on a fresh app install, and with both versions (free and pro).

[Two screenshots](https://imgur.com/YDz29Ue,tk3vGOx) of the bug.

**Comment by laurencedawson** [comment]
Fixed for the next release.
