### ISSUE TITLE
[Bug?] Ads open up automatically when using 3G - using free version

### ISSUE THREAD

**Issue by felekin** [laurencedawson/reddit-sync-development#977]
I'm not sure when this started to happen but it did after 2-3 updates ago but that could have been a while since i updated. Basically on wi-fi, no ads open up but it will when i use 3G. 

For reference, this happens even when i open up self-posts and not even links to other sites. It just happens almost every time i click a self-post on 3G. It is very frustrating and wasting my data. In addition, i don't click on the ads on the bottom and it's obvious that the link opened is different from the ad on the bottom of the screen because the opened ad is different from the one on displayed on the app.

Please fix this, i like reddit sync.

**Comment by laurencedawson** [comment]
I've removed the ad network that did this. Cheers.
