### ISSUE TITLE
[Feature request] Possibility to put multi-reddits first in menu

### ISSUE THREAD

**Issue by ThomasBerends** [laurencedawson/reddit-sync-development#979]
Make it possible to switch subreddits and mult-reddits in the menu, so multi-reddits are on top.

I always check the multi-reddits first, and now I'm just scrolling a lot. This would make it a lot easier.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/reddit-sync-development/issues/359
