### ISSUE TITLE
[Feature request] np.reddit/user link support in-app

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#981]
Refer to http://www.reddit.com/r/redditsync/comments/3afd7p/npreddituser_links_open_in_browser/. I am aware of https://github.com/laurencedawson/reddit-sync-development/issues/237, but I wanted to draw attention to user links in particular. Thanks.

**Comment by l3d00m** [comment]
Do you have content/link preloading activated? I think this is the problem.

**Comment by machinator2** [comment]
Even with it inactivated it doesn't work properly.

**Comment by laurencedawson** [comment]
Duplicate:

https://github.com/laurencedawson/reddit-sync-development/issues/237
