### ISSUE TITLE
set audio focus to music volume

### ISSUE THREAD

**Issue by willnorris** [laurencedawson/reddit-sync-development#986]
before clicking on a video link, I often want to turn down the media volume to make sure it's not too loud.  However, when reddit sync is running the volume buttons control the ringer volume.  This is because it doesn't set the audio focus.  For an example of apps that do set the focus, try using the volume buttons inside Google Play Music or YouTube (and Spotify as well I'm told, though I haven't tested that).

Docs: http://developer.android.com/training/managing-audio/audio-focus.html

**Comment by laurencedawson** [comment]
I don't feel it's right for sync to be requesting the audio focus.

Personally I'd be annoyed I could no longer change my ringer volume in app.

Does your volume screen not allow you to change the media volume once it's showing?
