### ISSUE TITLE
Album subtitles show null

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#987]
http://www.reddit.com/r/frugalmalefashion/comments/3bkozm/uniqlo_slim_straight_selvedge_for_1490/csn2yqo

Specifically, the Linc is: http://i.imgur.com/LxmIfxJ.jpg

And here is a screenshot: http://imgur.com/UL1VIGG

**Comment by nguyenmp** [comment]
v10.7.21

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
