### ISSUE TITLE
[Android M] App crashes loading any post from /r/dailyprogrammer

### ISSUE THREAD

**Issue by jwalters3** [laurencedawson/reddit-sync-development#988]
Example: http://www.reddit.com/r/dailyprogrammer/comments/3bi5na/20150629_challenge_221_easy_word_snake/
Device: Google Nexus 5
Android Version: M
App Version: 10.7.21

[logcat](https://gist.github.com/jwalters3/fc34defc3f08b96df56b)

**Comment by nguyenmp** [comment]
Probably related to #961

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers.
