### ISSUE TITLE
App Crash (logcat included; F/chromium(29957): [FATAL:jni_android.cc(295)]) when quickly opening/closing posts

### ISSUE THREAD

**Issue by ikjadoon** [laurencedawson/reddit-sync-development#990]
Hi! Relevant post from sub here: https://www.reddit.com/r/redditsync/comments/3btvi0/anyone_else_app_crashing_when_quickly_opening/

Basically, when opening and then rapidly closing a post that contains a URL (not a self-post), Reddit Sync crashes. I can reliably reproduce the issue. 

System details: 
stock unrooted CM12 on OnePlus One (Android 5.0.2)
Reddit Sync Pro 10.7.21

LOGCAT HERE: http://pastebin.com/U2wv8fHD

**Comment by franzks** [comment]
Might be related, my reddit sync crashed as well and found the error through ndk-stack when I was debugging my own app.

Nexus 6 unrooted running stock 5.1.1
Sync Pro version 10.7.21

Here's the crash dump:
http://pastie.org/10281075

**Comment by ikjadoon** [comment]
@franzks Yes! I think it is a Chromium/WebView bug here. On my phone, it only happens when I open and then relatively quickly close a story that uses WebView (I'm using the preview "slide" feature). Is that true for you, too?

**Comment by ikjadoon** [comment]
Fixed in v10.7.22

**Comment by laurencedawson** [comment]
Thanks for closing this.

**Comment by zewenwang** [comment]
hei, could somebody tell me how to fix this bug or what is the fixed commit id?

**Comment by MysteryAngle** [comment]
I have a same problem. but i don't know how to fix it.
This bug will crash my app.

**Comment by Abdelalim-dev** [comment]
For future reference.
I found this solution on [StackOverflow](https://stackoverflow.com/a/38036057/2317116):

Basically you destroy the Webview when the activity is destroyed (**onDestroy**) or when the fragment is destroyed (**onDestroyView**) if you're using fragments.
```
if (myWbView != null)
        myWbView.destroy();
```
