### ISSUE TITLE
Why are there two secret santas and one of them doesn't show the badge

### ISSUE THREAD

**Issue by miladmaz12** [laurencedawson/reddit-sync-development#991]
http://imgur.com/AixMoCZ

**Comment by nguyenmp** [comment]
There's a secret santa trophy for each year.  The first one is 2014 and the one with the missing link is 2013.

https://imgur.com/o2dv6KG

**Comment by laurencedawson** [comment]
So I looked into this. @nguyenmp was right, each yeah has its own badge however old badges sometimes used GIFs.

Sync is pretty strict about downloading GIFs where it doesn't expect them. In this case it didn't proceed.

I've added a fix for this and all trophies will be visible in the next release. 

Cheers!
