### ISSUE TITLE
App Crashes When browsing GIF albums

### ISSUE THREAD

**Issue by fezj** [laurencedawson/reddit-sync-development#994]
https://www.youtube.com/watch?v=BpN3RPw6gbU&feature=youtu.be

also check this thread for more information
http://www.reddit.com/r/redditsync/comments/3btj4z/_/

**Comment by machinator2** [comment]
Are you still seeing this issue?

**Comment by laurencedawson** [comment]
I've since replaced the old less stable GIF viewer with the v11 release.

If you're still seeing this issue let me know and I'll re-open this post. Cheers.
