### ISSUE TITLE
Link handling inconsistency

### ISSUE THREAD

**Issue by sanguinepar** [laurencedawson/reddit-sync-development#995]
Hi, apologies if this is a known issue.

I have link handling set to manage everything image and video related, but not other external links, eg to a regular webpage, Google Play or whatever. 

I've found that when I tap the thumbnail of a thread (I use small cards view) then this works fine. However, if I've opened the comments and THEN tap the OP link, Sync opens it in-app instead of taking me to a browser or the Play app.

Phone is an LGG3, rooted, running Cloudy 2.2.

Thanks :-)

**Comment by sanguinepar** [comment]
Sorry, app version is 10.7.19 if that helps.

**Comment by laurencedawson** [comment]
This should of been fixed with the v11 release. Cheers.
