### ISSUE TITLE
Brackets in a spoiler breaks the spoiler tag which reveals the spoiler.

### ISSUE THREAD

**Issue by Primeey** [laurencedawson/reddit-sync-development#996]
The comment on reddit: https://www.reddit.com/r/television/comments/3c6vwl/dragon_ball_super_premiered_today/cssuq8e

The comment as seen in sync for reddit:
http://i.imgur.com/0SBywfC.png

**Comment by laurencedawson** [comment]
That's a really strange spoiler actually. I think they've messed up encoding it but I've added additional support for these kinds of spoilers.
