### ISSUE TITLE
Possibility to leave imgur gallery in overview

### ISSUE THREAD

**Issue by thomassooon** [laurencedawson/reddit-sync-development#997]
I can leave an imgur gallery by tapping on an image of the gallery. On the last page of an imgur gallery there is an overview. A tap on the blank space there does nothing. Would it be possible to leave the gallery by doing that? Thanks for any responses.

See https://www.reddit.com/r/redditsync/comments/3c408o/leave_imgur_gallery_in_overview/

**Comment by laurencedawson** [comment]
I think as there is the X and also the back key I won't be adding in additional close methods. Cheers.
