### ISSUE TITLE
Link is incorrectly recognised as imgur image

### ISSUE THREAD

**Issue by Overv** [laurencedawson/reddit-sync-development#998]
The following post opens as image in the application just because it has "imgur" in the link:

https://www.reddit.com/r/programming/comments/3clho3/1_out_of_every_120_images_hosted_on_imgur_are/

**Comment by Moleculor** [comment]
As do many of the links here: https://www.reddit.com/r/technology/comments/3lw2g6/_/

Even trying to open up that link (once it's open in Sync) in a browser is broken.

**Comment by laurencedawson** [comment]
This has been fixed for the upcoming v11 release. Cheers.
