### ISSUE TITLE
Header text color in recents view is incorrect for some themes

### ISSUE THREAD

**Issue by afrolkin** [laurencedawson/reddit-sync-development#999]
Just a very minor thing thats been bothering me. In the recents view, for certain themes, the text colour for the header should be white to match the text colour in the action bar within the app. 

In the following screenshot, the app theme is set to "Light Blue" and the header text is black when it should be white.

![screenshot_20150709-112415](https://cloud.githubusercontent.com/assets/6852387/8599569/40b161c0-262f-11e5-8f10-632536c81622.png)

In other themes (like "Reddit Blue") the header text is white (which is correct).

![screenshot_20150709-112617](https://cloud.githubusercontent.com/assets/6852387/8599573/442386c6-262f-11e5-9d56-4e9c6aab232f.png)

This is on a Nexus 6 running the M preview.

**Comment by machinator2** [comment]
Are you still seeing this issue?

**Comment by afrolkin** [comment]
I am indeed still seeing this issue, in particular when using the "Light Blue" theme.

It's a very minor issue, and as I understand, there's no way to fix it as the text color is automatically generated.

**Comment by laurencedawson** [comment]
This is actually down to the system. Sadly there's no way to tell the overview what color to pick.
